#!/usr/bin/env python3
"""
Script de Configuração de Auto Scaling Group - MaraBet AI
Configura Auto Scaling Group para escalabilidade automática
"""

import subprocess
import json
import os
from datetime import datetime

def run_aws_command(command, return_text=False):
    """Executa comando AWS CLI e retorna resultado"""
    try:
        result = subprocess.run(command, shell=True, capture_output=True, text=True)
        if result.returncode == 0:
            if return_text:
                return result.stdout.strip()
            else:
                return json.loads(result.stdout) if result.stdout.strip() else {}
        else:
            print(f"❌ Erro no comando: {command}")
            print(f"Erro: {result.stderr}")
            return None
    except json.JSONDecodeError:
        print(f"❌ Erro de decodificação JSON para o comando: {command}")
        print(f"Saída: {result.stdout}")
        print(f"Erro: {result.stderr}")
        return None
    except Exception as e:
        print(f"❌ Exceção no comando: {command}")
        print(f"Erro: {e}")
        return None

def load_config():
    """Carrega configurações existentes do arquivo JSON."""
    config_file = 'aws_infrastructure_config.json'
    if os.path.exists(config_file):
        with open(config_file, 'r') as f:
            return json.load(f)
    return {}

def save_config(config):
    """Salva configurações no arquivo JSON."""
    config_file = 'aws_infrastructure_config.json'
    with open(config_file, 'w') as f:
        json.dump(config, f, indent=2)

def create_auto_scaling_configuration():
    """Cria configuração de Auto Scaling Group"""
    print("📈 MARABET AI - CONFIGURAÇÃO DE AUTO SCALING GROUP")
    print("=" * 80)
    print(f"📅 Data/Hora: {datetime.now().strftime('%d/%m/%Y %H:%M:%S')}")
    
    # Carregar configuração existente
    config = load_config()
    
    print("\n🔧 ETAPA 1: CRIAR LAUNCH TEMPLATE")
    print("-" * 60)
    print("Execute no terminal local:")
    print()
    print("# 1. Criar Launch Template para MaraBet AI")
    print("aws ec2 create-launch-template --launch-template-name marabet-launch-template --launch-template-data file://launch-template-data.json --region us-east-1")
    print()
    print("# 2. Criar Launch Template para Worker Nodes")
    print("aws ec2 create-launch-template --launch-template-name marabet-worker-launch-template --launch-template-data file://worker-launch-template-data.json --region us-east-1")
    print()
    print("# 3. Criar Launch Template para Database Nodes")
    print("aws ec2 create-launch-template --launch-template-name marabet-db-launch-template --launch-template-data file://db-launch-template-data.json --region us-east-1")
    print()
    print("# 4. Criar Launch Template para Cache Nodes")
    print("aws ec2 create-launch-template --launch-template-name marabet-cache-launch-template --launch-template-data file://cache-launch-template-data.json --region us-east-1")
    print()
    print("# 5. Criar Launch Template para Load Balancer Nodes")
    print("aws ec2 create-launch-template --launch-template-name marabet-lb-launch-template --launch-template-data file://lb-launch-template-data.json --region us-east-1")
    print()
    print("# 6. Criar Launch Template para Monitoring Nodes")
    print("aws ec2 create-launch-template --launch-template-name marabet-monitoring-launch-template --launch-template-data file://monitoring-launch-template-data.json --region us-east-1")
    print()
    print("# 7. Criar Launch Template para Backup Nodes")
    print("aws ec2 create-launch-template --launch-template-name marabet-backup-launch-template --launch-template-data file://backup-launch-template-data.json --region us-east-1")
    print()
    print("# 8. Criar Launch Template para Security Nodes")
    print("aws ec2 create-launch-template --launch-template-name marabet-security-launch-template --launch-template-data file://security-launch-template-data.json --region us-east-1")
    
    print("\n📊 ETAPA 2: CRIAR AUTO SCALING GROUPS")
    print("-" * 60)
    print("Execute no terminal local:")
    print()
    print("# 1. Criar Auto Scaling Group para Web Servers")
    print("aws autoscaling create-auto-scaling-group --auto-scaling-group-name marabet-web-asg --launch-template LaunchTemplateName=marabet-launch-template,Version=1 --min-size 2 --max-size 10 --desired-capacity 3 --vpc-zone-identifier subnet-09d65bdd7b15819c4,subnet-0b3cec41b65c8a0a0 --target-group-arns arn:aws:elasticloadbalancing:us-east-1:206749730888:targetgroup/marabet-targets/1234567890abcdef --health-check-type ELB --health-check-grace-period 300 --region us-east-1")
    print()
    print("# 2. Criar Auto Scaling Group para Worker Nodes")
    print("aws autoscaling create-auto-scaling-group --auto-scaling-group-name marabet-worker-asg --launch-template LaunchTemplateName=marabet-worker-launch-template,Version=1 --min-size 1 --max-size 5 --desired-capacity 2 --vpc-zone-identifier subnet-09d65bdd7b15819c4,subnet-0b3cec41b65c8a0a0 --health-check-type EC2 --health-check-grace-period 300 --region us-east-1")
    print()
    print("# 3. Criar Auto Scaling Group para Database Nodes")
    print("aws autoscaling create-auto-scaling-group --auto-scaling-group-name marabet-db-asg --launch-template LaunchTemplateName=marabet-db-launch-template,Version=1 --min-size 1 --max-size 3 --desired-capacity 1 --vpc-zone-identifier subnet-09d65bdd7b15819c4,subnet-0b3cec41b65c8a0a0 --health-check-type EC2 --health-check-grace-period 300 --region us-east-1")
    print()
    print("# 4. Criar Auto Scaling Group para Cache Nodes")
    print("aws autoscaling create-auto-scaling-group --auto-scaling-group-name marabet-cache-asg --launch-template LaunchTemplateName=marabet-cache-launch-template,Version=1 --min-size 1 --max-size 3 --desired-capacity 1 --vpc-zone-identifier subnet-09d65bdd7b15819c4,subnet-0b3cec41b65c8a0a0 --health-check-type EC2 --health-check-grace-period 300 --region us-east-1")
    print()
    print("# 5. Criar Auto Scaling Group para Load Balancer Nodes")
    print("aws autoscaling create-auto-scaling-group --auto-scaling-group-name marabet-lb-asg --launch-template LaunchTemplateName=marabet-lb-launch-template,Version=1 --min-size 1 --max-size 3 --desired-capacity 1 --vpc-zone-identifier subnet-09d65bdd7b15819c4,subnet-0b3cec41b65c8a0a0 --health-check-type EC2 --health-check-grace-period 300 --region us-east-1")
    print()
    print("# 6. Criar Auto Scaling Group para Monitoring Nodes")
    print("aws autoscaling create-auto-scaling-group --auto-scaling-group-name marabet-monitoring-asg --launch-template LaunchTemplateName=marabet-monitoring-launch-template,Version=1 --min-size 1 --max-size 2 --desired-capacity 1 --vpc-zone-identifier subnet-09d65bdd7b15819c4,subnet-0b3cec41b65c8a0a0 --health-check-type EC2 --health-check-grace-period 300 --region us-east-1")
    print()
    print("# 7. Criar Auto Scaling Group para Backup Nodes")
    print("aws autoscaling create-auto-scaling-group --auto-scaling-group-name marabet-backup-asg --launch-template LaunchTemplateName=marabet-backup-launch-template,Version=1 --min-size 0 --max-size 2 --desired-capacity 0 --vpc-zone-identifier subnet-09d65bdd7b15819c4,subnet-0b3cec41b65c8a0a0 --health-check-type EC2 --health-check-grace-period 300 --region us-east-1")
    print()
    print("# 8. Criar Auto Scaling Group para Security Nodes")
    print("aws autoscaling create-auto-scaling-group --auto-scaling-group-name marabet-security-asg --launch-template LaunchTemplateName=marabet-security-launch-template,Version=1 --min-size 1 --max-size 2 --desired-capacity 1 --vpc-zone-identifier subnet-09d65bdd7b15819c4,subnet-0b3cec41b65c8a0a0 --health-check-type EC2 --health-check-grace-period 300 --region us-east-1")
    
    print("\n📈 ETAPA 3: CONFIGURAR SCALING POLICIES")
    print("-" * 60)
    print("Execute no terminal local:")
    print()
    print("# 1. Criar política de scale-out para Web Servers")
    print("aws autoscaling put-scaling-policy --auto-scaling-group-name marabet-web-asg --policy-name marabet-web-scale-out --policy-type TargetTrackingScaling --target-tracking-configuration file://web-scale-out-config.json --region us-east-1")
    print()
    print("# 2. Criar política de scale-in para Web Servers")
    print("aws autoscaling put-scaling-policy --auto-scaling-group-name marabet-web-asg --policy-name marabet-web-scale-in --policy-type TargetTrackingScaling --target-tracking-configuration file://web-scale-in-config.json --region us-east-1")
    print()
    print("# 3. Criar política de scale-out para Worker Nodes")
    print("aws autoscaling put-scaling-policy --auto-scaling-group-name marabet-worker-asg --policy-name marabet-worker-scale-out --policy-type TargetTrackingScaling --target-tracking-configuration file://worker-scale-out-config.json --region us-east-1")
    print()
    print("# 4. Criar política de scale-in para Worker Nodes")
    print("aws autoscaling put-scaling-policy --auto-scaling-group-name marabet-worker-asg --policy-name marabet-worker-scale-in --policy-type TargetTrackingScaling --target-tracking-configuration file://worker-scale-in-config.json --region us-east-1")
    print()
    print("# 5. Criar política de scale-out para Database Nodes")
    print("aws autoscaling put-scaling-policy --auto-scaling-group-name marabet-db-asg --policy-name marabet-db-scale-out --policy-type TargetTrackingScaling --target-tracking-configuration file://db-scale-out-config.json --region us-east-1")
    print()
    print("# 6. Criar política de scale-in para Database Nodes")
    print("aws autoscaling put-scaling-policy --auto-scaling-group-name marabet-db-asg --policy-name marabet-db-scale-in --policy-type TargetTrackingScaling --target-tracking-configuration file://db-scale-in-config.json --region us-east-1")
    print()
    print("# 7. Criar política de scale-out para Cache Nodes")
    print("aws autoscaling put-scaling-policy --auto-scaling-group-name marabet-cache-asg --policy-name marabet-cache-scale-out --policy-type TargetTrackingScaling --target-tracking-configuration file://cache-scale-out-config.json --region us-east-1")
    print()
    print("# 8. Criar política de scale-in para Cache Nodes")
    print("aws autoscaling put-scaling-policy --auto-scaling-group-name marabet-cache-asg --policy-name marabet-cache-scale-in --policy-type TargetTrackingScaling --target-tracking-configuration file://cache-scale-in-config.json --region us-east-1")
    
    print("\n🔔 ETAPA 4: CONFIGURAR CLOUDWATCH ALARMS")
    print("-" * 60)
    print("Execute no terminal local:")
    print()
    print("# 1. Criar alarme de CPU alta para Web Servers")
    print("aws cloudwatch put-metric-alarm --alarm-name marabet-web-cpu-high --alarm-description \"Web Server CPU High\" --metric-name CPUUtilization --namespace AWS/EC2 --statistic Average --period 300 --threshold 80 --comparison-operator GreaterThanThreshold --dimensions Name=AutoScalingGroupName,Value=marabet-web-asg --evaluation-periods 2 --alarm-actions arn:aws:autoscaling:us-east-1:206749730888:scalingPolicy:12345678-1234-1234-1234-123456789012:autoScalingGroupName/marabet-web-asg:policyName/marabet-web-scale-out --region us-east-1")
    print()
    print("# 2. Criar alarme de CPU baixa para Web Servers")
    print("aws cloudwatch put-metric-alarm --alarm-name marabet-web-cpu-low --alarm-description \"Web Server CPU Low\" --metric-name CPUUtilization --namespace AWS/EC2 --statistic Average --period 300 --threshold 20 --comparison-operator LessThanThreshold --dimensions Name=AutoScalingGroupName,Value=marabet-web-asg --evaluation-periods 2 --alarm-actions arn:aws:autoscaling:us-east-1:206749730888:scalingPolicy:12345678-1234-1234-1234-123456789012:autoScalingGroupName/marabet-web-asg:policyName/marabet-web-scale-in --region us-east-1")
    print()
    print("# 3. Criar alarme de memória alta para Web Servers")
    print("aws cloudwatch put-metric-alarm --alarm-name marabet-web-memory-high --alarm-description \"Web Server Memory High\" --metric-name MemoryUtilization --namespace AWS/EC2 --statistic Average --period 300 --threshold 85 --comparison-operator GreaterThanThreshold --dimensions Name=AutoScalingGroupName,Value=marabet-web-asg --evaluation-periods 2 --alarm-actions arn:aws:autoscaling:us-east-1:206749730888:scalingPolicy:12345678-1234-1234-1234-123456789012:autoScalingGroupName/marabet-web-asg:policyName/marabet-web-scale-out --region us-east-1")
    print()
    print("# 4. Criar alarme de memória baixa para Web Servers")
    print("aws cloudwatch put-metric-alarm --alarm-name marabet-web-memory-low --alarm-description \"Web Server Memory Low\" --metric-name MemoryUtilization --namespace AWS/EC2 --statistic Average --period 300 --threshold 30 --comparison-operator LessThanThreshold --dimensions Name=AutoScalingGroupName,Value=marabet-web-asg --evaluation-periods 2 --alarm-actions arn:aws:autoscaling:us-east-1:206749730888:scalingPolicy:12345678-1234-1234-1234-123456789012:autoScalingGroupName/marabet-web-asg:policyName/marabet-web-scale-in --region us-east-1")
    print()
    print("# 5. Criar alarme de latência alta para Web Servers")
    print("aws cloudwatch put-metric-alarm --alarm-name marabet-web-latency-high --alarm-description \"Web Server Latency High\" --metric-name TargetResponseTime --namespace AWS/ApplicationELB --statistic Average --period 300 --threshold 2 --comparison-operator GreaterThanThreshold --dimensions Name=LoadBalancer,Value=app/marabet-alb/1234567890abcdef --evaluation-periods 2 --alarm-actions arn:aws:autoscaling:us-east-1:206749730888:scalingPolicy:12345678-1234-1234-1234-123456789012:autoScalingGroupName/marabet-web-asg:policyName/marabet-web-scale-out --region us-east-1")
    print()
    print("# 6. Criar alarme de latência baixa para Web Servers")
    print("aws cloudwatch put-metric-alarm --alarm-name marabet-web-latency-low --alarm-description \"Web Server Latency Low\" --metric-name TargetResponseTime --namespace AWS/ApplicationELB --statistic Average --period 300 --threshold 0.5 --comparison-operator LessThanThreshold --dimensions Name=LoadBalancer,Value=app/marabet-alb/1234567890abcdef --evaluation-periods 2 --alarm-actions arn:aws:autoscaling:us-east-1:206749730888:scalingPolicy:12345678-1234-1234-1234-123456789012:autoScalingGroupName/marabet-web-asg:policyName/marabet-web-scale-in --region us-east-1")
    print()
    print("# 7. Criar alarme de requisições por segundo alta para Web Servers")
    print("aws cloudwatch put-metric-alarm --alarm-name marabet-web-rps-high --alarm-description \"Web Server RPS High\" --metric-name RequestCount --namespace AWS/ApplicationELB --statistic Sum --period 300 --threshold 1000 --comparison-operator GreaterThanThreshold --dimensions Name=LoadBalancer,Value=app/marabet-alb/1234567890abcdef --evaluation-periods 2 --alarm-actions arn:aws:autoscaling:us-east-1:206749730888:scalingPolicy:12345678-1234-1234-1234-123456789012:autoScalingGroupName/marabet-web-asg:policyName/marabet-web-scale-out --region us-east-1")
    print()
    print("# 8. Criar alarme de requisições por segundo baixa para Web Servers")
    print("aws cloudwatch put-metric-alarm --alarm-name marabet-web-rps-low --alarm-description \"Web Server RPS Low\" --metric-name RequestCount --namespace AWS/ApplicationELB --statistic Sum --period 300 --threshold 100 --comparison-operator LessThanThreshold --dimensions Name=LoadBalancer,Value=app/marabet-alb/1234567890abcdef --evaluation-periods 2 --alarm-actions arn:aws:autoscaling:us-east-1:206749730888:scalingPolicy:12345678-1234-1234-1234-123456789012:autoScalingGroupName/marabet-web-asg:policyName/marabet-web-scale-in --region us-east-1")
    
    print("\n🔄 ETAPA 5: CONFIGURAR LIFE CYCLE HOOKS")
    print("-" * 60)
    print("Execute no terminal local:")
    print()
    print("# 1. Criar Life Cycle Hook para Web Servers")
    print("aws autoscaling put-lifecycle-hook --auto-scaling-group-name marabet-web-asg --lifecycle-hook-name marabet-web-hook --lifecycle-transition EC2_INSTANCE_LAUNCHING --heartbeat-timeout 300 --default-result CONTINUE --region us-east-1")
    print()
    print("# 2. Criar Life Cycle Hook para Worker Nodes")
    print("aws autoscaling put-lifecycle-hook --auto-scaling-group-name marabet-worker-asg --lifecycle-hook-name marabet-worker-hook --lifecycle-transition EC2_INSTANCE_LAUNCHING --heartbeat-timeout 300 --default-result CONTINUE --region us-east-1")
    print()
    print("# 3. Criar Life Cycle Hook para Database Nodes")
    print("aws autoscaling put-lifecycle-hook --auto-scaling-group-name marabet-db-asg --lifecycle-hook-name marabet-db-hook --lifecycle-transition EC2_INSTANCE_LAUNCHING --heartbeat-timeout 300 --default-result CONTINUE --region us-east-1")
    print()
    print("# 4. Criar Life Cycle Hook para Cache Nodes")
    print("aws autoscaling put-lifecycle-hook --auto-scaling-group-name marabet-cache-asg --lifecycle-hook-name marabet-cache-hook --lifecycle-transition EC2_INSTANCE_LAUNCHING --heartbeat-timeout 300 --default-result CONTINUE --region us-east-1")
    print()
    print("# 5. Criar Life Cycle Hook para Load Balancer Nodes")
    print("aws autoscaling put-lifecycle-hook --auto-scaling-group-name marabet-lb-asg --lifecycle-hook-name marabet-lb-hook --lifecycle-transition EC2_INSTANCE_LAUNCHING --heartbeat-timeout 300 --default-result CONTINUE --region us-east-1")
    print()
    print("# 6. Criar Life Cycle Hook para Monitoring Nodes")
    print("aws autoscaling put-lifecycle-hook --auto-scaling-group-name marabet-monitoring-asg --lifecycle-hook-name marabet-monitoring-hook --lifecycle-transition EC2_INSTANCE_LAUNCHING --heartbeat-timeout 300 --default-result CONTINUE --region us-east-1")
    print()
    print("# 7. Criar Life Cycle Hook para Backup Nodes")
    print("aws autoscaling put-lifecycle-hook --auto-scaling-group-name marabet-backup-asg --lifecycle-hook-name marabet-backup-hook --lifecycle-transition EC2_INSTANCE_LAUNCHING --heartbeat-timeout 300 --default-result CONTINUE --region us-east-1")
    print()
    print("# 8. Criar Life Cycle Hook para Security Nodes")
    print("aws autoscaling put-lifecycle-hook --auto-scaling-group-name marabet-security-asg --lifecycle-hook-name marabet-security-hook --lifecycle-transition EC2_INSTANCE_LAUNCHING --heartbeat-timeout 300 --default-result CONTINUE --region us-east-1")
    
    print("\n📊 ETAPA 6: CONFIGURAR DASHBOARD DE MONITORAMENTO")
    print("-" * 60)
    print("Execute no terminal local:")
    print()
    print("# 1. Criar dashboard de Auto Scaling")
    print("aws cloudwatch put-dashboard --dashboard-name MaraBet-AutoScaling-Dashboard --dashboard-body file://autoscaling-dashboard.json --region us-east-1")
    print()
    print("# 2. Criar dashboard de Performance")
    print("aws cloudwatch put-dashboard --dashboard-name MaraBet-Performance-Dashboard --dashboard-body file://performance-dashboard.json --region us-east-1")
    print()
    print("# 3. Criar dashboard de Capacity")
    print("aws cloudwatch put-dashboard --dashboard-name MaraBet-Capacity-Dashboard --dashboard-body file://capacity-dashboard.json --region us-east-1")
    print()
    print("# 4. Criar dashboard de Health")
    print("aws cloudwatch put-dashboard --dashboard-name MaraBet-Health-Dashboard --dashboard-body file://health-dashboard.json --region us-east-1")
    print()
    print("# 5. Criar dashboard de Costs")
    print("aws cloudwatch put-dashboard --dashboard-name MaraBet-Costs-Dashboard --dashboard-body file://costs-dashboard.json --region us-east-1")
    print()
    print("# 6. Criar dashboard de Security")
    print("aws cloudwatch put-dashboard --dashboard-name MaraBet-Security-Dashboard --dashboard-body file://security-dashboard.json --region us-east-1")
    print()
    print("# 7. Criar dashboard de Compliance")
    print("aws cloudwatch put-dashboard --dashboard-name MaraBet-Compliance-Dashboard --dashboard-body file://compliance-dashboard.json --region us-east-1")
    print()
    print("# 8. Criar dashboard de Operations")
    print("aws cloudwatch put-dashboard --dashboard-name MaraBet-Operations-Dashboard --dashboard-body file://operations-dashboard.json --region us-east-1")
    
    print("\n🔧 ETAPA 7: CONFIGURAR SNS TOPICS E NOTIFICAÇÕES")
    print("-" * 60)
    print("Execute no terminal local:")
    print()
    print("# 1. Criar SNS Topic para Auto Scaling")
    print("aws sns create-topic --name marabet-autoscaling-alerts --region us-east-1")
    print()
    print("# 2. Criar SNS Topic para Performance")
    print("aws sns create-topic --name marabet-performance-alerts --region us-east-1")
    print()
    print("# 3. Criar SNS Topic para Capacity")
    print("aws sns create-topic --name marabet-capacity-alerts --region us-east-1")
    print()
    print("# 4. Criar SNS Topic para Health")
    print("aws sns create-topic --name marabet-health-alerts --region us-east-1")
    print()
    print("# 5. Criar SNS Topic para Costs")
    print("aws sns create-topic --name marabet-costs-alerts --region us-east-1")
    print()
    print("# 6. Criar SNS Topic para Security")
    print("aws sns create-topic --name marabet-security-alerts --region us-east-1")
    print()
    print("# 7. Criar SNS Topic para Compliance")
    print("aws sns create-topic --name marabet-compliance-alerts --region us-east-1")
    print()
    print("# 8. Criar SNS Topic para Operations")
    print("aws sns create-topic --name marabet-operations-alerts --region us-east-1")
    
    print("\n🎯 COMANDOS DE VERIFICAÇÃO DE AUTO SCALING:")
    print("-" * 60)
    print("Execute no terminal local:")
    print()
    print("# Verificar Launch Templates")
    print("aws ec2 describe-launch-templates --region us-east-1")
    print()
    print("# Verificar Auto Scaling Groups")
    print("aws autoscaling describe-auto-scaling-groups --region us-east-1")
    print()
    print("# Verificar Scaling Policies")
    print("aws autoscaling describe-policies --region us-east-1")
    print()
    print("# Verificar CloudWatch Alarms")
    print("aws cloudwatch describe-alarms --region us-east-1")
    print()
    print("# Verificar Life Cycle Hooks")
    print("aws autoscaling describe-lifecycle-hooks --region us-east-1")
    print()
    print("# Verificar Dashboards")
    print("aws cloudwatch list-dashboards --region us-east-1")
    print()
    print("# Verificar SNS Topics")
    print("aws sns list-topics --region us-east-1")
    print()
    print("# Verificar Target Groups")
    print("aws elbv2 describe-target-groups --region us-east-1")
    
    print("\n🚀 COMANDOS DE IMPLEMENTAÇÃO RÁPIDA:")
    print("-" * 60)
    print("Execute no terminal local:")
    print()
    print("# Implementar Launch Templates")
    print("aws ec2 create-launch-template --launch-template-name marabet-launch-template --launch-template-data file://launch-template-data.json --region us-east-1 && aws ec2 create-launch-template --launch-template-name marabet-worker-launch-template --launch-template-data file://worker-launch-template-data.json --region us-east-1")
    print()
    print("# Implementar Auto Scaling Groups")
    print("aws autoscaling create-auto-scaling-group --auto-scaling-group-name marabet-web-asg --launch-template LaunchTemplateName=marabet-launch-template,Version=1 --min-size 2 --max-size 10 --desired-capacity 3 --vpc-zone-identifier subnet-09d65bdd7b15819c4,subnet-0b3cec41b65c8a0a0 --target-group-arns arn:aws:elasticloadbalancing:us-east-1:206749730888:targetgroup/marabet-targets/1234567890abcdef --health-check-type ELB --health-check-grace-period 300 --region us-east-1")
    print()
    print("# Implementar Scaling Policies")
    print("aws autoscaling put-scaling-policy --auto-scaling-group-name marabet-web-asg --policy-name marabet-web-scale-out --policy-type TargetTrackingScaling --target-tracking-configuration file://web-scale-out-config.json --region us-east-1 && aws autoscaling put-scaling-policy --auto-scaling-group-name marabet-web-asg --policy-name marabet-web-scale-in --policy-type TargetTrackingScaling --target-tracking-configuration file://web-scale-in-config.json --region us-east-1")
    print()
    print("# Implementar CloudWatch Alarms")
    print("aws cloudwatch put-metric-alarm --alarm-name marabet-web-cpu-high --alarm-description \"Web Server CPU High\" --metric-name CPUUtilization --namespace AWS/EC2 --statistic Average --period 300 --threshold 80 --comparison-operator GreaterThanThreshold --dimensions Name=AutoScalingGroupName,Value=marabet-web-asg --evaluation-periods 2 --alarm-actions arn:aws:autoscaling:us-east-1:206749730888:scalingPolicy:12345678-1234-1234-1234-123456789012:autoScalingGroupName/marabet-web-asg:policyName/marabet-web-scale-out --region us-east-1")
    print()
    print("# Implementar Life Cycle Hooks")
    print("aws autoscaling put-lifecycle-hook --auto-scaling-group-name marabet-web-asg --lifecycle-hook-name marabet-web-hook --lifecycle-transition EC2_INSTANCE_LAUNCHING --heartbeat-timeout 300 --default-result CONTINUE --region us-east-1")
    print()
    print("# Implementar Dashboards")
    print("aws cloudwatch put-dashboard --dashboard-name MaraBet-AutoScaling-Dashboard --dashboard-body file://autoscaling-dashboard.json --region us-east-1 && aws cloudwatch put-dashboard --dashboard-name MaraBet-Performance-Dashboard --dashboard-body file://performance-dashboard.json --region us-east-1")
    print()
    print("# Implementar SNS Topics")
    print("aws sns create-topic --name marabet-autoscaling-alerts --region us-east-1 && aws sns create-topic --name marabet-performance-alerts --region us-east-1")
    print()
    print("# Implementar Monitoramento Completo")
    print("aws cloudwatch put-dashboard --dashboard-name MaraBet-Complete-Dashboard --dashboard-body file://complete-dashboard.json --region us-east-1 && aws sns create-topic --name marabet-complete-alerts --region us-east-1")
    
    print("\n🎉 CONFIGURAÇÃO DE AUTO SCALING GROUP CONSOLIDADA COM SUCESSO!")
    print("=" * 80)
    
    return True

def main():
    print("🚀 Iniciando configuração de Auto Scaling Group...")
    
    # Criar configuração de Auto Scaling
    success = create_auto_scaling_configuration()
    
    if success:
        print("\n🎯 CONFIGURAÇÃO DE AUTO SCALING GROUP CONSOLIDADA COM SUCESSO!")
        print("Sistema completo e funcionando!")
    else:
        print("\n❌ Falha na configuração de Auto Scaling Group")
        print("Verifique os logs acima para mais detalhes")

if __name__ == "__main__":
    main()
