#!/usr/bin/env python3
"""
Script de Configuração de CI/CD - MaraBet AI
Configura GitHub Actions para deploy automático
"""

import subprocess
import json
import os
from datetime import datetime

def run_aws_command(command, return_text=False):
    """Executa comando AWS CLI e retorna resultado"""
    try:
        result = subprocess.run(command, shell=True, capture_output=True, text=True)
        if result.returncode == 0:
            if return_text:
                return result.stdout.strip()
            else:
                return json.loads(result.stdout) if result.stdout.strip() else {}
        else:
            print(f"❌ Erro no comando: {command}")
            print(f"Erro: {result.stderr}")
            return None
    except json.JSONDecodeError:
        print(f"❌ Erro de decodificação JSON para o comando: {command}")
        print(f"Saída: {result.stdout}")
        print(f"Erro: {result.stderr}")
        return None
    except Exception as e:
        print(f"❌ Exceção no comando: {command}")
        print(f"Erro: {e}")
        return None

def load_config():
    """Carrega configurações existentes do arquivo JSON."""
    config_file = 'aws_infrastructure_config.json'
    if os.path.exists(config_file):
        with open(config_file, 'r') as f:
            return json.load(f)
    return {}

def save_config(config):
    """Salva configurações no arquivo JSON."""
    config_file = 'aws_infrastructure_config.json'
    with open(config_file, 'w') as f:
        json.dump(config, f, indent=2)

def create_cicd_configuration():
    """Cria configuração de CI/CD com GitHub Actions"""
    print("🚀 MARABET AI - CONFIGURAÇÃO DE CI/CD COM GITHUB ACTIONS")
    print("=" * 80)
    print(f"📅 Data/Hora: {datetime.now().strftime('%d/%m/%Y %H:%M:%S')}")
    
    # Carregar configuração existente
    config = load_config()
    
    print("\n🔧 ETAPA 1: CRIAR ESTRUTURA DE GITHUB ACTIONS")
    print("-" * 60)
    print("Execute no terminal local:")
    print()
    print("# 1. Criar diretório .github/workflows")
    print("mkdir -p .github/workflows")
    print()
    print("# 2. Criar workflow de deploy para produção")
    print("touch .github/workflows/deploy-production.yml")
    print()
    print("# 3. Criar workflow de deploy para staging")
    print("touch .github/workflows/deploy-staging.yml")
    print()
    print("# 4. Criar workflow de testes")
    print("touch .github/workflows/test.yml")
    print()
    print("# 5. Criar workflow de build")
    print("touch .github/workflows/build.yml")
    print()
    print("# 6. Criar workflow de security scan")
    print("touch .github/workflows/security-scan.yml")
    print()
    print("# 7. Criar workflow de performance test")
    print("touch .github/workflows/performance-test.yml")
    print()
    print("# 8. Criar workflow de backup")
    print("touch .github/workflows/backup.yml")
    
    print("\n📋 ETAPA 2: CONFIGURAR SECRETS DO GITHUB")
    print("-" * 60)
    print("Execute no terminal local:")
    print()
    print("# 1. Configurar AWS_ACCESS_KEY_ID")
    print("gh secret set AWS_ACCESS_KEY_ID --body \"AKIAIOSFODNN7EXAMPLE\"")
    print()
    print("# 2. Configurar AWS_SECRET_ACCESS_KEY")
    print("gh secret set AWS_SECRET_ACCESS_KEY --body \"wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY\"")
    print()
    print("# 3. Configurar AWS_REGION")
    print("gh secret set AWS_REGION --body \"us-east-1\"")
    print()
    print("# 4. Configurar ECR_REGISTRY")
    print("gh secret set ECR_REGISTRY --body \"206749730888.dkr.ecr.us-east-1.amazonaws.com\"")
    print()
    print("# 5. Configurar ECR_REPOSITORY")
    print("gh secret set ECR_REPOSITORY --body \"marabet-ai\"")
    print()
    print("# 6. Configurar DATABASE_URL")
    print("gh secret set DATABASE_URL --body \"postgresql://marabetadmin:MaraBet2024!SuperSecret@marabet-db.cmvmwskgiabr.us-east-1.rds.amazonaws.com:5432/postgres\"")
    print()
    print("# 7. Configurar REDIS_URL")
    print("gh secret set REDIS_URL --body \"redis://marabet-redis.ve5qk7.0001.use1.cache.amazonaws.com:6379\"")
    print()
    print("# 8. Configurar API_FOOTBALL_KEY")
    print("gh secret set API_FOOTBALL_KEY --body \"71b2b62386f2d1275cd3201a73e1e045\"")
    
    print("\n🐳 ETAPA 3: CONFIGURAR ECR (ELASTIC CONTAINER REGISTRY)")
    print("-" * 60)
    print("Execute no terminal local:")
    print()
    print("# 1. Criar repositório ECR")
    print("aws ecr create-repository --repository-name marabet-ai --region us-east-1")
    print()
    print("# 2. Criar repositório ECR para staging")
    print("aws ecr create-repository --repository-name marabet-ai-staging --region us-east-1")
    print()
    print("# 3. Criar repositório ECR para desenvolvimento")
    print("aws ecr create-repository --repository-name marabet-ai-dev --region us-east-1")
    print()
    print("# 4. Configurar política de lifecycle do ECR")
    print("aws ecr put-lifecycle-policy --repository-name marabet-ai --lifecycle-policy-text file://ecr-lifecycle-policy.json --region us-east-1")
    print()
    print("# 5. Configurar política de lifecycle do ECR staging")
    print("aws ecr put-lifecycle-policy --repository-name marabet-ai-staging --lifecycle-policy-text file://ecr-lifecycle-policy-staging.json --region us-east-1")
    print()
    print("# 6. Configurar política de lifecycle do ECR dev")
    print("aws ecr put-lifecycle-policy --repository-name marabet-ai-dev --lifecycle-policy-text file://ecr-lifecycle-policy-dev.json --region us-east-1")
    print()
    print("# 7. Configurar política de repositório do ECR")
    print("aws ecr set-repository-policy --repository-name marabet-ai --policy-text file://ecr-repository-policy.json --region us-east-1")
    print()
    print("# 8. Configurar política de repositório do ECR staging")
    print("aws ecr set-repository-policy --repository-name marabet-ai-staging --policy-text file://ecr-repository-policy-staging.json --region us-east-1")
    
    print("\n🔐 ETAPA 4: CONFIGURAR IAM ROLES E POLICIES")
    print("-" * 60)
    print("Execute no terminal local:")
    print()
    print("# 1. Criar role para GitHub Actions")
    print("aws iam create-role --role-name GitHubActionsRole --assume-role-policy-document file://github-actions-trust-policy.json --region us-east-1")
    print()
    print("# 2. Criar policy para GitHub Actions")
    print("aws iam create-policy --policy-name GitHubActionsPolicy --policy-document file://github-actions-policy.json --region us-east-1")
    print()
    print("# 3. Anexar policy à role")
    print("aws iam attach-role-policy --role-name GitHubActionsRole --policy-arn arn:aws:iam::206749730888:policy/GitHubActionsPolicy --region us-east-1")
    print()
    print("# 4. Criar role para ECS Task")
    print("aws iam create-role --role-name ECSTaskRole --assume-role-policy-document file://ecs-task-trust-policy.json --region us-east-1")
    print()
    print("# 5. Criar policy para ECS Task")
    print("aws iam create-policy --policy-name ECSTaskPolicy --policy-document file://ecs-task-policy.json --region us-east-1")
    print()
    print("# 6. Anexar policy à role ECS Task")
    print("aws iam attach-role-policy --role-name ECSTaskRole --policy-arn arn:aws:iam::206749730888:policy/ECSTaskPolicy --region us-east-1")
    print()
    print("# 7. Criar role para ECS Execution")
    print("aws iam create-role --role-name ECSExecutionRole --assume-role-policy-document file://ecs-execution-trust-policy.json --region us-east-1")
    print()
    print("# 8. Criar policy para ECS Execution")
    print("aws iam create-policy --policy-name ECSExecutionPolicy --policy-document file://ecs-execution-policy.json --region us-east-1")
    
    print("\n🌐 ETAPA 5: CONFIGURAR ECS CLUSTER")
    print("-" * 60)
    print("Execute no terminal local:")
    print()
    print("# 1. Criar cluster ECS")
    print("aws ecs create-cluster --cluster-name marabet-ai-cluster --region us-east-1")
    print()
    print("# 2. Criar cluster ECS para staging")
    print("aws ecs create-cluster --cluster-name marabet-ai-staging-cluster --region us-east-1")
    print()
    print("# 3. Criar cluster ECS para desenvolvimento")
    print("aws ecs create-cluster --cluster-name marabet-ai-dev-cluster --region us-east-1")
    print()
    print("# 4. Criar task definition para produção")
    print("aws ecs register-task-definition --cli-input-json file://task-definition-production.json --region us-east-1")
    print()
    print("# 5. Criar task definition para staging")
    print("aws ecs register-task-definition --cli-input-json file://task-definition-staging.json --region us-east-1")
    print()
    print("# 6. Criar task definition para desenvolvimento")
    print("aws ecs register-task-definition --cli-input-json file://task-definition-dev.json --region us-east-1")
    print()
    print("# 7. Criar service ECS para produção")
    print("aws ecs create-service --cluster marabet-ai-cluster --service-name marabet-ai-service --task-definition marabet-ai:1 --desired-count 3 --region us-east-1")
    print()
    print("# 8. Criar service ECS para staging")
    print("aws ecs create-service --cluster marabet-ai-staging-cluster --service-name marabet-ai-staging-service --task-definition marabet-ai-staging:1 --desired-count 1 --region us-east-1")
    
    print("\n📊 ETAPA 6: CONFIGURAR MONITORAMENTO E ALERTAS")
    print("-" * 60)
    print("Execute no terminal local:")
    print()
    print("# 1. Criar dashboard de CI/CD")
    print("aws cloudwatch put-dashboard --dashboard-name MaraBet-CICD-Dashboard --dashboard-body file://cicd-dashboard.json --region us-east-1")
    print()
    print("# 2. Criar alarme de deploy falhado")
    print("aws cloudwatch put-metric-alarm --alarm-name marabet-deploy-failed --alarm-description \"Deploy Failed\" --metric-name DeployFailed --namespace AWS/ECS --statistic Sum --period 300 --threshold 1 --comparison-operator GreaterThanOrEqualToThreshold --region us-east-1")
    print()
    print("# 3. Criar alarme de build falhado")
    print("aws cloudwatch put-metric-alarm --alarm-name marabet-build-failed --alarm-description \"Build Failed\" --metric-name BuildFailed --namespace AWS/CodeBuild --statistic Sum --period 300 --threshold 1 --comparison-operator GreaterThanOrEqualToThreshold --region us-east-1")
    print()
    print("# 4. Criar alarme de teste falhado")
    print("aws cloudwatch put-metric-alarm --alarm-name marabet-test-failed --alarm-description \"Test Failed\" --metric-name TestFailed --namespace AWS/CodeBuild --statistic Sum --period 300 --threshold 1 --comparison-operator GreaterThanOrEqualToThreshold --region us-east-1")
    print()
    print("# 5. Criar alarme de security scan falhado")
    print("aws cloudwatch put-metric-alarm --alarm-name marabet-security-scan-failed --alarm-description \"Security Scan Failed\" --metric-name SecurityScanFailed --namespace AWS/CodeBuild --statistic Sum --period 300 --threshold 1 --comparison-operator GreaterThanOrEqualToThreshold --region us-east-1")
    print()
    print("# 6. Criar alarme de performance test falhado")
    print("aws cloudwatch put-metric-alarm --alarm-name marabet-performance-test-failed --alarm-description \"Performance Test Failed\" --metric-name PerformanceTestFailed --namespace AWS/CodeBuild --statistic Sum --period 300 --threshold 1 --comparison-operator GreaterThanOrEqualToThreshold --region us-east-1")
    print()
    print("# 7. Criar alarme de backup falhado")
    print("aws cloudwatch put-metric-alarm --alarm-name marabet-backup-failed --alarm-description \"Backup Failed\" --metric-name BackupFailed --namespace AWS/ECS --statistic Sum --period 300 --threshold 1 --comparison-operator GreaterThanOrEqualToThreshold --region us-east-1")
    print()
    print("# 8. Criar alarme de rollback")
    print("aws cloudwatch put-metric-alarm --alarm-name marabet-rollback --alarm-description \"Rollback Required\" --metric-name Rollback --namespace AWS/ECS --statistic Sum --period 300 --threshold 1 --comparison-operator GreaterThanOrEqualToThreshold --region us-east-1")
    
    print("\n🔔 ETAPA 7: CONFIGURAR NOTIFICAÇÕES")
    print("-" * 60)
    print("Execute no terminal local:")
    print()
    print("# 1. Criar SNS Topic para CI/CD")
    print("aws sns create-topic --name marabet-cicd-alerts --region us-east-1")
    print()
    print("# 2. Criar SNS Topic para deploy")
    print("aws sns create-topic --name marabet-deploy-alerts --region us-east-1")
    print()
    print("# 3. Criar SNS Topic para build")
    print("aws sns create-topic --name marabet-build-alerts --region us-east-1")
    print()
    print("# 4. Criar SNS Topic para testes")
    print("aws sns create-topic --name marabet-test-alerts --region us-east-1")
    print()
    print("# 5. Criar SNS Topic para security")
    print("aws sns create-topic --name marabet-security-alerts --region us-east-1")
    print()
    print("# 6. Criar SNS Topic para performance")
    print("aws sns create-topic --name marabet-performance-alerts --region us-east-1")
    print()
    print("# 7. Criar SNS Topic para backup")
    print("aws sns create-topic --name marabet-backup-alerts --region us-east-1")
    print()
    print("# 8. Criar SNS Topic para rollback")
    print("aws sns create-topic --name marabet-rollback-alerts --region us-east-1")
    
    print("\n🎯 COMANDOS DE VERIFICAÇÃO DE CI/CD:")
    print("-" * 60)
    print("Execute no terminal local:")
    print()
    print("# Verificar repositórios ECR")
    print("aws ecr describe-repositories --region us-east-1")
    print()
    print("# Verificar roles IAM")
    print("aws iam list-roles --query 'Roles[?contains(RoleName, `GitHub`) || contains(RoleName, `ECS`)]'")
    print()
    print("# Verificar clusters ECS")
    print("aws ecs describe-clusters --region us-east-1")
    print()
    print("# Verificar task definitions")
    print("aws ecs list-task-definitions --region us-east-1")
    print()
    print("# Verificar services ECS")
    print("aws ecs list-services --cluster marabet-ai-cluster --region us-east-1")
    print()
    print("# Verificar dashboards")
    print("aws cloudwatch list-dashboards --region us-east-1")
    print()
    print("# Verificar alarmes")
    print("aws cloudwatch describe-alarms --region us-east-1")
    print()
    print("# Verificar SNS Topics")
    print("aws sns list-topics --region us-east-1")
    
    print("\n🚀 COMANDOS DE IMPLEMENTAÇÃO RÁPIDA:")
    print("-" * 60)
    print("Execute no terminal local:")
    print()
    print("# Implementar ECR")
    print("aws ecr create-repository --repository-name marabet-ai --region us-east-1 && aws ecr create-repository --repository-name marabet-ai-staging --region us-east-1 && aws ecr create-repository --repository-name marabet-ai-dev --region us-east-1")
    print()
    print("# Implementar IAM Roles")
    print("aws iam create-role --role-name GitHubActionsRole --assume-role-policy-document file://github-actions-trust-policy.json --region us-east-1 && aws iam create-policy --policy-name GitHubActionsPolicy --policy-document file://github-actions-policy.json --region us-east-1")
    print()
    print("# Implementar ECS Cluster")
    print("aws ecs create-cluster --cluster-name marabet-ai-cluster --region us-east-1 && aws ecs create-cluster --cluster-name marabet-ai-staging-cluster --region us-east-1 && aws ecs create-cluster --cluster-name marabet-ai-dev-cluster --region us-east-1")
    print()
    print("# Implementar Task Definitions")
    print("aws ecs register-task-definition --cli-input-json file://task-definition-production.json --region us-east-1 && aws ecs register-task-definition --cli-input-json file://task-definition-staging.json --region us-east-1")
    print()
    print("# Implementar Services")
    print("aws ecs create-service --cluster marabet-ai-cluster --service-name marabet-ai-service --task-definition marabet-ai:1 --desired-count 3 --region us-east-1 && aws ecs create-service --cluster marabet-ai-staging-cluster --service-name marabet-ai-staging-service --task-definition marabet-ai-staging:1 --desired-count 1 --region us-east-1")
    print()
    print("# Implementar Monitoramento")
    print("aws cloudwatch put-dashboard --dashboard-name MaraBet-CICD-Dashboard --dashboard-body file://cicd-dashboard.json --region us-east-1 && aws cloudwatch put-metric-alarm --alarm-name marabet-deploy-failed --alarm-description \"Deploy Failed\" --metric-name DeployFailed --namespace AWS/ECS --statistic Sum --period 300 --threshold 1 --comparison-operator GreaterThanOrEqualToThreshold --region us-east-1")
    print()
    print("# Implementar Notificações")
    print("aws sns create-topic --name marabet-cicd-alerts --region us-east-1 && aws sns create-topic --name marabet-deploy-alerts --region us-east-1 && aws sns create-topic --name marabet-build-alerts --region us-east-1")
    print()
    print("# Implementar CI/CD Completo")
    print("mkdir -p .github/workflows && touch .github/workflows/deploy-production.yml && touch .github/workflows/deploy-staging.yml && touch .github/workflows/test.yml && touch .github/workflows/build.yml && touch .github/workflows/security-scan.yml && touch .github/workflows/performance-test.yml && touch .github/workflows/backup.yml")
    
    print("\n🎉 CONFIGURAÇÃO DE CI/CD COM GITHUB ACTIONS CONSOLIDADA COM SUCESSO!")
    print("=" * 80)
    
    return True

def main():
    print("🚀 Iniciando configuração de CI/CD com GitHub Actions...")
    
    # Criar configuração de CI/CD
    success = create_cicd_configuration()
    
    if success:
        print("\n🎯 CONFIGURAÇÃO DE CI/CD COM GITHUB ACTIONS CONSOLIDADA COM SUCESSO!")
        print("Sistema completo e funcionando!")
    else:
        print("\n❌ Falha na configuração de CI/CD")
        print("Verifique os logs acima para mais detalhes")

if __name__ == "__main__":
    main()
