#!/usr/bin/env python3
"""
Script de Diagnóstico de Banco de Dados - MaraBet AI
Diagnostica e resolve problemas de conexão com RDS PostgreSQL e Redis
"""

import subprocess
import json
import os
from datetime import datetime

def run_aws_command(command, return_text=False):
    """Executa comando AWS CLI e retorna resultado"""
    try:
        result = subprocess.run(command, shell=True, capture_output=True, text=True)
        if result.returncode == 0:
            if return_text:
                return result.stdout.strip()
            else:
                return json.loads(result.stdout) if result.stdout.strip() else {}
        else:
            print(f"❌ Erro no comando: {command}")
            print(f"Erro: {result.stderr}")
            return None
    except json.JSONDecodeError:
        print(f"❌ Erro de decodificação JSON para o comando: {command}")
        print(f"Saída: {result.stdout}")
        print(f"Erro: {result.stderr}")
        return None
    except Exception as e:
        print(f"❌ Exceção no comando: {command}")
        print(f"Erro: {e}")
        return None

def load_config():
    """Carrega configurações existentes do arquivo JSON."""
    config_file = 'aws_infrastructure_config.json'
    if os.path.exists(config_file):
        with open(config_file, 'r') as f:
            return json.load(f)
    return {}

def save_config(config):
    """Salva configurações no arquivo JSON."""
    config_file = 'aws_infrastructure_config.json'
    with open(config_file, 'w') as f:
        json.dump(config, f, indent=2)

def create_database_diagnosis():
    """Cria guia de diagnóstico de banco de dados"""
    print("🗄️ MARABET AI - DIAGNÓSTICO DE BANCO DE DADOS")
    print("=" * 80)
    print(f"📅 Data/Hora: {datetime.now().strftime('%d/%m/%Y %H:%M:%S')}")
    
    # Carregar configuração existente
    config = load_config()
    
    print("\n🔍 DIAGNÓSTICO INICIAL - VERIFICAÇÕES BÁSICAS:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Verificar status do RDS")
    print("aws rds describe-db-instances --db-instance-identifier marabet-db")
    print()
    print("# 2. Verificar status do Redis")
    print("aws elasticache describe-cache-clusters --cache-cluster-id marabet-redis")
    print()
    print("# 3. Verificar security groups")
    print("aws ec2 describe-security-groups --group-ids sg-0510c72d32779d3fa")
    print("aws ec2 describe-security-groups --group-ids sg-0cb8519ebb24a65e9")
    print()
    print("# 4. Verificar conectividade de rede")
    print("ping marabet-db.cmvmwskgiabr.us-east-1.rds.amazonaws.com")
    print("ping marabet-redis.ve5qk7.0001.use1.cache.amazonaws.com")
    print()
    print("# 5. Verificar resolução DNS")
    print("nslookup marabet-db.cmvmwskgiabr.us-east-1.rds.amazonaws.com")
    print("nslookup marabet-redis.ve5qk7.0001.use1.cache.amazonaws.com")
    
    print("\n🗄️ VERIFICAÇÃO DE RDS POSTGRESQL:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Testar conectividade de rede")
    print("telnet marabet-db.cmvmwskgiabr.us-east-1.rds.amazonaws.com 5432")
    print()
    print("# 2. Testar conexão PostgreSQL")
    print("PGPASSWORD=\"MaraBet2024!SuperSecret\" psql -h marabet-db.cmvmwskgiabr.us-east-1.rds.amazonaws.com -U marabetadmin -d postgres -c \"SELECT version();\"")
    print()
    print("# 3. Testar conexão com database específico")
    print("PGPASSWORD=\"MaraBet2024!SuperSecret\" psql -h marabet-db.cmvmwskgiabr.us-east-1.rds.amazonaws.com -U marabetadmin -d marabet -c \"SELECT current_database();\"")
    print()
    print("# 4. Verificar tabelas existentes")
    print("PGPASSWORD=\"MaraBet2024!SuperSecret\" psql -h marabet-db.cmvmwskgiabr.us-east-1.rds.amazonaws.com -U marabetadmin -d marabet -c \"\\dt\"")
    print()
    print("# 5. Verificar conexões ativas")
    print("PGPASSWORD=\"MaraBet2024!SuperSecret\" psql -h marabet-db.cmvmwskgiabr.us-east-1.rds.amazonaws.com -U marabetadmin -d postgres -c \"SELECT * FROM pg_stat_activity;\"")
    print()
    print("# 6. Verificar configurações do banco")
    print("PGPASSWORD=\"MaraBet2024!SuperSecret\" psql -h marabet-db.cmvmwskgiabr.us-east-1.rds.amazonaws.com -U marabetadmin -d postgres -c \"SHOW ALL;\"")
    print()
    print("# 7. Verificar logs do RDS")
    print("aws rds describe-db-log-files --db-instance-identifier marabet-db")
    print()
    print("# 8. Verificar métricas do RDS")
    print("aws cloudwatch get-metric-statistics --namespace AWS/RDS --metric-name DatabaseConnections --dimensions Name=DBInstanceIdentifier,Value=marabet-db --start-time 2024-01-01T00:00:00Z --end-time 2024-01-02T00:00:00Z --period 3600 --statistics Average")
    
    print("\n🔴 VERIFICAÇÃO DE REDIS:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Testar conectividade de rede")
    print("telnet marabet-redis.ve5qk7.0001.use1.cache.amazonaws.com 6379")
    print()
    print("# 2. Testar conexão Redis")
    print("redis-cli -h marabet-redis.ve5qk7.0001.use1.cache.amazonaws.com ping")
    print()
    print("# 3. Testar operações básicas")
    print("redis-cli -h marabet-redis.ve5qk7.0001.use1.cache.amazonaws.com set test_key \"test_value\"")
    print("redis-cli -h marabet-redis.ve5qk7.0001.use1.cache.amazonaws.com get test_key")
    print("redis-cli -h marabet-redis.ve5qk7.0001.use1.cache.amazonaws.com del test_key")
    print()
    print("# 4. Verificar informações do Redis")
    print("redis-cli -h marabet-redis.ve5qk7.0001.use1.cache.amazonaws.com info")
    print()
    print("# 5. Verificar chaves existentes")
    print("redis-cli -h marabet-redis.ve5qk7.0001.use1.cache.amazonaws.com keys \"*\"")
    print()
    print("# 6. Verificar configurações do Redis")
    print("redis-cli -h marabet-redis.ve5qk7.0001.use1.cache.amazonaws.com config get \"*\"")
    print()
    print("# 7. Verificar logs do Redis")
    print("aws elasticache describe-cache-clusters --cache-cluster-id marabet-redis --show-cache-node-info")
    print()
    print("# 8. Verificar métricas do Redis")
    print("aws cloudwatch get-metric-statistics --namespace AWS/ElastiCache --metric-name CurrConnections --dimensions Name=CacheClusterId,Value=marabet-redis --start-time 2024-01-01T00:00:00Z --end-time 2024-01-02T00:00:00Z --period 3600 --statistics Average")
    
    print("\n🔧 VERIFICAÇÃO DE SECURITY GROUPS:")
    print("-" * 60)
    print("Execute no terminal local:")
    print()
    print("# 1. Verificar security group do RDS")
    print("aws ec2 describe-security-groups --group-ids sg-0510c72d32779d3fa")
    print()
    print("# 2. Verificar security group do Redis")
    print("aws ec2 describe-security-groups --group-ids sg-0cb8519ebb24a65e9")
    print()
    print("# 3. Verificar security group do EC2")
    print("aws ec2 describe-security-groups --group-ids sg-07f7e19db4e1e8f78")
    print()
    print("# 4. Adicionar regra para RDS (se necessário)")
    print("aws ec2 authorize-security-group-ingress --group-id sg-0510c72d32779d3fa --protocol tcp --port 5432 --source-group sg-07f7e19db4e1e8f78")
    print()
    print("# 5. Adicionar regra para Redis (se necessário)")
    print("aws ec2 authorize-security-group-ingress --group-id sg-0cb8519ebb24a65e9 --protocol tcp --port 6379 --source-group sg-07f7e19db4e1e8f78")
    print()
    print("# 6. Verificar regras de saída do EC2")
    print("aws ec2 describe-security-groups --group-ids sg-07f7e19db4e1e8f78 --query 'SecurityGroups[0].IpPermissionsEgress'")
    print()
    print("# 7. Adicionar regra de saída para RDS (se necessário)")
    print("aws ec2 authorize-security-group-egress --group-id sg-07f7e19db4e1e8f78 --protocol tcp --port 5432 --cidr 0.0.0.0/0")
    print()
    print("# 8. Adicionar regra de saída para Redis (se necessário)")
    print("aws ec2 authorize-security-group-egress --group-id sg-07f7e19db4e1e8f78 --protocol tcp --port 6379 --cidr 0.0.0.0/0")
    
    print("\n🌐 VERIFICAÇÃO DE CONECTIVIDADE DE REDE:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Verificar rota para RDS")
    print("traceroute marabet-db.cmvmwskgiabr.us-east-1.rds.amazonaws.com")
    print()
    print("# 2. Verificar rota para Redis")
    print("traceroute marabet-redis.ve5qk7.0001.use1.cache.amazonaws.com")
    print()
    print("# 3. Verificar conectividade TCP")
    print("nc -zv marabet-db.cmvmwskgiabr.us-east-1.rds.amazonaws.com 5432")
    print("nc -zv marabet-redis.ve5qk7.0001.use1.cache.amazonaws.com 6379")
    print()
    print("# 4. Verificar conectividade UDP")
    print("nc -zuv marabet-db.cmvmwskgiabr.us-east-1.rds.amazonaws.com 5432")
    print("nc -zuv marabet-redis.ve5qk7.0001.use1.cache.amazonaws.com 6379")
    print()
    print("# 5. Verificar firewall local")
    print("sudo ufw status")
    print("sudo iptables -L")
    print()
    print("# 6. Verificar configuração de rede")
    print("ip route show")
    print("ip addr show")
    print()
    print("# 7. Verificar DNS")
    print("cat /etc/resolv.conf")
    print("systemd-resolve --status")
    print()
    print("# 8. Verificar conectividade geral")
    print("ping google.com")
    print("ping 8.8.8.8")
    
    print("\n🔍 VERIFICAÇÃO DE CONFIGURAÇÃO DA APLICAÇÃO:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Verificar variáveis de ambiente")
    print("docker-compose -f docker-compose.production.yml exec web env | grep -E '(DATABASE|REDIS)'")
    print()
    print("# 2. Verificar arquivo .env")
    print("cat .env.production | grep -E '(DATABASE|REDIS)'")
    print()
    print("# 3. Verificar configuração do Docker Compose")
    print("docker-compose -f docker-compose.production.yml config | grep -A 10 -B 10 -E '(DATABASE|REDIS)'")
    print()
    print("# 4. Verificar logs da aplicação")
    print("docker-compose -f docker-compose.production.yml logs web | grep -i -E '(database|redis|connection|error)'")
    print()
    print("# 5. Verificar conectividade interna do container")
    print("docker-compose -f docker-compose.production.yml exec web ping marabet-db.cmvmwskgiabr.us-east-1.rds.amazonaws.com")
    print("docker-compose -f docker-compose.production.yml exec web ping marabet-redis.ve5qk7.0001.use1.cache.amazonaws.com")
    print()
    print("# 6. Verificar conectividade de porta do container")
    print("docker-compose -f docker-compose.production.yml exec web nc -zv marabet-db.cmvmwskgiabr.us-east-1.rds.amazonaws.com 5432")
    print("docker-compose -f docker-compose.production.yml exec web nc -zv marabet-redis.ve5qk7.0001.use1.cache.amazonaws.com 6379")
    print()
    print("# 7. Verificar configuração de rede do container")
    print("docker-compose -f docker-compose.production.yml exec web ip route show")
    print("docker-compose -f docker-compose.production.yml exec web cat /etc/resolv.conf")
    print()
    print("# 8. Verificar logs do sistema")
    print("sudo journalctl -u docker | grep -i -E '(database|redis|connection|error)'")
    
    print("\n🚨 SOLUÇÕES COMUNS - CORREÇÕES RÁPIDAS:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Reiniciar containers")
    print("docker-compose -f docker-compose.production.yml restart")
    print()
    print("# 2. Reiniciar serviços de rede")
    print("sudo systemctl restart networking")
    print("sudo systemctl restart systemd-resolved")
    print()
    print("# 3. Limpar cache DNS")
    print("sudo systemctl flush-dns")
    print("sudo systemd-resolve --flush-caches")
    print()
    print("# 4. Verificar e corrigir permissões")
    print("sudo chown -R ubuntu:ubuntu /home/ubuntu/marabet-ai/")
    print("chmod +x /home/ubuntu/marabet-ai/*.sh")
    print()
    print("# 5. Verificar e corrigir variáveis de ambiente")
    print("cp .env.production .env")
    print()
    print("# 6. Verificar e corrigir configuração do Docker")
    print("sudo systemctl restart docker")
    print()
    print("# 7. Verificar e corrigir configuração do sistema")
    print("sudo apt update && sudo apt upgrade -y")
    print()
    print("# 8. Verificar e corrigir configuração de rede")
    print("sudo ufw allow 5432")
    print("sudo ufw allow 6379")
    
    print("\n🔧 SOLUÇÕES AVANÇADAS - CORREÇÕES DETALHADAS:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Verificar e corrigir problemas de memória")
    print("free -h")
    print("sudo swapoff -a && sudo swapon -a")
    print()
    print("# 2. Verificar e corrigir problemas de disco")
    print("df -h")
    print("sudo du -sh /var/lib/docker/*")
    print("docker system prune -a -f")
    print()
    print("# 3. Verificar e corrigir problemas de rede")
    print("sudo systemctl restart networking")
    print("sudo systemctl restart systemd-resolved")
    print()
    print("# 4. Verificar e corrigir problemas de DNS")
    print("nslookup marabet-db.cmvmwskgiabr.us-east-1.rds.amazonaws.com")
    print("echo 'nameserver 8.8.8.8' | sudo tee -a /etc/resolv.conf")
    print()
    print("# 5. Verificar e corrigir problemas de firewall")
    print("sudo ufw status")
    print("sudo ufw allow 5432")
    print("sudo ufw allow 6379")
    print()
    print("# 6. Verificar e corrigir problemas de SSL")
    print("sudo certbot certificates")
    print("sudo certbot renew")
    print("sudo systemctl reload nginx")
    print()
    print("# 7. Verificar e corrigir problemas de backup")
    print("sudo /home/ubuntu/backup.sh")
    print()
    print("# 8. Verificar e corrigir problemas de monitoramento")
    print("sudo /home/ubuntu/marabet-ai/monitoring_script.sh")
    
    print("\n🎯 COMANDOS DE DIAGNÓSTICO RÁPIDO:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Diagnóstico completo de banco de dados")
    print("aws rds describe-db-instances --db-instance-identifier marabet-db && aws elasticache describe-cache-clusters --cache-cluster-id marabet-redis")
    print()
    print("# Teste de conectividade completo")
    print("telnet marabet-db.cmvmwskgiabr.us-east-1.rds.amazonaws.com 5432 && telnet marabet-redis.ve5qk7.0001.use1.cache.amazonaws.com 6379")
    print()
    print("# Teste de conexão completo")
    print("PGPASSWORD=\"MaraBet2024!SuperSecret\" psql -h marabet-db.cmvmwskgiabr.us-east-1.rds.amazonaws.com -U marabetadmin -d postgres -c \"SELECT version();\" && redis-cli -h marabet-redis.ve5qk7.0001.use1.cache.amazonaws.com ping")
    print()
    print("# Verificação de security groups completa")
    print("aws ec2 describe-security-groups --group-ids sg-0510c72d32779d3fa && aws ec2 describe-security-groups --group-ids sg-0cb8519ebb24a65e9")
    print()
    print("# Verificação de rede completa")
    print("ping marabet-db.cmvmwskgiabr.us-east-1.rds.amazonaws.com && ping marabet-redis.ve5qk7.0001.use1.cache.amazonaws.com")
    print()
    print("# Verificação de logs completa")
    print("docker-compose -f docker-compose.production.yml logs web | grep -i -E '(database|redis|connection|error)'")
    print()
    print("# Verificação de configuração completa")
    print("docker-compose -f docker-compose.production.yml config | grep -E '(DATABASE|REDIS)'")
    print()
    print("# Verificação de conectividade interna completa")
    print("docker-compose -f docker-compose.production.yml exec web nc -zv marabet-db.cmvmwskgiabr.us-east-1.rds.amazonaws.com 5432 && docker-compose -f docker-compose.production.yml exec web nc -zv marabet-redis.ve5qk7.0001.use1.cache.amazonaws.com 6379")
    
    print("\n🚀 COMANDOS DE RECUPERAÇÃO RÁPIDA:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Parar e limpar containers")
    print("docker-compose -f docker-compose.production.yml down && docker system prune -a -f")
    print()
    print("# Rebuild e restart")
    print("docker-compose -f docker-compose.production.yml up -d --build")
    print()
    print("# Reiniciar serviços")
    print("sudo systemctl restart nginx && sudo systemctl restart docker")
    print()
    print("# Verificar status")
    print("docker-compose -f docker-compose.production.yml ps && sudo systemctl status nginx")
    print()
    print("# Testar conectividade")
    print("telnet marabet-db.cmvmwskgiabr.us-east-1.rds.amazonaws.com 5432 && telnet marabet-redis.ve5qk7.0001.use1.cache.amazonaws.com 6379")
    print()
    print("# Testar aplicação")
    print("curl -I http://localhost:8000/health && curl -I https://marabet.com/health")
    print()
    print("# Ver logs")
    print("docker-compose -f docker-compose.production.yml logs -f")
    
    print("\n🎉 GUIA DE DIAGNÓSTICO DE BANCO DE DADOS CONSOLIDADO COM SUCESSO!")
    print("=" * 80)
    
    return True

def main():
    print("🚀 Iniciando consolidação do guia de diagnóstico de banco de dados...")
    
    # Criar guia de diagnóstico
    success = create_database_diagnosis()
    
    if success:
        print("\n🎯 GUIA DE DIAGNÓSTICO DE BANCO DE DADOS CONSOLIDADO COM SUCESSO!")
        print("Sistema completo e funcionando!")
    else:
        print("\n❌ Falha na consolidação do guia de diagnóstico")
        print("Verifique os logs acima para mais detalhes")

if __name__ == "__main__":
    main()
