#!/usr/bin/env python3
"""
Script para Instruções de Configuração do Banco de Dados - MaraBet AI
Mostra instruções detalhadas para configurar o banco de dados manualmente
"""

import json
from datetime import datetime

def show_database_config_instructions():
    """Mostra instruções detalhadas para configuração do banco de dados"""
    
    print("\n" + "="*80)
    print("🗄️ MARABET AI - INSTRUÇÕES DE CONFIGURAÇÃO DO BANCO DE DADOS")
    print("="*80)
    
    print(f"\n📅 Data/Hora: {datetime.now().strftime('%d/%m/%Y %H:%M:%S')}")
    
    # Carregar configuração existente
    try:
        with open('aws_infrastructure_config.json', 'r') as f:
            config = json.load(f)
    except FileNotFoundError:
        print("❌ Arquivo de configuração não encontrado")
        return False
    
    ubuntu_public_ip = config.get('ubuntu_public_ip')
    rds_endpoint = config.get('rds_endpoint')
    redis_endpoint = config.get('redis_endpoint')
    
    if not all([ubuntu_public_ip, rds_endpoint, redis_endpoint]):
        print("❌ Endpoints do RDS ou Redis não encontrados na configuração")
        return False
    
    print(f"\n📋 INFORMAÇÕES DOS SERVIÇOS:")
    print("-" * 60)
    print(f"• IP Público: {ubuntu_public_ip}")
    print(f"• RDS Endpoint: {rds_endpoint}")
    print(f"• Redis Endpoint: {redis_endpoint}")
    print(f"• Banco: PostgreSQL")
    print(f"• Cache: Redis")
    
    print(f"\n🔑 ETAPA 1: CONFIGURAR CHAVE SSH")
    print("-" * 60)
    print("1. Baixar a chave SSH da AWS:")
    print("   aws ec2 create-key-pair --key-name marabet-key-new --query 'KeyMaterial' --output text > ~/.ssh/marabet-key.pem")
    print()
    print("2. Configurar permissões (Windows):")
    print("   icacls C:\\Users\\%USERNAME%\\.ssh\\marabet-key.pem /inheritance:r")
    print("   icacls C:\\Users\\%USERNAME%\\.ssh\\marabet-key.pem /grant:r \"%USERNAME%:R\"")
    print()
    print("3. Configurar permissões (Linux/Mac):")
    print("   chmod 600 ~/.ssh/marabet-key.pem")
    
    print(f"\n🔗 ETAPA 2: CONECTAR VIA SSH")
    print("-" * 60)
    print("Comando para conectar:")
    print(f"ssh -i ~/.ssh/marabet-key.pem ubuntu@{ubuntu_public_ip}")
    print()
    print("Comando PowerShell:")
    print(f'$PUBLIC_IP = "{ubuntu_public_ip}"')
    print('ssh -i ~/.ssh/marabet-key.pem ubuntu@$PUBLIC_IP')
    
    print(f"\n🐳 ETAPA 3: VERIFICAR CONTAINERS")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Ir para pasta do projeto")
    print("cd /home/ubuntu/marabet-ai")
    print()
    print("# 2. Verificar status dos containers")
    print("docker-compose -f docker-compose.production.yml ps")
    print()
    print("# 3. Ver logs da aplicação")
    print("docker-compose -f docker-compose.production.yml logs --tail=20")
    print()
    print("# 4. Verificar se container web está rodando")
    print("docker ps | grep web")
    
    print(f"\n🗄️ ETAPA 4: CONFIGURAR BANCO DE DADOS")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Entrar no container web")
    print("docker-compose -f docker-compose.production.yml exec web bash")
    print()
    print("# 2. Verificar variáveis de ambiente")
    print("echo $DATABASE_URL")
    print("echo $REDIS_URL")
    print()
    print("# 3. Instalar dependências do banco")
    print("pip install psycopg2-binary redis sqlalchemy alembic")
    print()
    print("# 4. Testar conexão com RDS")
    print("python -c \"import psycopg2; conn = psycopg2.connect('$DATABASE_URL'); print('RDS OK'); conn.close()\"")
    print()
    print("# 5. Testar conexão com Redis")
    print("python -c \"import redis; r = redis.from_url('$REDIS_URL'); print('Redis OK:', r.ping())\"")
    
    print(f"\n🏗️ ETAPA 5: CRIAR TABELAS DO BANCO")
    print("-" * 60)
    print("Execute dentro do container web:")
    print()
    print("# 1. Criar script de inicialização")
    print("cat > init_db.py << 'EOF'")
    print("import os")
    print("import psycopg2")
    print("from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT")
    print("")
    print("def init_database():")
    print("    try:")
    print("        # Conectar ao banco")
    print("        conn = psycopg2.connect(os.getenv('DATABASE_URL'))")
    print("        conn.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)")
    print("        cur = conn.cursor()")
    print("        ")
    print("        # Criar tabelas")
    print("        print('Criando tabelas...')")
    print("        ")
    print("        # Tabela de partidas")
    print("        cur.execute('''")
    print("        CREATE TABLE IF NOT EXISTS matches (")
    print("            id SERIAL PRIMARY KEY,")
    print("            home_team VARCHAR(255) NOT NULL,")
    print("            away_team VARCHAR(255) NOT NULL,")
    print("            league VARCHAR(255),")
    print("            match_date TIMESTAMP,")
    print("            status VARCHAR(50),")
    print("            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,")
    print("            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
    print("        );")
    print("        ''')")
    print("        ")
    print("        # Tabela de odds")
    print("        cur.execute('''")
    print("        CREATE TABLE IF NOT EXISTS odds (")
    print("            id SERIAL PRIMARY KEY,")
    print("            match_id INTEGER REFERENCES matches(id),")
    print("            market_type VARCHAR(100),")
    print("            selection VARCHAR(100),")
    print("            odds_value DECIMAL(10,2),")
    print("            bookmaker VARCHAR(100),")
    print("            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,")
    print("            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
    print("        );")
    print("        ''')")
    print("        ")
    print("        # Tabela de predições")
    print("        cur.execute('''")
    print("        CREATE TABLE IF NOT EXISTS predictions (")
    print("            id SERIAL PRIMARY KEY,")
    print("            match_id INTEGER REFERENCES matches(id),")
    print("            prediction_type VARCHAR(100),")
    print("            prediction_data JSONB,")
    print("            confidence DECIMAL(5,2),")
    print("            expected_value DECIMAL(10,4),")
    print("            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,")
    print("            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
    print("        );")
    print("        ''')")
    print("        ")
    print("        # Tabela de estatísticas")
    print("        cur.execute('''")
    print("        CREATE TABLE IF NOT EXISTS team_stats (")
    print("            id SERIAL PRIMARY KEY,")
    print("            team_name VARCHAR(255) NOT NULL,")
    print("            league VARCHAR(255),")
    print("            season VARCHAR(20),")
    print("            matches_played INTEGER DEFAULT 0,")
    print("            wins INTEGER DEFAULT 0,")
    print("            draws INTEGER DEFAULT 0,")
    print("            losses INTEGER DEFAULT 0,")
    print("            goals_for INTEGER DEFAULT 0,")
    print("            goals_against INTEGER DEFAULT 0,")
    print("            points INTEGER DEFAULT 0,")
    print("            form VARCHAR(20),")
    print("            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,")
    print("            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
    print("        );")
    print("        ''')")
    print("        ")
    print("        # Tabela de configurações")
    print("        cur.execute('''")
    print("        CREATE TABLE IF NOT EXISTS app_config (")
    print("            id SERIAL PRIMARY KEY,")
    print("            config_key VARCHAR(255) UNIQUE NOT NULL,")
    print("            config_value TEXT,")
    print("            description TEXT,")
    print("            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,")
    print("            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
    print("        );")
    print("        ''')")
    print("        ")
    print("        print('Tabelas criadas com sucesso!')")
    print("        ")
    print("        # Inserir configurações iniciais")
    print("        cur.execute('''")
    print("        INSERT INTO app_config (config_key, config_value, description) VALUES")
    print("        ('app_name', 'MaraBet AI', 'Nome da aplicação'),")
    print("        ('app_version', '1.0.0', 'Versão da aplicação'),")
    print("        ('environment', 'production', 'Ambiente de execução')")
    print("        ON CONFLICT (config_key) DO NOTHING;")
    print("        ''')")
    print("        ")
    print("        print('Configurações inseridas!')")
    print("        ")
    print("        # Verificar tabelas")
    print("        cur.execute('''")
    print("        SELECT table_name FROM information_schema.tables")
    print("        WHERE table_schema = 'public' ORDER BY table_name;")
    print("        ''')")
    print("        tables = cur.fetchall()")
    print("        print('Tabelas encontradas:')")
    print("        for table in tables:")
    print("            print(f'  • {table[0]}')")
    print("        ")
    print("        cur.close()")
    print("        conn.close()")
    print("        print('Banco configurado com sucesso!')")
    print("        return True")
    print("        ")
    print("    except Exception as e:")
    print("        print(f'Erro: {e}')")
    print("        return False")
    print("")
    print("if __name__ == '__main__':")
    print("    init_database()")
    print("EOF")
    print()
    print("# 2. Executar script de inicialização")
    print("python init_db.py")
    print()
    print("# 3. Verificar tabelas criadas")
    print("python -c \"import psycopg2; conn = psycopg2.connect('$DATABASE_URL'); cur = conn.cursor(); cur.execute('SELECT table_name FROM information_schema.tables WHERE table_schema = \\'public\\' ORDER BY table_name;'); print('Tabelas:', [row[0] for row in cur.fetchall()]); conn.close()\"")
    print()
    print("# 4. Sair do container")
    print("exit")
    
    print(f"\n🔍 ETAPA 6: VERIFICAR CONFIGURAÇÃO")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Verificar status dos containers")
    print("docker-compose -f docker-compose.production.yml ps")
    print()
    print("# 2. Ver logs da aplicação")
    print("docker-compose -f docker-compose.production.yml logs --tail=20")
    print()
    print("# 3. Testar endpoint de health")
    print("curl http://localhost:8000/health")
    print()
    print("# 4. Testar endpoint de configuração")
    print("curl http://localhost:8000/config")
    print()
    print("# 5. Testar endpoint de predições")
    print("curl http://localhost:8000/predictions")
    
    print(f"\n🧪 ETAPA 7: TESTAR CONECTIVIDADE")
    print("-" * 60)
    print("Execute no Windows (PowerShell):")
    print()
    print("# 1. Testar conectividade")
    print(f"curl http://{ubuntu_public_ip}:8000/health")
    print()
    print("# 2. Testar API docs")
    print(f"curl http://{ubuntu_public_ip}:8000/docs")
    print()
    print("# 3. Testar endpoint de predições")
    print(f"curl http://{ubuntu_public_ip}:8000/predictions")
    print()
    print("# 4. Testar endpoint de análise")
    print(f"curl http://{ubuntu_public_ip}:8000/analysis")
    
    print(f"\n💡 COMANDOS ÚTEIS")
    print("-" * 60)
    print("# Conectar via SSH")
    print(f"ssh -i ~/.ssh/marabet-key.pem ubuntu@{ubuntu_public_ip}")
    print()
    print("# Entrar no container")
    print("cd /home/ubuntu/marabet-ai")
    print("docker-compose -f docker-compose.production.yml exec web bash")
    print()
    print("# Ver logs da aplicação")
    print("docker-compose -f docker-compose.production.yml logs -f")
    print()
    print("# Reiniciar aplicação")
    print("docker-compose -f docker-compose.production.yml restart")
    print()
    print("# Ver status dos containers")
    print("docker ps")
    print()
    print("# Ver uso de recursos")
    print("htop")
    print()
    print("# Ver espaço em disco")
    print("df -h")
    
    print(f"\n🌐 ACESSAR APLICAÇÃO")
    print("-" * 60)
    print(f"• URL Principal: http://{ubuntu_public_ip}:8000")
    print(f"• API Documentation: http://{ubuntu_public_ip}:8000/docs")
    print(f"• Health Check: http://{ubuntu_public_ip}:8000/health")
    print(f"• Predictions: http://{ubuntu_public_ip}:8000/predictions")
    print(f"• Analysis: http://{ubuntu_public_ip}:8000/analysis")
    print(f"• Configuration: http://{ubuntu_public_ip}:8000/config")
    
    print(f"\n🎯 RESUMO DA CONFIGURAÇÃO")
    print("-" * 60)
    print("✅ Instância Ubuntu criada e configurada")
    print("✅ Docker e Docker Compose instalados")
    print("✅ RDS PostgreSQL configurado")
    print("✅ Redis configurado")
    print("✅ Aplicação MaraBet AI pronta para configuração do banco")
    print("✅ Instruções detalhadas fornecidas")
    
    print(f"\n🔗 PRÓXIMOS PASSOS")
    print("-" * 60)
    print("1. ✅ Configurar chave SSH")
    print("2. ✅ Conectar via SSH")
    print("3. ✅ Verificar containers")
    print("4. ✅ Configurar banco de dados")
    print("5. ✅ Criar tabelas")
    print("6. ✅ Verificar configuração")
    print("7. ✅ Testar conectividade")
    print("8. ✅ Testar aplicação")
    
    print("\n" + "="*80)
    print("🗄️ MARABET AI - INSTRUÇÕES DE CONFIGURAÇÃO DO BANCO DE DADOS")
    print("="*80)
    
    return True

def main():
    print("🚀 Iniciando instruções de configuração do banco de dados...")
    
    # Mostrar instruções
    success = show_database_config_instructions()
    
    if success:
        print("\n🎯 INSTRUÇÕES DE CONFIGURAÇÃO DO BANCO PRONTAS!")
        print("Siga as instruções acima para configurar o banco de dados!")
    else:
        print("\n❌ Falha ao carregar configurações")
        print("Verifique se o arquivo aws_infrastructure_config.json existe")

if __name__ == "__main__":
    main()
