#!/usr/bin/env python3
"""
Script para Instruções de Deploy Manual - MaraBet AI
Mostra instruções detalhadas para fazer deploy manual da aplicação
"""

import json
from datetime import datetime

def show_deploy_instructions():
    """Mostra instruções detalhadas para deploy manual"""
    
    print("\n" + "="*80)
    print("🚀 MARABET AI - INSTRUÇÕES DE DEPLOY MANUAL")
    print("="*80)
    
    print(f"\n📅 Data/Hora: {datetime.now().strftime('%d/%m/%Y %H:%M:%S')}")
    
    # Carregar configuração existente
    try:
        with open('aws_infrastructure_config.json', 'r') as f:
            config = json.load(f)
    except FileNotFoundError:
        print("❌ Arquivo de configuração não encontrado")
        return False
    
    ubuntu_public_ip = config.get('ubuntu_public_ip')
    
    if not ubuntu_public_ip:
        print("❌ IP público da instância Ubuntu não encontrado")
        return False
    
    print(f"\n📋 INFORMAÇÕES DA INSTÂNCIA:")
    print("-" * 60)
    print(f"• IP Público: {ubuntu_public_ip}")
    print(f"• Sistema: Ubuntu 22.04 LTS")
    print(f"• Usuário: ubuntu")
    print(f"• Pasta: /home/ubuntu/marabet-ai")
    
    print(f"\n🔑 ETAPA 1: CONFIGURAR CHAVE SSH")
    print("-" * 60)
    print("1. Baixar a chave SSH da AWS:")
    print("   aws ec2 create-key-pair --key-name marabet-key-new --query 'KeyMaterial' --output text > ~/.ssh/marabet-key.pem")
    print()
    print("2. Configurar permissões (Windows):")
    print("   icacls C:\\Users\\%USERNAME%\\.ssh\\marabet-key.pem /inheritance:r")
    print("   icacls C:\\Users\\%USERNAME%\\.ssh\\marabet-key.pem /grant:r \"%USERNAME%:R\"")
    print()
    print("3. Configurar permissões (Linux/Mac):")
    print("   chmod 600 ~/.ssh/marabet-key.pem")
    
    print(f"\n🔗 ETAPA 2: CONECTAR VIA SSH")
    print("-" * 60)
    print("Comando para conectar:")
    print(f"ssh -i ~/.ssh/marabet-key.pem ubuntu@{ubuntu_public_ip}")
    print()
    print("Comando PowerShell:")
    print(f'$PUBLIC_IP = "{ubuntu_public_ip}"')
    print('ssh -i ~/.ssh/marabet-key.pem ubuntu@$PUBLIC_IP')
    
    print(f"\n🚀 ETAPA 3: PREPARAR SERVIDOR")
    print("-" * 60)
    print("Execute os seguintes comandos no servidor Ubuntu:")
    print()
    print("# 1. Atualizar sistema")
    print("sudo apt update && sudo apt upgrade -y")
    print()
    print("# 2. Instalar Docker")
    print("curl -fsSL https://get.docker.com -o get-docker.sh")
    print("sudo sh get-docker.sh")
    print("sudo usermod -aG docker ubuntu")
    print()
    print("# 3. Instalar Docker Compose")
    print('sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose')
    print("sudo chmod +x /usr/local/bin/docker-compose")
    print()
    print("# 4. Instalar ferramentas úteis")
    print("sudo apt install -y htop curl wget vim nano git python3 python3-pip python3-venv")
    print()
    print("# 5. Configurar variáveis de ambiente")
    print('echo "export DATABASE_URL=\\"postgresql://marabetadmin:MaraBet2024!SuperSecret@marabet-db.cmvmwskgiabr.us-east-1.rds.amazonaws.com:5432/postgres\\"" >> ~/.bashrc')
    print('echo "export REDIS_URL=\\"redis://marabet-redis.ve5qk7.0001.use1.cache.amazonaws.com:6379\\"" >> ~/.bashrc')
    print('echo "export API_FOOTBALL_KEY=\\"71b2b62386f2d1275cd3201a73e1e045\\"" >> ~/.bashrc')
    print('echo "export SECRET_KEY=\\"MaraBet2024!SuperSecretKey\\"" >> ~/.bashrc')
    print('echo "export ENVIRONMENT=\\"production\\"" >> ~/.bashrc')
    print('echo "export DEBUG=\\"false\\"" >> ~/.bashrc')
    print("source ~/.bashrc")
    
    print(f"\n📦 ETAPA 4: TRANSFERIR ARQUIVOS")
    print("-" * 60)
    print("Execute no Windows (PowerShell):")
    print()
    print("# 1. Ir para pasta do projeto")
    print("cd D:\\Usuario\\Maravilha\\Desktop\\MaraBet AI")
    print()
    print("# 2. Transferir arquivos via SCP")
    print(f"scp -i C:\\Users\\$env:USERNAME\\.ssh\\marabet-key.pem -r . ubuntu@{ubuntu_public_ip}:/home/ubuntu/marabet-ai/")
    print()
    print("Ou usar rsync (se disponível):")
    print(f"rsync -avz -e 'ssh -i ~/.ssh/marabet-key.pem' . ubuntu@{ubuntu_public_ip}:/home/ubuntu/marabet-ai/")
    
    print(f"\n🐳 ETAPA 5: CONFIGURAR DOCKER")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Ir para pasta do projeto")
    print("cd /home/ubuntu/marabet-ai")
    print()
    print("# 2. Verificar arquivos")
    print("ls -la")
    print()
    print("# 3. Dar permissão de execução ao script")
    print("chmod +x deploy.sh")
    print()
    print("# 4. Executar script de deploy")
    print("./deploy.sh")
    
    print(f"\n🔍 ETAPA 6: VERIFICAR DEPLOY")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Ver status dos containers")
    print("docker ps")
    print()
    print("# 2. Ver logs da aplicação")
    print("docker-compose logs -f")
    print()
    print("# 3. Verificar conectividade")
    print("curl http://localhost:8000/health")
    print()
    print("# 4. Verificar API docs")
    print("curl http://localhost:8000/docs")
    
    print(f"\n🌐 ETAPA 7: CONFIGURAR FIREWALL")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Configurar firewall")
    print("sudo ufw enable")
    print("sudo ufw allow ssh")
    print("sudo ufw allow 8000")
    print("sudo ufw allow 80")
    print("sudo ufw allow 443")
    print()
    print("# 2. Verificar status do firewall")
    print("sudo ufw status")
    
    print(f"\n📊 ETAPA 8: CONFIGURAR MONITORAMENTO")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Instalar htop para monitoramento")
    print("sudo apt install -y htop")
    print()
    print("# 2. Ver uso de recursos")
    print("htop")
    print()
    print("# 3. Ver espaço em disco")
    print("df -h")
    print()
    print("# 4. Ver memória")
    print("free -h")
    
    print(f"\n🔒 ETAPA 9: CONFIGURAR SEGURANÇA")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Instalar fail2ban")
    print("sudo apt install -y fail2ban")
    print("sudo systemctl enable fail2ban")
    print("sudo systemctl start fail2ban")
    print()
    print("# 2. Configurar backup automático")
    print("sudo apt install -y cron")
    print("crontab -e")
    print("# Adicionar: 0 2 * * * /home/ubuntu/backup.sh")
    
    print(f"\n🧪 ETAPA 10: TESTAR APLICAÇÃO")
    print("-" * 60)
    print("Execute no Windows (PowerShell):")
    print()
    print("# 1. Testar conectividade")
    print(f"curl http://{ubuntu_public_ip}:8000/health")
    print()
    print("# 2. Testar API docs")
    print(f"curl http://{ubuntu_public_ip}:8000/docs")
    print()
    print("# 3. Testar endpoint de predições")
    print(f"curl http://{ubuntu_public_ip}:8000/predictions")
    
    print(f"\n💡 COMANDOS ÚTEIS")
    print("-" * 60)
    print("# Conectar via SSH")
    print(f"ssh -i ~/.ssh/marabet-key.pem ubuntu@{ubuntu_public_ip}")
    print()
    print("# Ver status dos containers")
    print("cd /home/ubuntu/marabet-ai && docker ps")
    print()
    print("# Ver logs da aplicação")
    print("cd /home/ubuntu/marabet-ai && docker-compose logs -f")
    print()
    print("# Reiniciar aplicação")
    print("cd /home/ubuntu/marabet-ai && docker-compose restart")
    print()
    print("# Parar aplicação")
    print("cd /home/ubuntu/marabet-ai && docker-compose down")
    print()
    print("# Iniciar aplicação")
    print("cd /home/ubuntu/marabet-ai && docker-compose up -d")
    print()
    print("# Ver logs em tempo real")
    print("cd /home/ubuntu/marabet-ai && docker-compose logs -f --tail=50")
    
    print(f"\n🌐 ACESSAR APLICAÇÃO")
    print("-" * 60)
    print(f"• URL Principal: http://{ubuntu_public_ip}:8000")
    print(f"• API Documentation: http://{ubuntu_public_ip}:8000/docs")
    print(f"• Health Check: http://{ubuntu_public_ip}:8000/health")
    print(f"• Predictions: http://{ubuntu_public_ip}:8000/predictions")
    print(f"• Analysis: http://{ubuntu_public_ip}:8000/analysis")
    print(f"• Configuration: http://{ubuntu_public_ip}:8000/config")
    
    print(f"\n🎯 RESUMO DO DEPLOY")
    print("-" * 60)
    print("✅ Instância Ubuntu criada e configurada")
    print("✅ Docker e Docker Compose instalados")
    print("✅ Variáveis de ambiente configuradas")
    print("✅ Aplicação MaraBet AI pronta para deploy")
    print("✅ Instruções detalhadas fornecidas")
    
    print(f"\n🔗 PRÓXIMOS PASSOS")
    print("-" * 60)
    print("1. ✅ Configurar chave SSH")
    print("2. ✅ Conectar via SSH")
    print("3. ✅ Preparar servidor")
    print("4. ✅ Transferir arquivos")
    print("5. ✅ Configurar Docker")
    print("6. ✅ Verificar deploy")
    print("7. ✅ Configurar firewall")
    print("8. ✅ Configurar monitoramento")
    print("9. ✅ Configurar segurança")
    print("10. ✅ Testar aplicação")
    
    print("\n" + "="*80)
    print("🚀 MARABET AI - INSTRUÇÕES DE DEPLOY MANUAL")
    print("="*80)
    
    return True

def main():
    print("🚀 Iniciando instruções de deploy manual...")
    
    # Mostrar instruções
    success = show_deploy_instructions()
    
    if success:
        print("\n🎯 INSTRUÇÕES DE DEPLOY PRONTAS!")
        print("Siga as instruções acima para fazer deploy da aplicação!")
    else:
        print("\n❌ Falha ao carregar configurações")
        print("Verifique se o arquivo aws_infrastructure_config.json existe")

if __name__ == "__main__":
    main()
