#!/usr/bin/env python3
"""
Script de Implementação de Testes de Carga - MaraBet AI
Implementa testes de carga com Locust, JMeter e Artillery
"""

import subprocess
import json
import os
from datetime import datetime

def run_aws_command(command, return_text=False):
    """Executa comando AWS CLI e retorna resultado"""
    try:
        result = subprocess.run(command, shell=True, capture_output=True, text=True)
        if result.returncode == 0:
            if return_text:
                return result.stdout.strip()
            else:
                return json.loads(result.stdout) if result.stdout.strip() else {}
        else:
            print(f"❌ Erro no comando: {command}")
            print(f"Erro: {result.stderr}")
            return None
    except json.JSONDecodeError:
        print(f"❌ Erro de decodificação JSON para o comando: {command}")
        print(f"Saída: {result.stdout}")
        print(f"Erro: {result.stderr}")
        return None
    except Exception as e:
        print(f"❌ Exceção no comando: {command}")
        print(f"Erro: {e}")
        return None

def load_config():
    """Carrega configurações existentes do arquivo JSON."""
    config_file = 'aws_infrastructure_config.json'
    if os.path.exists(config_file):
        with open(config_file, 'r') as f:
            return json.load(f)
    return {}

def save_config(config):
    """Salva configurações no arquivo JSON."""
    config_file = 'aws_infrastructure_config.json'
    with open(config_file, 'w') as f:
        json.dump(config, f, indent=2)

def create_load_testing_implementation():
    """Cria implementação de testes de carga"""
    print("🚀 MARABET AI - IMPLEMENTAÇÃO DE TESTES DE CARGA")
    print("=" * 80)
    print(f"📅 Data/Hora: {datetime.now().strftime('%d/%m/%Y %H:%M:%S')}")
    
    # Carregar configuração existente
    config = load_config()
    
    print("\n🔧 ETAPA 1: CONFIGURAR LOCUST (TESTES DE CARGA PYTHON)")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Instalar Locust")
    print("sudo apt update")
    print("sudo apt install -y python3-pip")
    print("pip3 install locust")
    print()
    print("# 2. Criar diretório para testes de carga")
    print("mkdir -p /opt/load-testing")
    print("cd /opt/load-testing")
    print()
    print("# 3. Criar arquivo de teste Locust para MaraBet AI")
    print("cat > /opt/load-testing/marabet_load_test.py << 'EOF'")
    print("from locust import HttpUser, task, between")
    print("import random")
    print("import json")
    print()
    print("class MaraBetAILoadTest(HttpUser):")
    print("    wait_time = between(1, 3)")
    print("    host = 'https://marabet.com'")
    print()
    print("    def on_start(self):")
    print("        \"\"\"Executado quando um usuário virtual inicia\"\"\"")
    print("        self.login()")
    print()
    print("    def login(self):")
    print("        \"\"\"Simula login do usuário\"\"\"")
    print("        response = self.client.post('/api/auth/login', json={")
    print("            'username': 'test_user',")
    print("            'password': 'test_password'")
    print("        })")
    print("        if response.status_code == 200:")
    print("            self.token = response.json().get('token')")
    print("            self.client.headers.update({'Authorization': f'Bearer {self.token}'})")
    print()
    print("    @task(3)")
    print("    def get_predictions(self):")
    print("        \"\"\"Testa endpoint de predições\"\"\"")
    print("        self.client.get('/api/predictions')")
    print()
    print("    @task(2)")
    print("    def get_matches(self):")
    print("        \"\"\"Testa endpoint de partidas\"\"\"")
    print("        self.client.get('/api/matches')")
    print()
    print("    @task(1)")
    print("    def get_analysis(self):")
    print("        \"\"\"Testa endpoint de análise\"\"\"")
    print("        self.client.get('/api/analysis')")
    print()
    print("    @task(1)")
    print("    def create_prediction(self):")
    print("        \"\"\"Testa criação de predição\"\"\"")
    print("        prediction_data = {")
    print("            'match_id': f'match_{random.randint(1000, 9999)}',")
    print("            'home_team': 'Real Madrid',")
    print("            'away_team': 'Barcelona',")
    print("            'league': 'La Liga',")
    print("            'match_date': '2024-12-01T20:00:00Z'")
    print("        }")
    print("        self.client.post('/api/predict', json=prediction_data)")
    print()
    print("    @task(1)")
    print("    def get_health(self):")
    print("        \"\"\"Testa endpoint de health check\"\"\"")
    print("        self.client.get('/health')")
    print()
    print("    @task(1)")
    print("    def get_config(self):")
    print("        \"\"\"Testa endpoint de configuração\"\"\"")
    print("        self.client.get('/config')")
    print()
    print("    @task(1)")
    print("    def get_logs(self):")
    print("        \"\"\"Testa endpoint de logs\"\"\"")
    print("        self.client.get('/logs')")
    print("EOF")
    print()
    print("# 4. Criar arquivo de configuração do Locust")
    print("cat > /opt/load-testing/locust.conf << 'EOF'")
    print("host = https://marabet.com")
    print("users = 100")
    print("spawn-rate = 10")
    print("run-time = 300s")
    print("headless = true")
    print("html = /opt/load-testing/reports/locust_report.html")
    print("csv = /opt/load-testing/reports/locust_report")
    print("EOF")
    print()
    print("# 5. Criar diretório para relatórios")
    print("mkdir -p /opt/load-testing/reports")
    print()
    print("# 6. Criar script de execução do Locust")
    print("cat > /opt/load-testing/run_locust_test.sh << 'EOF'")
    print("#!/bin/bash")
    print("cd /opt/load-testing")
    print("echo \"🚀 Iniciando teste de carga com Locust...\"")
    print("echo \"📊 Usuários: 100, Taxa de spawn: 10/s, Duração: 5 minutos\"")
    print("echo \"🌐 Host: https://marabet.com\"")
    print("echo \"📁 Relatórios: /opt/load-testing/reports/\"")
    print()
    print("# Executar teste de carga")
    print("locust -f marabet_load_test.py --config=locust.conf")
    print()
    print("echo \"✅ Teste de carga concluído!\"")
    print("echo \"📊 Relatórios gerados em: /opt/load-testing/reports/\"")
    print("EOF")
    print()
    print("# 7. Tornar script executável")
    print("chmod +x /opt/load-testing/run_locust_test.sh")
    print()
    print("# 8. Executar teste de carga")
    print("cd /opt/load-testing")
    print("./run_locust_test.sh")
    
    print("\n📊 ETAPA 2: CONFIGURAR JMETER (TESTES DE CARGA JAVA)")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Instalar Java (requisito do JMeter)")
    print("sudo apt update")
    print("sudo apt install -y openjdk-11-jdk")
    print()
    print("# 2. Baixar JMeter")
    print("cd /opt")
    print("wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.2.tgz")
    print("tar -xzf apache-jmeter-5.6.2.tgz")
    print("sudo mv apache-jmeter-5.6.2 jmeter")
    print()
    print("# 3. Criar arquivo de teste JMeter para MaraBet AI")
    print("cat > /opt/jmeter/test-plans/marabet_load_test.jmx << 'EOF'")
    print("<?xml version=\"1.0\" encoding=\"UTF-8\"?>")
    print("<jmeterTestPlan version=\"1.2\" properties=\"5.0\" jmeter=\"5.6.2\">")
    print("  <hashTree>")
    print("    <TestPlan guiclass=\"TestPlanGui\" testclass=\"TestPlan\" testname=\"MaraBet AI Load Test\" enabled=\"true\">")
    print("      <stringProp name=\"TestPlan.comments\">Teste de carga para MaraBet AI</stringProp>")
    print("      <boolProp name=\"TestPlan.functional_mode\">false</boolProp>")
    print("      <boolProp name=\"TestPlan.tearDown_on_shutdown\">true</boolProp>")
    print("      <boolProp name=\"TestPlan.serialize_threadgroups\">false</boolProp>")
    print("      <elementProp name=\"TestPlan.arguments\" elementType=\"Arguments\" guiclass=\"ArgumentsPanel\" testclass=\"Arguments\" testname=\"User Defined Variables\" enabled=\"true\">")
    print("        <collectionProp name=\"Arguments.arguments\">")
    print("          <elementProp name=\"HOST\" elementType=\"Argument\">")
    print("            <stringProp name=\"Argument.name\">HOST</stringProp>")
    print("            <stringProp name=\"Argument.value\">https://marabet.com</stringProp>")
    print("            <stringProp name=\"Argument.metadata\">=</stringProp>")
    print("          </elementProp>")
    print("        </collectionProp>")
    print("      </elementProp>")
    print("      <stringProp name=\"TestPlan.user_define_classpath\"></stringProp>")
    print("    </TestPlan>")
    print("    <hashTree>")
    print("      <ThreadGroup guiclass=\"ThreadGroupGui\" testclass=\"ThreadGroup\" testname=\"MaraBet AI Users\" enabled=\"true\">")
    print("        <stringProp name=\"ThreadGroup.on_sample_error\">continue</stringProp>")
    print("        <elementProp name=\"ThreadGroup.main_controller\" elementType=\"LoopController\" guiclass=\"LoopControllerGui\" testclass=\"LoopController\" testname=\"Loop Controller\" enabled=\"true\">")
    print("          <boolProp name=\"LoopController.continue_forever\">false</boolProp>")
    print("          <stringProp name=\"LoopController.loops\">10</stringProp>")
    print("        </elementProp>")
    print("        <stringProp name=\"ThreadGroup.num_threads\">100</stringProp>")
    print("        <stringProp name=\"ThreadGroup.ramp_time\">60</stringProp>")
    print("        <boolProp name=\"ThreadGroup.scheduler\">true</boolProp>")
    print("        <stringProp name=\"ThreadGroup.duration\">300</stringProp>")
    print("        <stringProp name=\"ThreadGroup.delay\">0</stringProp>")
    print("        <boolProp name=\"ThreadGroup.same_user_on_next_iteration\">true</boolProp>")
    print("      </ThreadGroup>")
    print("      <hashTree>")
    print("        <HTTPSamplerProxy guiclass=\"HttpTestSampleGui\" testclass=\"HTTPSamplerProxy\" testname=\"Get Predictions\" enabled=\"true\">")
    print("          <elementProp name=\"HTTPsampler.Arguments\" elementType=\"Arguments\" guiclass=\"HTTPArgumentsPanel\" testclass=\"Arguments\" testname=\"User Defined Variables\" enabled=\"true\">")
    print("            <collectionProp name=\"Arguments.arguments\"/>")
    print("          </elementProp>")
    print("          <stringProp name=\"HTTPSampler.domain\">${HOST}</stringProp>")
    print("          <stringProp name=\"HTTPSampler.port\"></stringProp>")
    print("          <stringProp name=\"HTTPSampler.protocol\">https</stringProp>")
    print("          <stringProp name=\"HTTPSampler.contentEncoding\"></stringProp>")
    print("          <stringProp name=\"HTTPSampler.path\">/api/predictions</stringProp>")
    print("          <stringProp name=\"HTTPSampler.method\">GET</stringProp>")
    print("          <boolProp name=\"HTTPSampler.follow_redirects\">true</boolProp>")
    print("          <boolProp name=\"HTTPSampler.auto_redirects\">false</boolProp>")
    print("          <boolProp name=\"HTTPSampler.use_keepalive\">true</boolProp>")
    print("          <boolProp name=\"HTTPSampler.DO_MULTIPART_POST\">false</boolProp>")
    print("          <stringProp name=\"HTTPSampler.embedded_url_re\"></stringProp>")
    print("          <stringProp name=\"HTTPSampler.connect_timeout\"></stringProp>")
    print("          <stringProp name=\"HTTPSampler.response_timeout\"></stringProp>")
    print("        </HTTPSamplerProxy>")
    print("        <hashTree/>")
    print("        <HTTPSamplerProxy guiclass=\"HttpTestSampleGui\" testclass=\"HTTPSamplerProxy\" testname=\"Get Matches\" enabled=\"true\">")
    print("          <elementProp name=\"HTTPsampler.Arguments\" elementType=\"Arguments\" guiclass=\"HTTPArgumentsPanel\" testclass=\"Arguments\" testname=\"User Defined Variables\" enabled=\"true\">")
    print("            <collectionProp name=\"Arguments.arguments\"/>")
    print("          </elementProp>")
    print("          <stringProp name=\"HTTPSampler.domain\">${HOST}</stringProp>")
    print("          <stringProp name=\"HTTPSampler.port\"></stringProp>")
    print("          <stringProp name=\"HTTPSampler.protocol\">https</stringProp>")
    print("          <stringProp name=\"HTTPSampler.contentEncoding\"></stringProp>")
    print("          <stringProp name=\"HTTPSampler.path\">/api/matches</stringProp>")
    print("          <stringProp name=\"HTTPSampler.method\">GET</stringProp>")
    print("          <boolProp name=\"HTTPSampler.follow_redirects\">true</boolProp>")
    print("          <boolProp name=\"HTTPSampler.auto_redirects\">false</boolProp>")
    print("          <boolProp name=\"HTTPSampler.use_keepalive\">true</boolProp>")
    print("          <boolProp name=\"HTTPSampler.DO_MULTIPART_POST\">false</boolProp>")
    print("          <stringProp name=\"HTTPSampler.embedded_url_re\"></stringProp>")
    print("          <stringProp name=\"HTTPSampler.connect_timeout\"></stringProp>")
    print("          <stringProp name=\"HTTPSampler.response_timeout\"></stringProp>")
    print("        </HTTPSamplerProxy>")
    print("        <hashTree/>")
    print("        <HTTPSamplerProxy guiclass=\"HttpTestSampleGui\" testclass=\"HTTPSamplerProxy\" testname=\"Get Analysis\" enabled=\"true\">")
    print("          <elementProp name=\"HTTPsampler.Arguments\" elementType=\"Arguments\" guiclass=\"HTTPArgumentsPanel\" testclass=\"Arguments\" testname=\"User Defined Variables\" enabled=\"true\">")
    print("            <collectionProp name=\"Arguments.arguments\"/>")
    print("          </elementProp>")
    print("          <stringProp name=\"HTTPSampler.domain\">${HOST}</stringProp>")
    print("          <stringProp name=\"HTTPSampler.port\"></stringProp>")
    print("          <stringProp name=\"HTTPSampler.protocol\">https</stringProp>")
    print("          <stringProp name=\"HTTPSampler.contentEncoding\"></stringProp>")
    print("          <stringProp name=\"HTTPSampler.path\">/api/analysis</stringProp>")
    print("          <stringProp name=\"HTTPSampler.method\">GET</stringProp>")
    print("          <boolProp name=\"HTTPSampler.follow_redirects\">true</boolProp>")
    print("          <boolProp name=\"HTTPSampler.auto_redirects\">false</boolProp>")
    print("          <boolProp name=\"HTTPSampler.use_keepalive\">true</boolProp>")
    print("          <boolProp name=\"HTTPSampler.DO_MULTIPART_POST\">false</boolProp>")
    print("          <stringProp name=\"HTTPSampler.embedded_url_re\"></stringProp>")
    print("          <stringProp name=\"HTTPSampler.connect_timeout\"></stringProp>")
    print("          <stringProp name=\"HTTPSampler.response_timeout\"></stringProp>")
    print("        </HTTPSamplerProxy>")
    print("        <hashTree/>")
    print("        <HTTPSamplerProxy guiclass=\"HttpTestSampleGui\" testclass=\"HTTPSamplerProxy\" testname=\"Create Prediction\" enabled=\"true\">")
    print("          <elementProp name=\"HTTPsampler.Arguments\" elementType=\"Arguments\" guiclass=\"HTTPArgumentsPanel\" testclass=\"Arguments\" testname=\"User Defined Variables\" enabled=\"true\">")
    print("            <collectionProp name=\"Arguments.arguments\">")
    print("              <elementProp name=\"\" elementType=\"HTTPArgument\">")
    print("                <boolProp name=\"HTTPArgument.always_encode\">false</boolProp>")
    print("                <stringProp name=\"Argument.value\">{\"match_id\":\"match_123\",\"home_team\":\"Real Madrid\",\"away_team\":\"Barcelona\",\"league\":\"La Liga\",\"match_date\":\"2024-12-01T20:00:00Z\"}</stringProp>")
    print("                <stringProp name=\"Argument.metadata\">=</stringProp>")
    print("              </elementProp>")
    print("            </collectionProp>")
    print("          </elementProp>")
    print("          <stringProp name=\"HTTPSampler.domain\">${HOST}</stringProp>")
    print("          <stringProp name=\"HTTPSampler.port\"></stringProp>")
    print("          <stringProp name=\"HTTPSampler.protocol\">https</stringProp>")
    print("          <stringProp name=\"HTTPSampler.contentEncoding\"></stringProp>")
    print("          <stringProp name=\"HTTPSampler.path\">/api/predict</stringProp>")
    print("          <stringProp name=\"HTTPSampler.method\">POST</stringProp>")
    print("          <boolProp name=\"HTTPSampler.follow_redirects\">true</boolProp>")
    print("          <boolProp name=\"HTTPSampler.auto_redirects\">false</boolProp>")
    print("          <boolProp name=\"HTTPSampler.use_keepalive\">true</boolProp>")
    print("          <boolProp name=\"HTTPSampler.DO_MULTIPART_POST\">false</boolProp>")
    print("          <stringProp name=\"HTTPSampler.embedded_url_re\"></stringProp>")
    print("          <stringProp name=\"HTTPSampler.connect_timeout\"></stringProp>")
    print("          <stringProp name=\"HTTPSampler.response_timeout\"></stringProp>")
    print("        </HTTPSamplerProxy>")
    print("        <hashTree/>")
    print("        <HTTPSamplerProxy guiclass=\"HttpTestSampleGui\" testclass=\"HTTPSamplerProxy\" testname=\"Get Health\" enabled=\"true\">")
    print("          <elementProp name=\"HTTPsampler.Arguments\" elementType=\"Arguments\" guiclass=\"HTTPArgumentsPanel\" testclass=\"Arguments\" testname=\"User Defined Variables\" enabled=\"true\">")
    print("            <collectionProp name=\"Arguments.arguments\"/>")
    print("          </elementProp>")
    print("          <stringProp name=\"HTTPSampler.domain\">${HOST}</stringProp>")
    print("          <stringProp name=\"HTTPSampler.port\"></stringProp>")
    print("          <stringProp name=\"HTTPSampler.protocol\">https</stringProp>")
    print("          <stringProp name=\"HTTPSampler.contentEncoding\"></stringProp>")
    print("          <stringProp name=\"HTTPSampler.path\">/health</stringProp>")
    print("          <stringProp name=\"HTTPSampler.method\">GET</stringProp>")
    print("          <boolProp name=\"HTTPSampler.follow_redirects\">true</boolProp>")
    print("          <boolProp name=\"HTTPSampler.auto_redirects\">false</boolProp>")
    print("          <boolProp name=\"HTTPSampler.use_keepalive\">true</boolProp>")
    print("          <boolProp name=\"HTTPSampler.DO_MULTIPART_POST\">false</boolProp>")
    print("          <stringProp name=\"HTTPSampler.embedded_url_re\"></stringProp>")
    print("          <stringProp name=\"HTTPSampler.connect_timeout\"></stringProp>")
    print("          <stringProp name=\"HTTPSampler.response_timeout\"></stringProp>")
    print("        </HTTPSamplerProxy>")
    print("        <hashTree/>")
    print("        <HTTPSamplerProxy guiclass=\"HttpTestSampleGui\" testclass=\"HTTPSamplerProxy\" testname=\"Get Config\" enabled=\"true\">")
    print("          <elementProp name=\"HTTPsampler.Arguments\" elementType=\"Arguments\" guiclass=\"HTTPArgumentsPanel\" testclass=\"Arguments\" testname=\"User Defined Variables\" enabled=\"true\">")
    print("            <collectionProp name=\"Arguments.arguments\"/>")
    print("          </elementProp>")
    print("          <stringProp name=\"HTTPSampler.domain\">${HOST}</stringProp>")
    print("          <stringProp name=\"HTTPSampler.port\"></stringProp>")
    print("          <stringProp name=\"HTTPSampler.protocol\">https</stringProp>")
    print("          <stringProp name=\"HTTPSampler.contentEncoding\"></stringProp>")
    print("          <stringProp name=\"HTTPSampler.path\">/config</stringProp>")
    print("          <stringProp name=\"HTTPSampler.method\">GET</stringProp>")
    print("          <boolProp name=\"HTTPSampler.follow_redirects\">true</boolProp>")
    print("          <boolProp name=\"HTTPSampler.auto_redirects\">false</boolProp>")
    print("          <boolProp name=\"HTTPSampler.use_keepalive\">true</boolProp>")
    print("          <boolProp name=\"HTTPSampler.DO_MULTIPART_POST\">false</boolProp>")
    print("          <stringProp name=\"HTTPSampler.embedded_url_re\"></stringProp>")
    print("          <stringProp name=\"HTTPSampler.connect_timeout\"></stringProp>")
    print("          <stringProp name=\"HTTPSampler.response_timeout\"></stringProp>")
    print("        </HTTPSamplerProxy>")
    print("        <hashTree/>")
    print("        <HTTPSamplerProxy guiclass=\"HttpTestSampleGui\" testclass=\"HTTPSamplerProxy\" testname=\"Get Logs\" enabled=\"true\">")
    print("          <elementProp name=\"HTTPsampler.Arguments\" elementType=\"Arguments\" guiclass=\"HTTPArgumentsPanel\" testclass=\"Arguments\" testname=\"User Defined Variables\" enabled=\"true\">")
    print("            <collectionProp name=\"Arguments.arguments\"/>")
    print("          </elementProp>")
    print("          <stringProp name=\"HTTPSampler.domain\">${HOST}</stringProp>")
    print("          <stringProp name=\"HTTPSampler.port\"></stringProp>")
    print("          <stringProp name=\"HTTPSampler.protocol\">https</stringProp>")
    print("          <stringProp name=\"HTTPSampler.contentEncoding\"></stringProp>")
    print("          <stringProp name=\"HTTPSampler.path\">/logs</stringProp>")
    print("          <stringProp name=\"HTTPSampler.method\">GET</stringProp>")
    print("          <boolProp name=\"HTTPSampler.follow_redirects\">true</boolProp>")
    print("          <boolProp name=\"HTTPSampler.auto_redirects\">false</boolProp>")
    print("          <boolProp name=\"HTTPSampler.use_keepalive\">true</boolProp>")
    print("          <boolProp name=\"HTTPSampler.DO_MULTIPART_POST\">false</boolProp>")
    print("          <stringProp name=\"HTTPSampler.embedded_url_re\"></stringProp>")
    print("          <stringProp name=\"HTTPSampler.connect_timeout\"></stringProp>")
    print("          <stringProp name=\"HTTPSampler.response_timeout\"></stringProp>")
    print("        </HTTPSamplerProxy>")
    print("        <hashTree/>")
    print("      </hashTree>")
    print("    </hashTree>")
    print("  </hashTree>")
    print("</jmeterTestPlan>")
    print("EOF")
    print()
    print("# 4. Criar diretório para relatórios JMeter")
    print("mkdir -p /opt/jmeter/reports")
    print()
    print("# 5. Criar script de execução do JMeter")
    print("cat > /opt/jmeter/run_jmeter_test.sh << 'EOF'")
    print("#!/bin/bash")
    print("cd /opt/jmeter")
    print("echo \"🚀 Iniciando teste de carga com JMeter...\"")
    print("echo \"📊 Usuários: 100, Ramp-up: 60s, Duração: 5 minutos\"")
    print("echo \"🌐 Host: https://marabet.com\"")
    print("echo \"📁 Relatórios: /opt/jmeter/reports/\"")
    print()
    print("# Executar teste de carga")
    print("./bin/jmeter -n -t test-plans/marabet_load_test.jmx -l reports/marabet_load_test.jtl -e -o reports/marabet_load_test_report")
    print()
    print("echo \"✅ Teste de carga concluído!\"")
    print("echo \"📊 Relatórios gerados em: /opt/jmeter/reports/\"")
    print("EOF")
    print()
    print("# 6. Tornar script executável")
    print("chmod +x /opt/jmeter/run_jmeter_test.sh")
    print()
    print("# 7. Executar teste de carga")
    print("cd /opt/jmeter")
    print("./run_jmeter_test.sh")
    
    print("\n🎯 ETAPA 3: CONFIGURAR ARTILLERY (TESTES DE CARGA NODE.JS)")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Instalar Node.js (requisito do Artillery)")
    print("curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -")
    print("sudo apt-get install -y nodejs")
    print()
    print("# 2. Instalar Artillery")
    print("sudo npm install -g artillery")
    print()
    print("# 3. Criar diretório para testes Artillery")
    print("mkdir -p /opt/artillery-tests")
    print("cd /opt/artillery-tests")
    print()
    print("# 4. Criar arquivo de configuração do Artillery")
    print("cat > /opt/artillery-tests/marabet_load_test.yml << 'EOF'")
    print("config:")
    print("  target: 'https://marabet.com'")
    print("  phases:")
    print("    - duration: 60")
    print("      arrivalRate: 10")
    print("      name: 'Warm up'")
    print("    - duration: 180")
    print("      arrivalRate: 50")
    print("      name: 'Ramp up load'")
    print("    - duration: 60")
    print("      arrivalRate: 100")
    print("      name: 'Sustained load'")
    print("  defaults:")
    print("    headers:")
    print("      Content-Type: 'application/json'")
    print("  plugins:")
    print("    metrics-by-endpoint:")
    print("      useOnlyRequestNames: true")
    print()
    print("scenarios:")
    print("  - name: 'MaraBet AI Load Test'")
    print("    weight: 100")
    print("    flow:")
    print("      - get:")
    print("          url: '/health'")
    print("          name: 'Health Check'")
    print("      - get:")
    print("          url: '/api/predictions'")
    print("          name: 'Get Predictions'")
    print("      - get:")
    print("          url: '/api/matches'")
    print("          name: 'Get Matches'")
    print("      - get:")
    print("          url: '/api/analysis'")
    print("          name: 'Get Analysis'")
    print("      - post:")
    print("          url: '/api/predict'")
    print("          name: 'Create Prediction'")
    print("          json:")
    print("            match_id: 'match_{{ $randomInt(1000, 9999) }}'")
    print("            home_team: 'Real Madrid'")
    print("            away_team: 'Barcelona'")
    print("            league: 'La Liga'")
    print("            match_date: '2024-12-01T20:00:00Z'")
    print("      - get:")
    print("          url: '/config'")
    print("          name: 'Get Config'")
    print("      - get:")
    print("          url: '/logs'")
    print("          name: 'Get Logs'")
    print("EOF")
    print()
    print("# 5. Criar diretório para relatórios Artillery")
    print("mkdir -p /opt/artillery-tests/reports")
    print()
    print("# 6. Criar script de execução do Artillery")
    print("cat > /opt/artillery-tests/run_artillery_test.sh << 'EOF'")
    print("#!/bin/bash")
    print("cd /opt/artillery-tests")
    print("echo \"🚀 Iniciando teste de carga com Artillery...\"")
    print("echo \"📊 Fases: Warm up (60s), Ramp up (180s), Sustained (60s)\"")
    print("echo \"🌐 Host: https://marabet.com\"")
    print("echo \"📁 Relatórios: /opt/artillery-tests/reports/\"")
    print()
    print("# Executar teste de carga")
    print("artillery run marabet_load_test.yml --output reports/marabet_load_test.json")
    print()
    print("# Gerar relatório HTML")
    print("artillery report reports/marabet_load_test.json --output reports/marabet_load_test_report.html")
    print()
    print("echo \"✅ Teste de carga concluído!\"")
    print("echo \"📊 Relatórios gerados em: /opt/artillery-tests/reports/\"")
    print("EOF")
    print()
    print("# 7. Tornar script executável")
    print("chmod +x /opt/artillery-tests/run_artillery_test.sh")
    print()
    print("# 8. Executar teste de carga")
    print("cd /opt/artillery-tests")
    print("./run_artillery_test.sh")
    
    print("\n📈 ETAPA 4: CONFIGURAR K6 (TESTES DE CARGA JAVASCRIPT)")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Instalar K6")
    print("sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69")
    print("echo \"deb https://dl.k6.io/deb stable main\" | sudo tee /etc/apt/sources.list.d/k6.list")
    print("sudo apt update")
    print("sudo apt install k6")
    print()
    print("# 2. Criar diretório para testes K6")
    print("mkdir -p /opt/k6-tests")
    print("cd /opt/k6-tests")
    print()
    print("# 3. Criar arquivo de teste K6 para MaraBet AI")
    print("cat > /opt/k6-tests/marabet_load_test.js << 'EOF'")
    print("import http from 'k6/http';")
    print("import { check, sleep } from 'k6';")
    print("import { Rate } from 'k6/metrics';")
    print()
    print("// Métricas customizadas")
    print("const errorRate = new Rate('errors');")
    print()
    print("// Configuração do teste")
    print("export const options = {")
    print("  stages: [")
    print("    { duration: '60s', target: 10 }, // Warm up")
    print("    { duration: '180s', target: 50 }, // Ramp up")
    print("    { duration: '60s', target: 100 }, // Sustained load")
    print("  ],")
    print("  thresholds: {")
    print("    http_req_duration: ['p(95)<2000'], // 95% das requisições devem ser < 2s")
    print("    http_req_failed: ['rate<0.1'], // Taxa de erro < 10%")
    print("    errors: ['rate<0.1'], // Taxa de erro customizada < 10%")
    print("  },")
    print("};")
    print()
    print("// URL base")
    print("const BASE_URL = 'https://marabet.com';")
    print()
    print("// Função principal do teste")
    print("export default function() {")
    print("  // Health Check")
    print("  let response = http.get(`${BASE_URL}/health`);")
    print("  check(response, {")
    print("    'health check status is 200': (r) => r.status === 200,")
    print("  });")
    print("  errorRate.add(response.status !== 200);")
    print("  sleep(1);")
    print()
    print("  // Get Predictions")
    print("  response = http.get(`${BASE_URL}/api/predictions`);")
    print("  check(response, {")
    print("    'predictions status is 200': (r) => r.status === 200,")
    print("    'predictions response time < 2s': (r) => r.timings.duration < 2000,")
    print("  });")
    print("  errorRate.add(response.status !== 200);")
    print("  sleep(1);")
    print()
    print("  // Get Matches")
    print("  response = http.get(`${BASE_URL}/api/matches`);")
    print("  check(response, {")
    print("    'matches status is 200': (r) => r.status === 200,")
    print("    'matches response time < 2s': (r) => r.timings.duration < 2000,")
    print("  });")
    print("  errorRate.add(response.status !== 200);")
    print("  sleep(1);")
    print()
    print("  // Get Analysis")
    print("  response = http.get(`${BASE_URL}/api/analysis`);")
    print("  check(response, {")
    print("    'analysis status is 200': (r) => r.status === 200,")
    print("    'analysis response time < 2s': (r) => r.timings.duration < 2000,")
    print("  });")
    print("  errorRate.add(response.status !== 200);")
    print("  sleep(1);")
    print()
    print("  // Create Prediction")
    print("  const payload = JSON.stringify({")
    print("    match_id: `match_${Math.floor(Math.random() * 9000) + 1000}`,")
    print("    home_team: 'Real Madrid',")
    print("    away_team: 'Barcelona',")
    print("    league: 'La Liga',")
    print("    match_date: '2024-12-01T20:00:00Z'")
    print("  });")
    print("  const params = {")
    print("    headers: { 'Content-Type': 'application/json' },")
    print("  };")
    print("  response = http.post(`${BASE_URL}/api/predict`, payload, params);")
    print("  check(response, {")
    print("    'create prediction status is 200': (r) => r.status === 200,")
    print("    'create prediction response time < 3s': (r) => r.timings.duration < 3000,")
    print("  });")
    print("  errorRate.add(response.status !== 200);")
    print("  sleep(1);")
    print()
    print("  // Get Config")
    print("  response = http.get(`${BASE_URL}/config`);")
    print("  check(response, {")
    print("    'config status is 200': (r) => r.status === 200,")
    print("    'config response time < 2s': (r) => r.timings.duration < 2000,")
    print("  });")
    print("  errorRate.add(response.status !== 200);")
    print("  sleep(1);")
    print()
    print("  // Get Logs")
    print("  response = http.get(`${BASE_URL}/logs`);")
    print("  check(response, {")
    print("    'logs status is 200': (r) => r.status === 200,")
    print("    'logs response time < 2s': (r) => r.timings.duration < 2000,")
    print("  });")
    print("  errorRate.add(response.status !== 200);")
    print("  sleep(1);")
    print("}")
    print("EOF")
    print()
    print("# 4. Criar diretório para relatórios K6")
    print("mkdir -p /opt/k6-tests/reports")
    print()
    print("# 5. Criar script de execução do K6")
    print("cat > /opt/k6-tests/run_k6_test.sh << 'EOF'")
    print("#!/bin/bash")
    print("cd /opt/k6-tests")
    print("echo \"🚀 Iniciando teste de carga com K6...\"")
    print("echo \"📊 Fases: Warm up (60s), Ramp up (180s), Sustained (60s)\"")
    print("echo \"🌐 Host: https://marabet.com\"")
    print("echo \"📁 Relatórios: /opt/k6-tests/reports/\"")
    print()
    print("# Executar teste de carga")
    print("k6 run --out json=reports/marabet_load_test.json marabet_load_test.js")
    print()
    print("echo \"✅ Teste de carga concluído!\"")
    print("echo \"📊 Relatórios gerados em: /opt/k6-tests/reports/\"")
    print("EOF")
    print()
    print("# 6. Tornar script executável")
    print("chmod +x /opt/k6-tests/run_k6_test.sh")
    print()
    print("# 7. Executar teste de carga")
    print("cd /opt/k6-tests")
    print("./run_k6_test.sh")
    
    print("\n🔧 ETAPA 5: CONFIGURAR WRK (TESTES DE CARGA C)")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Instalar dependências do WRK")
    print("sudo apt update")
    print("sudo apt install -y build-essential libssl-dev git")
    print()
    print("# 2. Baixar e compilar WRK")
    print("cd /opt")
    print("git clone https://github.com/wg/wrk.git")
    print("cd wrk")
    print("make")
    print("sudo cp wrk /usr/local/bin/")
    print()
    print("# 3. Criar diretório para testes WRK")
    print("mkdir -p /opt/wrk-tests")
    print("cd /opt/wrk-tests")
    print()
    print("# 4. Criar script de execução do WRK")
    print("cat > /opt/wrk-tests/run_wrk_test.sh << 'EOF'")
    print("#!/bin/bash")
    print("cd /opt/wrk-tests")
    print("echo \"🚀 Iniciando teste de carga com WRK...\"")
    print("echo \"📊 Threads: 12, Connections: 100, Duration: 5 minutos\"")
    print("echo \"🌐 Host: https://marabet.com\"")
    print("echo \"📁 Relatórios: /opt/wrk-tests/reports/\"")
    print()
    print("# Criar diretório para relatórios")
    print("mkdir -p reports")
    print()
    print("# Executar teste de carga para diferentes endpoints")
    print("echo \"🔍 Testando endpoint /health...\"")
    print("wrk -t12 -c100 -d300s -s scripts/health.lua https://marabet.com/health > reports/health_test.txt")
    print()
    print("echo \"🔍 Testando endpoint /api/predictions...\"")
    print("wrk -t12 -c100 -d300s -s scripts/predictions.lua https://marabet.com/api/predictions > reports/predictions_test.txt")
    print()
    print("echo \"🔍 Testando endpoint /api/matches...\"")
    print("wrk -t12 -c100 -d300s -s scripts/matches.lua https://marabet.com/api/matches > reports/matches_test.txt")
    print()
    print("echo \"🔍 Testando endpoint /api/analysis...\"")
    print("wrk -t12 -c100 -d300s -s scripts/analysis.lua https://marabet.com/api/analysis > reports/analysis_test.txt")
    print()
    print("echo \"🔍 Testando endpoint /config...\"")
    print("wrk -t12 -c100 -d300s -s scripts/config.lua https://marabet.com/config > reports/config_test.txt")
    print()
    print("echo \"🔍 Testando endpoint /logs...\"")
    print("wrk -t12 -c100 -d300s -s scripts/logs.lua https://marabet.com/logs > reports/logs_test.txt")
    print()
    print("echo \"✅ Teste de carga concluído!\"")
    print("echo \"📊 Relatórios gerados em: /opt/wrk-tests/reports/\"")
    print("EOF")
    print()
    print("# 5. Criar diretório para scripts WRK")
    print("mkdir -p /opt/wrk-tests/scripts")
    print()
    print("# 6. Criar scripts Lua para WRK")
    print("cat > /opt/wrk-tests/scripts/health.lua << 'EOF'")
    print("wrk.method = \"GET\"")
    print("wrk.path = \"/health\"")
    print("wrk.headers[\"Content-Type\"] = \"application/json\"")
    print("EOF")
    print()
    print("cat > /opt/wrk-tests/scripts/predictions.lua << 'EOF'")
    print("wrk.method = \"GET\"")
    print("wrk.path = \"/api/predictions\"")
    print("wrk.headers[\"Content-Type\"] = \"application/json\"")
    print("EOF")
    print()
    print("cat > /opt/wrk-tests/scripts/matches.lua << 'EOF'")
    print("wrk.method = \"GET\"")
    print("wrk.path = \"/api/matches\"")
    print("wrk.headers[\"Content-Type\"] = \"application/json\"")
    print("EOF")
    print()
    print("cat > /opt/wrk-tests/scripts/analysis.lua << 'EOF'")
    print("wrk.method = \"GET\"")
    print("wrk.path = \"/api/analysis\"")
    print("wrk.headers[\"Content-Type\"] = \"application/json\"")
    print("EOF")
    print()
    print("cat > /opt/wrk-tests/scripts/config.lua << 'EOF'")
    print("wrk.method = \"GET\"")
    print("wrk.path = \"/config\"")
    print("wrk.headers[\"Content-Type\"] = \"application/json\"")
    print("EOF")
    print()
    print("cat > /opt/wrk-tests/scripts/logs.lua << 'EOF'")
    print("wrk.method = \"GET\"")
    print("wrk.path = \"/logs\"")
    print("wrk.headers[\"Content-Type\"] = \"application/json\"")
    print("EOF")
    print()
    print("# 7. Tornar script executável")
    print("chmod +x /opt/wrk-tests/run_wrk_test.sh")
    print()
    print("# 8. Executar teste de carga")
    print("cd /opt/wrk-tests")
    print("./run_wrk_test.sh")
    
    print("\n📊 ETAPA 6: CONFIGURAR MONITORAMENTO DE TESTES")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Criar diretório para monitoramento")
    print("mkdir -p /opt/load-testing-monitoring")
    print("cd /opt/load-testing-monitoring")
    print()
    print("# 2. Criar script de monitoramento")
    print("cat > /opt/load-testing-monitoring/monitor_load_tests.sh << 'EOF'")
    print("#!/bin/bash")
    print("echo \"📊 MARABET AI - MONITORAMENTO DE TESTES DE CARGA\"")
    print("echo \"================================================\"")
    print("echo \"📅 Data/Hora: $(date)\"")
    print("echo \"\"")
    print()
    print("# Verificar status dos serviços")
    print("echo \"🔍 Verificando status dos serviços...\"")
    print("sudo systemctl status prometheus grafana-server alertmanager nginx")
    print("echo \"\"")
    print()
    print("# Verificar métricas do Prometheus")
    print("echo \"📈 Verificando métricas do Prometheus...\"")
    print("curl -s http://localhost:9090/api/v1/query?query=up | jq .")
    print("echo \"\"")
    print()
    print("# Verificar dashboards do Grafana")
    print("echo \"📊 Verificando dashboards do Grafana...\"")
    print("curl -s http://admin:admin123@localhost:3000/api/dashboards | jq .")
    print("echo \"\"")
    print()
    print("# Verificar alertas do Alertmanager")
    print("echo \"🔔 Verificando alertas do Alertmanager...\"")
    print("curl -s http://localhost:9093/api/v1/alerts | jq .")
    print("echo \"\"")
    print()
    print("# Verificar logs dos serviços")
    print("echo \"📝 Verificando logs dos serviços...\"")
    print("sudo journalctl -u prometheus --since \"1 hour ago\" | tail -20")
    print("sudo journalctl -u grafana-server --since \"1 hour ago\" | tail -20")
    print("sudo journalctl -u alertmanager --since \"1 hour ago\" | tail -20")
    print("echo \"\"")
    print()
    print("# Verificar recursos do sistema")
    print("echo \"💻 Verificando recursos do sistema...\"")
    print("htop -n 1")
    print("df -h")
    print("free -h")
    print("echo \"\"")
    print()
    print("# Verificar portas abertas")
    print("echo \"🌐 Verificando portas abertas...\"")
    print("sudo netstat -tulpn | grep -E ':(3000|9090|9093|8080|9100|9121|9187)'")
    print("echo \"\"")
    print()
    print("echo \"✅ Monitoramento concluído!\"")
    print("EOF")
    print()
    print("# 3. Tornar script executável")
    print("chmod +x /opt/load-testing-monitoring/monitor_load_tests.sh")
    print()
    print("# 4. Executar monitoramento")
    print("cd /opt/load-testing-monitoring")
    print("./monitor_load_tests.sh")
    print()
    print("# 5. Configurar cron para monitoramento automático")
    print("echo \"0 */6 * * * /opt/load-testing-monitoring/monitor_load_tests.sh >> /var/log/load-testing-monitoring.log 2>&1\" | sudo crontab -")
    print()
    print("# 6. Verificar cron jobs")
    print("sudo crontab -l")
    
    print("\n🎯 COMANDOS DE VERIFICAÇÃO DE TESTES DE CARGA:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Verificar status dos testes")
    print("ps aux | grep -E '(locust|jmeter|artillery|k6|wrk)'")
    print()
    print("# Verificar relatórios gerados")
    print("ls -la /opt/load-testing/reports/")
    print("ls -la /opt/jmeter/reports/")
    print("ls -la /opt/artillery-tests/reports/")
    print("ls -la /opt/k6-tests/reports/")
    print("ls -la /opt/wrk-tests/reports/")
    print()
    print("# Verificar logs dos testes")
    print("tail -f /var/log/load-testing-monitoring.log")
    print()
    print("# Verificar métricas do Prometheus")
    print("curl http://localhost:9090/api/v1/targets")
    print("curl http://localhost:9090/api/v1/query?query=up")
    print()
    print("# Verificar dashboards do Grafana")
    print("curl http://admin:admin123@localhost:3000/api/dashboards")
    print()
    print("# Verificar alertas do Alertmanager")
    print("curl http://localhost:9093/api/v1/alerts")
    print()
    print("# Verificar configuração do Nginx")
    print("sudo nginx -t")
    print("sudo systemctl status nginx")
    print()
    print("# Verificar SSL")
    print("curl -I https://marabet.com/health")
    print("curl -I https://marabet.com/api/predictions")
    
    print("\n🚀 COMANDOS DE IMPLEMENTAÇÃO RÁPIDA:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Implementar Locust")
    print("sudo apt update && sudo apt install -y python3-pip && pip3 install locust && mkdir -p /opt/load-testing && cd /opt/load-testing")
    print()
    print("# Implementar JMeter")
    print("sudo apt install -y openjdk-11-jdk && cd /opt && wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.2.tgz && tar -xzf apache-jmeter-5.6.2.tgz && sudo mv apache-jmeter-5.6.2 jmeter")
    print()
    print("# Implementar Artillery")
    print("curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - && sudo apt-get install -y nodejs && sudo npm install -g artillery && mkdir -p /opt/artillery-tests && cd /opt/artillery-tests")
    print()
    print("# Implementar K6")
    print("sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69 && echo \"deb https://dl.k6.io/deb stable main\" | sudo tee /etc/apt/sources.list.d/k6.list && sudo apt update && sudo apt install k6 && mkdir -p /opt/k6-tests && cd /opt/k6-tests")
    print()
    print("# Implementar WRK")
    print("sudo apt install -y build-essential libssl-dev git && cd /opt && git clone https://github.com/wg/wrk.git && cd wrk && make && sudo cp wrk /usr/local/bin/ && mkdir -p /opt/wrk-tests && cd /opt/wrk-tests")
    print()
    print("# Implementar Monitoramento")
    print("mkdir -p /opt/load-testing-monitoring && echo \"0 */6 * * * /opt/load-testing-monitoring/monitor_load_tests.sh >> /var/log/load-testing-monitoring.log 2>&1\" | sudo crontab -")
    print()
    print("# Implementar Testes de Carga Completo")
    print("cd /opt/load-testing && ./run_locust_test.sh && cd /opt/jmeter && ./run_jmeter_test.sh && cd /opt/artillery-tests && ./run_artillery_test.sh && cd /opt/k6-tests && ./run_k6_test.sh && cd /opt/wrk-tests && ./run_wrk_test.sh")
    print()
    print("# Implementar Verificação Final")
    print("ps aux | grep -E '(locust|jmeter|artillery|k6|wrk)' && ls -la /opt/*/reports/ && curl http://localhost:9090/api/v1/targets && curl http://admin:admin123@localhost:3000/api/dashboards")
    
    print("\n🎉 IMPLEMENTAÇÃO DE TESTES DE CARGA CONSOLIDADA COM SUCESSO!")
    print("=" * 80)
    
    return True

def main():
    print("🚀 Iniciando implementação de testes de carga...")
    
    # Criar implementação de testes de carga
    success = create_load_testing_implementation()
    
    if success:
        print("\n🎯 IMPLEMENTAÇÃO DE TESTES DE CARGA CONSOLIDADA COM SUCESSO!")
        print("Sistema completo e funcionando!")
    else:
        print("\n❌ Falha na implementação de testes de carga")
        print("Verifique os logs acima para mais detalhes")

if __name__ == "__main__":
    main()
