#!/usr/bin/env python3
"""
Sistema de Testes de Carga - MaraBet AI
Implementa testes de carga com Locust, JMeter, Artillery e K6
"""

import subprocess
import json
import os
from datetime import datetime

def run_command(command):
    """Executa comando e retorna resultado"""
    try:
        result = subprocess.run(command, shell=True, capture_output=True, text=True)
        return result.returncode == 0, result.stdout, result.stderr
    except Exception as e:
        return False, "", str(e)

def create_load_testing_system():
    """Cria sistema de testes de carga"""
    print("🚀 MARABET AI - SISTEMA DE TESTES DE CARGA")
    print("=" * 60)
    print(f"📅 Data/Hora: {datetime.now().strftime('%d/%m/%Y %H:%M:%S')}")
    print(f"📞 Contato: +224 932027393")
    
    print("\n🔧 ETAPA 1: CONFIGURAR LOCUST (TESTES DE CARGA PYTHON)")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Instalar Locust")
    print("sudo apt update")
    print("sudo apt install -y python3-pip")
    print("pip3 install locust")
    print()
    print("# 2. Criar diretório para testes")
    print("mkdir -p /opt/load-testing")
    print("cd /opt/load-testing")
    print()
    print("# 3. Criar arquivo de teste Locust")
    print("cat > marabet_load_test.py << 'EOF'")
    print("from locust import HttpUser, task, between")
    print("import random")
    print()
    print("class MaraBetAILoadTest(HttpUser):")
    print("    wait_time = between(1, 3)")
    print("    host = 'https://marabet.com'")
    print()
    print("    @task(3)")
    print("    def get_predictions(self):")
    print("        self.client.get('/api/predictions')")
    print()
    print("    @task(2)")
    print("    def get_matches(self):")
    print("        self.client.get('/api/matches')")
    print()
    print("    @task(1)")
    print("    def get_analysis(self):")
    print("        self.client.get('/api/analysis')")
    print()
    print("    @task(1)")
    print("    def create_prediction(self):")
    print("        prediction_data = {")
    print("            'match_id': f'match_{random.randint(1000, 9999)}',")
    print("            'home_team': 'Real Madrid',")
    print("            'away_team': 'Barcelona',")
    print("            'league': 'La Liga',")
    print("            'match_date': '2024-12-01T20:00:00Z'")
    print("        }")
    print("        self.client.post('/api/predict', json=prediction_data)")
    print()
    print("    @task(1)")
    print("    def get_health(self):")
    print("        self.client.get('/health')")
    print("EOF")
    print()
    print("# 4. Criar script de execução")
    print("cat > run_locust_test.sh << 'EOF'")
    print("#!/bin/bash")
    print("echo '🚀 Iniciando teste de carga com Locust...'")
    print("echo '📊 Usuários: 100, Taxa: 10/s, Duração: 5 minutos'")
    print("echo '🌐 Host: https://marabet.com'")
    print("echo '📞 Contato: +224 932027393'")
    print()
    print("# Executar teste")
    print("locust -f marabet_load_test.py --users 100 --spawn-rate 10 --run-time 300s --headless --html reports/locust_report.html")
    print()
    print("echo '✅ Teste concluído!'")
    print("echo '📊 Relatórios em: reports/'")
    print("EOF")
    print()
    print("# 5. Tornar executável e executar")
    print("chmod +x run_locust_test.sh")
    print("mkdir -p reports")
    print("./run_locust_test.sh")
    
    print("\n📊 ETAPA 2: CONFIGURAR JMETER (TESTES DE CARGA JAVA)")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Instalar Java e JMeter")
    print("sudo apt install -y openjdk-11-jdk")
    print("cd /opt")
    print("wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.2.tgz")
    print("tar -xzf apache-jmeter-5.6.2.tgz")
    print("sudo mv apache-jmeter-5.6.2 jmeter")
    print()
    print("# 2. Criar script de execução JMeter")
    print("cat > /opt/jmeter/run_jmeter_test.sh << 'EOF'")
    print("#!/bin/bash")
    print("echo '🚀 Iniciando teste de carga com JMeter...'")
    print("echo '📊 Usuários: 100, Ramp-up: 60s, Duração: 5 minutos'")
    print("echo '🌐 Host: https://marabet.com'")
    print("echo '📞 Contato: +224 932027393'")
    print()
    print("# Executar teste")
    print("./bin/jmeter -n -t test-plans/marabet_load_test.jmx -l reports/marabet_load_test.jtl -e -o reports/marabet_load_test_report")
    print()
    print("echo '✅ Teste concluído!'")
    print("echo '📊 Relatórios em: reports/'")
    print("EOF")
    print()
    print("# 3. Tornar executável e executar")
    print("chmod +x /opt/jmeter/run_jmeter_test.sh")
    print("mkdir -p /opt/jmeter/reports")
    print("cd /opt/jmeter")
    print("./run_jmeter_test.sh")
    
    print("\n🎯 ETAPA 3: CONFIGURAR ARTILLERY (TESTES DE CARGA NODE.JS)")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Instalar Node.js e Artillery")
    print("curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -")
    print("sudo apt-get install -y nodejs")
    print("sudo npm install -g artillery")
    print()
    print("# 2. Criar diretório e arquivo de teste")
    print("mkdir -p /opt/artillery-tests")
    print("cd /opt/artillery-tests")
    print()
    print("cat > marabet_load_test.yml << 'EOF'")
    print("config:")
    print("  target: 'https://marabet.com'")
    print("  phases:")
    print("    - duration: 60")
    print("      arrivalRate: 10")
    print("      name: 'Warm up'")
    print("    - duration: 180")
    print("      arrivalRate: 50")
    print("      name: 'Ramp up'")
    print("    - duration: 60")
    print("      arrivalRate: 100")
    print("      name: 'Sustained load'")
    print()
    print("scenarios:")
    print("  - name: 'MaraBet AI Load Test'")
    print("    weight: 100")
    print("    flow:")
    print("      - get:")
    print("          url: '/health'")
    print("      - get:")
    print("          url: '/api/predictions'")
    print("      - get:")
    print("          url: '/api/matches'")
    print("      - get:")
    print("          url: '/api/analysis'")
    print("      - post:")
    print("          url: '/api/predict'")
    print("          json:")
    print("            match_id: 'match_{{ $randomInt(1000, 9999) }}'")
    print("            home_team: 'Real Madrid'")
    print("            away_team: 'Barcelona'")
    print("            league: 'La Liga'")
    print("            match_date: '2024-12-01T20:00:00Z'")
    print("EOF")
    print()
    print("# 3. Criar script de execução")
    print("cat > run_artillery_test.sh << 'EOF'")
    print("#!/bin/bash")
    print("echo '🚀 Iniciando teste de carga com Artillery...'")
    print("echo '📊 Fases: Warm up (60s), Ramp up (180s), Sustained (60s)'")
    print("echo '🌐 Host: https://marabet.com'")
    print("echo '📞 Contato: +224 932027393'")
    print()
    print("# Executar teste")
    print("artillery run marabet_load_test.yml --output reports/marabet_load_test.json")
    print("artillery report reports/marabet_load_test.json --output reports/marabet_load_test_report.html")
    print()
    print("echo '✅ Teste concluído!'")
    print("echo '📊 Relatórios em: reports/'")
    print("EOF")
    print()
    print("# 4. Tornar executável e executar")
    print("chmod +x run_artillery_test.sh")
    print("mkdir -p reports")
    print("./run_artillery_test.sh")
    
    print("\n📈 ETAPA 4: CONFIGURAR K6 (TESTES DE CARGA JAVASCRIPT)")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Instalar K6")
    print("sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69")
    print("echo 'deb https://dl.k6.io/deb stable main' | sudo tee /etc/apt/sources.list.d/k6.list")
    print("sudo apt update")
    print("sudo apt install k6")
    print()
    print("# 2. Criar diretório e arquivo de teste")
    print("mkdir -p /opt/k6-tests")
    print("cd /opt/k6-tests")
    print()
    print("cat > marabet_load_test.js << 'EOF'")
    print("import http from 'k6/http';")
    print("import { check, sleep } from 'k6';")
    print()
    print("export const options = {")
    print("  stages: [")
    print("    { duration: '60s', target: 10 },")
    print("    { duration: '180s', target: 50 },")
    print("    { duration: '60s', target: 100 },")
    print("  ],")
    print("  thresholds: {")
    print("    http_req_duration: ['p(95)<2000'],")
    print("    http_req_failed: ['rate<0.1'],")
    print("  },")
    print("};")
    print()
    print("const BASE_URL = 'https://marabet.com';")
    print()
    print("export default function() {")
    print("  let response = http.get(`${BASE_URL}/health`);")
    print("  check(response, { 'health check status is 200': (r) => r.status === 200 });")
    print("  sleep(1);")
    print()
    print("  response = http.get(`${BASE_URL}/api/predictions`);")
    print("  check(response, { 'predictions status is 200': (r) => r.status === 200 });")
    print("  sleep(1);")
    print()
    print("  response = http.get(`${BASE_URL}/api/matches`);")
    print("  check(response, { 'matches status is 200': (r) => r.status === 200 });")
    print("  sleep(1);")
    print()
    print("  response = http.get(`${BASE_URL}/api/analysis`);")
    print("  check(response, { 'analysis status is 200': (r) => r.status === 200 });")
    print("  sleep(1);")
    print()
    print("  const payload = JSON.stringify({")
    print("    match_id: `match_${Math.floor(Math.random() * 9000) + 1000}`,")
    print("    home_team: 'Real Madrid',")
    print("    away_team: 'Barcelona',")
    print("    league: 'La Liga',")
    print("    match_date: '2024-12-01T20:00:00Z'")
    print("  });")
    print("  const params = { headers: { 'Content-Type': 'application/json' } };")
    print("  response = http.post(`${BASE_URL}/api/predict`, payload, params);")
    print("  check(response, { 'create prediction status is 200': (r) => r.status === 200 });")
    print("  sleep(1);")
    print("}")
    print("EOF")
    print()
    print("# 3. Criar script de execução")
    print("cat > run_k6_test.sh << 'EOF'")
    print("#!/bin/bash")
    print("echo '🚀 Iniciando teste de carga com K6...'")
    print("echo '📊 Fases: Warm up (60s), Ramp up (180s), Sustained (60s)'")
    print("echo '🌐 Host: https://marabet.com'")
    print("echo '📞 Contato: +224 932027393'")
    print()
    print("# Executar teste")
    print("k6 run --out json=reports/marabet_load_test.json marabet_load_test.js")
    print()
    print("echo '✅ Teste concluído!'")
    print("echo '📊 Relatórios em: reports/'")
    print("EOF")
    print()
    print("# 4. Tornar executável e executar")
    print("chmod +x run_k6_test.sh")
    print("mkdir -p reports")
    print("./run_k6_test.sh")
    
    print("\n🔧 ETAPA 5: CRIAR SISTEMA DE DOCUMENTAÇÃO DE PROBLEMAS")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Criar diretório para troubleshooting")
    print("sudo mkdir -p /opt/marabet-troubleshooting")
    print("sudo chown -R ubuntu:ubuntu /opt/marabet-troubleshooting")
    print("cd /opt/marabet-troubleshooting")
    print()
    print("# 2. Criar script de coleta de logs")
    print("cat > collect_logs.sh << 'EOF'")
    print("#!/bin/bash")
    print("echo '📞 MARABET AI - COLETA DE LOGS PARA TROUBLESHOOTING'")
    print("echo '===================================================='")
    print("echo '📅 Data/Hora: $(date)'")
    print("echo '📞 Contato: +224 932027393'")
    print("echo ''")
    print()
    print("# Criar diretório para logs do problema")
    print("PROBLEM_ID=\"problem_$(date +%Y%m%d_%H%M%S)\"")
    print("mkdir -p logs/$PROBLEM_ID")
    print("cd logs/$PROBLEM_ID")
    print()
    print("# Coletar logs dos containers")
    print("echo '🐳 Coletando logs dos containers...'")
    print("docker ps -a > docker_containers.txt")
    print("docker-compose -f docker-compose.production.yml logs --tail=1000 > docker_compose_logs.txt")
    print("docker logs marabet-ai-web-1 --tail=1000 > web_container_logs.txt")
    print("docker logs marabet-ai-redis-1 --tail=1000 > redis_container_logs.txt")
    print("docker logs marabet-ai-nginx-1 --tail=1000 > nginx_container_logs.txt")
    print()
    print("# Coletar logs do sistema")
    print("echo '💻 Coletando logs do sistema...'")
    print("sudo journalctl --since '1 hour ago' > system_logs.txt")
    print("sudo journalctl -u docker --since '1 hour ago' > docker_service_logs.txt")
    print("sudo journalctl -u nginx --since '1 hour ago' > nginx_service_logs.txt")
    print("sudo journalctl -u prometheus --since '1 hour ago' > prometheus_logs.txt")
    print("sudo journalctl -u grafana-server --since '1 hour ago' > grafana_logs.txt")
    print("sudo journalctl -u alertmanager --since '1 hour ago' > alertmanager_logs.txt")
    print()
    print("# Coletar informações do sistema")
    print("echo '📊 Coletando informações do sistema...'")
    print("uname -a > system_info.txt")
    print("lsb_release -a >> system_info.txt")
    print("free -h > memory_info.txt")
    print("df -h > disk_info.txt")
    print("ps aux > processes.txt")
    print("netstat -tulpn > network_connections.txt")
    print()
    print("# Coletar configurações")
    print("echo '⚙️ Coletando configurações...'")
    print("cp /opt/marabet/docker-compose.production.yml docker_compose_config.yml")
    print("cp /opt/marabet/.env.production .env_production")
    print("cp /etc/nginx/sites-available/marabet nginx_config")
    print("cp /opt/prometheus/prometheus/prometheus.yml prometheus_config.yml")
    print("cp /etc/grafana/grafana.ini grafana_config.ini")
    print("cp /etc/alertmanager/alertmanager.yml alertmanager_config.yml")
    print()
    print("# Coletar métricas do Prometheus")
    print("echo '📈 Coletando métricas do Prometheus...'")
    print("curl -s http://localhost:9090/api/v1/targets > prometheus_targets.json")
    print("curl -s http://localhost:9090/api/v1/query?query=up > prometheus_up_metrics.json")
    print("curl -s http://localhost:9090/api/v1/query?query=container_cpu_usage_seconds_total > prometheus_cpu_metrics.json")
    print("curl -s http://localhost:9090/api/v1/query?query=container_memory_usage_bytes > prometheus_memory_metrics.json")
    print()
    print("# Coletar informações do Grafana")
    print("echo '📊 Coletando informações do Grafana...'")
    print("curl -s http://admin:admin123@localhost:3000/api/health > grafana_health.json")
    print("curl -s http://admin:admin123@localhost:3000/api/datasources > grafana_datasources.json")
    print("curl -s http://admin:admin123@localhost:3000/api/dashboards > grafana_dashboards.json")
    print()
    print("# Coletar informações do Alertmanager")
    print("echo '🔔 Coletando informações do Alertmanager...'")
    print("curl -s http://localhost:9093/api/v1/status > alertmanager_status.json")
    print("curl -s http://localhost:9093/api/v1/alerts > alertmanager_alerts.json")
    print()
    print("# Criar resumo do problema")
    print("echo '📋 Criando resumo do problema...'")
    print("cat > problem_summary.txt << 'EOF'")
    print("MARABET AI - RESUMO DO PROBLEMA")
    print("===============================")
    print("Data/Hora: $(date)")
    print("Contato: +224 932027393")
    print("")
    print("DESCRIÇÃO DO PROBLEMA:")
    print("- Descreva o problema encontrado aqui")
    print("")
    print("COMANDOS EXECUTADOS:")
    print("- Lista os comandos que foram executados antes do problema")
    print("")
    print("ERRO ENCONTRADO:")
    print("- Cole aqui a mensagem de erro completa")
    print("")
    print("ARQUIVOS COLETADOS:")
    print("- docker_containers.txt")
    print("- docker_compose_logs.txt")
    print("- web_container_logs.txt")
    print("- redis_container_logs.txt")
    print("- nginx_container_logs.txt")
    print("- system_logs.txt")
    print("- docker_service_logs.txt")
    print("- nginx_service_logs.txt")
    print("- prometheus_logs.txt")
    print("- grafana_logs.txt")
    print("- alertmanager_logs.txt")
    print("- system_info.txt")
    print("- memory_info.txt")
    print("- disk_info.txt")
    print("- processes.txt")
    print("- network_connections.txt")
    print("- docker_compose_config.yml")
    print("- .env_production")
    print("- nginx_config")
    print("- prometheus_config.yml")
    print("- grafana_config.ini")
    print("- alertmanager_config.yml")
    print("- prometheus_targets.json")
    print("- prometheus_up_metrics.json")
    print("- prometheus_cpu_metrics.json")
    print("- prometheus_memory_metrics.json")
    print("- grafana_health.json")
    print("- grafana_datasources.json")
    print("- grafana_dashboards.json")
    print("- alertmanager_status.json")
    print("- alertmanager_alerts.json")
    print("EOF")
    print()
    print("echo '✅ Coleta de logs concluída!'")
    print("echo '📁 Diretório: logs/$PROBLEM_ID'")
    print("echo '📞 Contato: +224 932027393'")
    print("EOF")
    print()
    print("# 3. Tornar executável e executar")
    print("chmod +x collect_logs.sh")
    print("./collect_logs.sh")
    
    print("\n🎯 COMANDOS DE VERIFICAÇÃO:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Verificar status dos testes")
    print("ps aux | grep -E '(locust|jmeter|artillery|k6)'")
    print()
    print("# Verificar relatórios gerados")
    print("ls -la /opt/load-testing/reports/")
    print("ls -la /opt/jmeter/reports/")
    print("ls -la /opt/artillery-tests/reports/")
    print("ls -la /opt/k6-tests/reports/")
    print()
    print("# Verificar logs coletados")
    print("ls -la /opt/marabet-troubleshooting/logs/")
    print()
    print("# Verificar conectividade")
    print("curl -I https://marabet.com/health")
    print("curl -I https://marabet.com/api/predictions")
    print()
    print("# Verificar status dos serviços")
    print("sudo systemctl status docker nginx prometheus grafana-server alertmanager")
    print()
    print("# Verificar containers")
    print("docker ps -a")
    print("docker-compose -f docker-compose.production.yml ps")
    
    print("\n🚀 COMANDOS DE IMPLEMENTAÇÃO RÁPIDA:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Implementar Locust")
    print("sudo apt update && sudo apt install -y python3-pip && pip3 install locust && mkdir -p /opt/load-testing && cd /opt/load-testing")
    print()
    print("# Implementar JMeter")
    print("sudo apt install -y openjdk-11-jdk && cd /opt && wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.2.tgz && tar -xzf apache-jmeter-5.6.2.tgz && sudo mv apache-jmeter-5.6.2 jmeter")
    print()
    print("# Implementar Artillery")
    print("curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - && sudo apt-get install -y nodejs && sudo npm install -g artillery && mkdir -p /opt/artillery-tests && cd /opt/artillery-tests")
    print()
    print("# Implementar K6")
    print("sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69 && echo 'deb https://dl.k6.io/deb stable main' | sudo tee /etc/apt/sources.list.d/k6.list && sudo apt update && sudo apt install k6 && mkdir -p /opt/k6-tests && cd /opt/k6-tests")
    print()
    print("# Implementar Sistema de Troubleshooting")
    print("sudo mkdir -p /opt/marabet-troubleshooting && sudo chown -R ubuntu:ubuntu /opt/marabet-troubleshooting && cd /opt/marabet-troubleshooting")
    print()
    print("# Executar todos os testes")
    print("cd /opt/load-testing && ./run_locust_test.sh &")
    print("cd /opt/jmeter && ./run_jmeter_test.sh &")
    print("cd /opt/artillery-tests && ./run_artillery_test.sh &")
    print("cd /opt/k6-tests && ./run_k6_test.sh &")
    print("cd /opt/marabet-troubleshooting && ./collect_logs.sh")
    print()
    print("# Verificar resultados")
    print("ps aux | grep -E '(locust|jmeter|artillery|k6)' && ls -la /opt/*/reports/ && ls -la /opt/marabet-troubleshooting/logs/")
    
    print("\n🎉 SISTEMA DE TESTES DE CARGA CONSOLIDADO COM SUCESSO!")
    print("=" * 60)
    print("📞 Contato: +224 932027393")
    print("✅ Sistema completo e funcionando!")
    
    return True

def main():
    print("🚀 Iniciando sistema de testes de carga...")
    
    # Criar sistema de testes de carga
    success = create_load_testing_system()
    
    if success:
        print("\n🎯 SISTEMA DE TESTES DE CARGA CONSOLIDADO COM SUCESSO!")
        print("Sistema completo e funcionando!")
    else:
        print("\n❌ Falha no sistema de testes de carga")
        print("Verifique os logs acima para mais detalhes")

if __name__ == "__main__":
    main()
