#!/usr/bin/env python3
"""
Script de Integração de Monitoramento - MaraBet AI
Integra Grafana e Prometheus para monitoramento avançado
"""

import subprocess
import json
import os
from datetime import datetime

def run_aws_command(command, return_text=False):
    """Executa comando AWS CLI e retorna resultado"""
    try:
        result = subprocess.run(command, shell=True, capture_output=True, text=True)
        if result.returncode == 0:
            if return_text:
                return result.stdout.strip()
            else:
                return json.loads(result.stdout) if result.stdout.strip() else {}
        else:
            print(f"❌ Erro no comando: {command}")
            print(f"Erro: {result.stderr}")
            return None
    except json.JSONDecodeError:
        print(f"❌ Erro de decodificação JSON para o comando: {command}")
        print(f"Saída: {result.stdout}")
        print(f"Erro: {result.stderr}")
        return None
    except Exception as e:
        print(f"❌ Exceção no comando: {command}")
        print(f"Erro: {e}")
        return None

def load_config():
    """Carrega configurações existentes do arquivo JSON."""
    config_file = 'aws_infrastructure_config.json'
    if os.path.exists(config_file):
        with open(config_file, 'r') as f:
            return json.load(f)
    return {}

def save_config(config):
    """Salva configurações no arquivo JSON."""
    config_file = 'aws_infrastructure_config.json'
    with open(config_file, 'w') as f:
        json.dump(config, f, indent=2)

def create_monitoring_integration():
    """Cria integração de monitoramento com Grafana e Prometheus"""
    print("📊 MARABET AI - INTEGRAÇÃO DE MONITORAMENTO GRAFANA E PROMETHEUS")
    print("=" * 80)
    print(f"📅 Data/Hora: {datetime.now().strftime('%d/%m/%Y %H:%M:%S')}")
    
    # Carregar configuração existente
    config = load_config()
    
    print("\n🔧 ETAPA 1: CONFIGURAR PROMETHEUS")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Criar diretório para Prometheus")
    print("sudo mkdir -p /opt/prometheus")
    print("sudo chown -R ubuntu:ubuntu /opt/prometheus")
    print()
    print("# 2. Baixar Prometheus")
    print("cd /opt/prometheus")
    print("wget https://github.com/prometheus/prometheus/releases/download/v2.45.0/prometheus-2.45.0.linux-amd64.tar.gz")
    print("tar -xzf prometheus-2.45.0.linux-amd64.tar.gz")
    print("mv prometheus-2.45.0.linux-amd64 prometheus")
    print()
    print("# 3. Criar arquivo de configuração do Prometheus")
    print("cat > /opt/prometheus/prometheus/prometheus.yml << 'EOF'")
    print("global:")
    print("  scrape_interval: 15s")
    print("  evaluation_interval: 15s")
    print()
    print("rule_files:")
    print("  - 'rules/*.yml'")
    print()
    print("scrape_configs:")
    print("  - job_name: 'prometheus'")
    print("    static_configs:")
    print("      - targets: ['localhost:9090']")
    print()
    print("  - job_name: 'marabet-ai'")
    print("    static_configs:")
    print("      - targets: ['localhost:8000']")
    print("    metrics_path: '/metrics'")
    print("    scrape_interval: 5s")
    print()
    print("  - job_name: 'node-exporter'")
    print("    static_configs:")
    print("      - targets: ['localhost:9100']")
    print()
    print("  - job_name: 'cadvisor'")
    print("    static_configs:")
    print("      - targets: ['localhost:8080']")
    print()
    print("  - job_name: 'redis-exporter'")
    print("    static_configs:")
    print("      - targets: ['localhost:9121']")
    print()
    print("  - job_name: 'postgres-exporter'")
    print("    static_configs:")
    print("      - targets: ['localhost:9187']")
    print("EOF")
    print()
    print("# 4. Criar diretório para regras")
    print("mkdir -p /opt/prometheus/prometheus/rules")
    print()
    print("# 5. Criar arquivo de regras do Prometheus")
    print("cat > /opt/prometheus/prometheus/rules/marabet-rules.yml << 'EOF'")
    print("groups:")
    print("- name: marabet-ai")
    print("  rules:")
    print("  - alert: HighCPUUsage")
    print("    expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100) > 80")
    print("    for: 5m")
    print("    labels:")
    print("      severity: warning")
    print("    annotations:")
    print("      summary: \"High CPU usage detected\"")
    print("      description: \"CPU usage is above 80% for more than 5 minutes\"")
    print()
    print("  - alert: HighMemoryUsage")
    print("    expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85")
    print("    for: 5m")
    print("    labels:")
    print("      severity: warning")
    print("    annotations:")
    print("      summary: \"High memory usage detected\"")
    print("      description: \"Memory usage is above 85% for more than 5 minutes\"")
    print()
    print("  - alert: DiskSpaceLow")
    print("    expr: (1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)) * 100 > 90")
    print("    for: 5m")
    print("    labels:")
    print("      severity: critical")
    print("    annotations:")
    print("      summary: \"Disk space is low\"")
    print("      description: \"Disk space is above 90% for more than 5 minutes\"")
    print()
    print("  - alert: ServiceDown")
    print("    expr: up == 0")
    print("    for: 1m")
    print("    labels:")
    print("      severity: critical")
    print("    annotations:")
    print("      summary: \"Service is down\"")
    print("      description: \"Service {{ $labels.instance }} is down\"")
    print("EOF")
    print()
    print("# 6. Criar systemd service para Prometheus")
    print("sudo cat > /etc/systemd/system/prometheus.service << 'EOF'")
    print("[Unit]")
    print("Description=Prometheus")
    print("After=network.target")
    print()
    print("[Service]")
    print("Type=simple")
    print("User=ubuntu")
    print("Group=ubuntu")
    print("ExecStart=/opt/prometheus/prometheus/prometheus --config.file=/opt/prometheus/prometheus/prometheus.yml --storage.tsdb.path=/opt/prometheus/prometheus/data --web.console.templates=/opt/prometheus/prometheus/consoles --web.console.libraries=/opt/prometheus/prometheus/console_libraries --web.listen-address=0.0.0.0:9090")
    print("Restart=always")
    print("RestartSec=10")
    print()
    print("[Install]")
    print("WantedBy=multi-user.target")
    print("EOF")
    print()
    print("# 7. Iniciar e habilitar Prometheus")
    print("sudo systemctl daemon-reload")
    print("sudo systemctl enable prometheus")
    print("sudo systemctl start prometheus")
    print("sudo systemctl status prometheus")
    
    print("\n📊 ETAPA 2: CONFIGURAR GRAFANA")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Instalar dependências")
    print("sudo apt update")
    print("sudo apt install -y software-properties-common")
    print()
    print("# 2. Adicionar repositório do Grafana")
    print("wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -")
    print("echo \"deb https://packages.grafana.com/oss/deb stable main\" | sudo tee -a /etc/apt/sources.list.d/grafana.list")
    print()
    print("# 3. Instalar Grafana")
    print("sudo apt update")
    print("sudo apt install -y grafana")
    print()
    print("# 4. Configurar Grafana")
    print("sudo systemctl enable grafana-server")
    print("sudo systemctl start grafana-server")
    print("sudo systemctl status grafana-server")
    print()
    print("# 5. Configurar Nginx para Grafana")
    print("sudo cat > /etc/nginx/sites-available/grafana << 'EOF'")
    print("server {")
    print("    listen 80;")
    print("    server_name grafana.marabet.com;")
    print()
    print("    location / {")
    print("        proxy_pass http://localhost:3000;")
    print("        proxy_set_header Host $host;")
    print("        proxy_set_header X-Real-IP $remote_addr;")
    print("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;")
    print("        proxy_set_header X-Forwarded-Proto $scheme;")
    print("    }")
    print("}")
    print("EOF")
    print()
    print("# 6. Habilitar site do Grafana")
    print("sudo ln -s /etc/nginx/sites-available/grafana /etc/nginx/sites-enabled/")
    print("sudo nginx -t")
    print("sudo systemctl reload nginx")
    print()
    print("# 7. Configurar SSL para Grafana")
    print("sudo certbot --nginx -d grafana.marabet.com")
    print()
    print("# 8. Configurar usuário admin do Grafana")
    print("sudo grafana-cli admin reset-admin-password admin123")
    
    print("\n🔌 ETAPA 3: CONFIGURAR EXPORTERS")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Instalar Node Exporter")
    print("cd /opt")
    print("wget https://github.com/prometheus/node_exporter/releases/download/v1.6.1/node_exporter-1.6.1.linux-amd64.tar.gz")
    print("tar -xzf node_exporter-1.6.1.linux-amd64.tar.gz")
    print("sudo mv node_exporter-1.6.1.linux-amd64/node_exporter /usr/local/bin/")
    print()
    print("# 2. Criar systemd service para Node Exporter")
    print("sudo cat > /etc/systemd/system/node_exporter.service << 'EOF'")
    print("[Unit]")
    print("Description=Node Exporter")
    print("After=network.target")
    print()
    print("[Service]")
    print("Type=simple")
    print("User=ubuntu")
    print("Group=ubuntu")
    print("ExecStart=/usr/local/bin/node_exporter")
    print("Restart=always")
    print("RestartSec=10")
    print()
    print("[Install]")
    print("WantedBy=multi-user.target")
    print("EOF")
    print()
    print("# 3. Iniciar Node Exporter")
    print("sudo systemctl daemon-reload")
    print("sudo systemctl enable node_exporter")
    print("sudo systemctl start node_exporter")
    print("sudo systemctl status node_exporter")
    print()
    print("# 4. Instalar cAdvisor")
    print("sudo docker run -d --name=cadvisor --restart=always -p 8080:8080 -v /:/rootfs:ro -v /var/run:/var/run:ro -v /sys:/sys:ro -v /var/lib/docker/:/var/lib/docker:ro -v /dev/disk/:/dev/disk:ro gcr.io/cadvisor/cadvisor:latest")
    print()
    print("# 5. Instalar Redis Exporter")
    print("cd /opt")
    print("wget https://github.com/oliver006/redis_exporter/releases/download/v1.55.0/redis_exporter-1.55.0.linux-amd64.tar.gz")
    print("tar -xzf redis_exporter-1.55.0.linux-amd64.tar.gz")
    print("sudo mv redis_exporter-1.55.0.linux-amd64/redis_exporter /usr/local/bin/")
    print()
    print("# 6. Criar systemd service para Redis Exporter")
    print("sudo cat > /etc/systemd/system/redis_exporter.service << 'EOF'")
    print("[Unit]")
    print("Description=Redis Exporter")
    print("After=network.target")
    print()
    print("[Service]")
    print("Type=simple")
    print("User=ubuntu")
    print("Group=ubuntu")
    print("ExecStart=/usr/local/bin/redis_exporter --redis.addr=marabet-redis.ve5qk7.0001.use1.cache.amazonaws.com:6379")
    print("Restart=always")
    print("RestartSec=10")
    print()
    print("[Install]")
    print("WantedBy=multi-user.target")
    print("EOF")
    print()
    print("# 7. Iniciar Redis Exporter")
    print("sudo systemctl daemon-reload")
    print("sudo systemctl enable redis_exporter")
    print("sudo systemctl start redis_exporter")
    print("sudo systemctl status redis_exporter")
    print()
    print("# 8. Instalar PostgreSQL Exporter")
    print("cd /opt")
    print("wget https://github.com/prometheus-community/postgres_exporter/releases/download/v0.13.2/postgres_exporter-0.13.2.linux-amd64.tar.gz")
    print("tar -xzf postgres_exporter-0.13.2.linux-amd64.tar.gz")
    print("sudo mv postgres_exporter-0.13.2.linux-amd64/postgres_exporter /usr/local/bin/")
    
    print("\n📈 ETAPA 4: CONFIGURAR DASHBOARDS DO GRAFANA")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Instalar plugins do Grafana")
    print("sudo grafana-cli plugins install grafana-piechart-panel")
    print("sudo grafana-cli plugins install grafana-worldmap-panel")
    print("sudo grafana-cli plugins install grafana-clock-panel")
    print("sudo grafana-cli plugins install grafana-simple-json-datasource")
    print("sudo systemctl restart grafana-server")
    print()
    print("# 2. Criar datasource do Prometheus")
    print("curl -X POST http://admin:admin123@localhost:3000/api/datasources \\")
    print("  -H 'Content-Type: application/json' \\")
    print("  -d '{\"name\":\"Prometheus\",\"type\":\"prometheus\",\"url\":\"http://localhost:9090\",\"access\":\"proxy\",\"isDefault\":true}'")
    print()
    print("# 3. Criar dashboard de sistema")
    print("curl -X POST http://admin:admin123@localhost:3000/api/dashboards/db \\")
    print("  -H 'Content-Type: application/json' \\")
    print("  -d @/opt/grafana-dashboards/system-dashboard.json")
    print()
    print("# 4. Criar dashboard de aplicação")
    print("curl -X POST http://admin:admin123@localhost:3000/api/dashboards/db \\")
    print("  -H 'Content-Type: application/json' \\")
    print("  -d @/opt/grafana-dashboards/application-dashboard.json")
    print()
    print("# 5. Criar dashboard de banco de dados")
    print("curl -X POST http://admin:admin123@localhost:3000/api/dashboards/db \\")
    print("  -H 'Content-Type: application/json' \\")
    print("  -d @/opt/grafana-dashboards/database-dashboard.json")
    print()
    print("# 6. Criar dashboard de Redis")
    print("curl -X POST http://admin:admin123@localhost:3000/api/dashboards/db \\")
    print("  -H 'Content-Type: application/json' \\")
    print("  -d @/opt/grafana-dashboards/redis-dashboard.json")
    print()
    print("# 7. Criar dashboard de Docker")
    print("curl -X POST http://admin:admin123@localhost:3000/api/dashboards/db \\")
    print("  -H 'Content-Type: application/json' \\")
    print("  -d @/opt/grafana-dashboards/docker-dashboard.json")
    print()
    print("# 8. Criar dashboard de alertas")
    print("curl -X POST http://admin:admin123@localhost:3000/api/dashboards/db \\")
    print("  -H 'Content-Type: application/json' \\")
    print("  -d @/opt/grafana-dashboards/alerts-dashboard.json")
    
    print("\n🔔 ETAPA 5: CONFIGURAR ALERTAS")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Instalar Alertmanager")
    print("cd /opt")
    print("wget https://github.com/prometheus/alertmanager/releases/download/v0.25.0/alertmanager-0.25.0.linux-amd64.tar.gz")
    print("tar -xzf alertmanager-0.25.0.linux-amd64.tar.gz")
    print("sudo mv alertmanager-0.25.0.linux-amd64/alertmanager /usr/local/bin/")
    print("sudo mv alertmanager-0.25.0.linux-amd64/amtool /usr/local/bin/")
    print()
    print("# 2. Criar configuração do Alertmanager")
    print("sudo mkdir -p /etc/alertmanager")
    print("sudo cat > /etc/alertmanager/alertmanager.yml << 'EOF'")
    print("global:")
    print("  smtp_smarthost: 'localhost:587'")
    print("  smtp_from: 'alerts@marabet.com'")
    print()
    print("route:")
    print("  group_by: ['alertname']")
    print("  group_wait: 10s")
    print("  group_interval: 10s")
    print("  repeat_interval: 1h")
    print("  receiver: 'web.hook'")
    print()
    print("receivers:")
    print("- name: 'web.hook'")
    print("  webhook_configs:")
    print("  - url: 'http://localhost:5001/'")
    print("    send_resolved: true")
    print()
    print("- name: 'email'")
    print("  email_configs:")
    print("  - to: 'admin@marabet.com'")
    print("    subject: 'MaraBet AI Alert: {{ .GroupLabels.alertname }}'")
    print("    body: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'")
    print()
    print("- name: 'telegram'")
    print("  webhook_configs:")
    print("  - url: 'https://api.telegram.org/bot<TOKEN>/sendMessage'")
    print("    send_resolved: true")
    print("EOF")
    print()
    print("# 3. Criar systemd service para Alertmanager")
    print("sudo cat > /etc/systemd/system/alertmanager.service << 'EOF'")
    print("[Unit]")
    print("Description=Alertmanager")
    print("After=network.target")
    print()
    print("[Service]")
    print("Type=simple")
    print("User=ubuntu")
    print("Group=ubuntu")
    print("ExecStart=/usr/local/bin/alertmanager --config.file=/etc/alertmanager/alertmanager.yml --storage.path=/opt/alertmanager/data")
    print("Restart=always")
    print("RestartSec=10")
    print()
    print("[Install]")
    print("WantedBy=multi-user.target")
    print("EOF")
    print()
    print("# 4. Iniciar Alertmanager")
    print("sudo systemctl daemon-reload")
    print("sudo systemctl enable alertmanager")
    print("sudo systemctl start alertmanager")
    print("sudo systemctl status alertmanager")
    print()
    print("# 5. Configurar Nginx para Alertmanager")
    print("sudo cat > /etc/nginx/sites-available/alertmanager << 'EOF'")
    print("server {")
    print("    listen 80;")
    print("    server_name alerts.marabet.com;")
    print()
    print("    location / {")
    print("        proxy_pass http://localhost:9093;")
    print("        proxy_set_header Host $host;")
    print("        proxy_set_header X-Real-IP $remote_addr;")
    print("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;")
    print("        proxy_set_header X-Forwarded-Proto $scheme;")
    print("    }")
    print("}")
    print("EOF")
    print()
    print("# 6. Habilitar site do Alertmanager")
    print("sudo ln -s /etc/nginx/sites-available/alertmanager /etc/nginx/sites-enabled/")
    print("sudo nginx -t")
    print("sudo systemctl reload nginx")
    print()
    print("# 7. Configurar SSL para Alertmanager")
    print("sudo certbot --nginx -d alerts.marabet.com")
    print()
    print("# 8. Atualizar configuração do Prometheus para Alertmanager")
    print("sudo cat >> /opt/prometheus/prometheus/prometheus.yml << 'EOF'")
    print("alerting:")
    print("  alertmanagers:")
    print("    - static_configs:")
    print("        - targets:")
    print("          - localhost:9093")
    print("EOF")
    print("sudo systemctl restart prometheus")
    
    print("\n🌐 ETAPA 6: CONFIGURAR NGINX E SSL")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Configurar Nginx para Prometheus")
    print("sudo cat > /etc/nginx/sites-available/prometheus << 'EOF'")
    print("server {")
    print("    listen 80;")
    print("    server_name prometheus.marabet.com;")
    print()
    print("    location / {")
    print("        proxy_pass http://localhost:9090;")
    print("        proxy_set_header Host $host;")
    print("        proxy_set_header X-Real-IP $remote_addr;")
    print("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;")
    print("        proxy_set_header X-Forwarded-Proto $scheme;")
    print("    }")
    print("}")
    print("EOF")
    print()
    print("# 2. Habilitar site do Prometheus")
    print("sudo ln -s /etc/nginx/sites-available/prometheus /etc/nginx/sites-enabled/")
    print("sudo nginx -t")
    print("sudo systemctl reload nginx")
    print()
    print("# 3. Configurar SSL para Prometheus")
    print("sudo certbot --nginx -d prometheus.marabet.com")
    print()
    print("# 4. Configurar SSL para Grafana")
    print("sudo certbot --nginx -d grafana.marabet.com")
    print()
    print("# 5. Configurar SSL para Alertmanager")
    print("sudo certbot --nginx -d alerts.marabet.com")
    print()
    print("# 6. Verificar configuração do Nginx")
    print("sudo nginx -t")
    print("sudo systemctl reload nginx")
    print()
    print("# 7. Verificar status dos serviços")
    print("sudo systemctl status prometheus grafana-server alertmanager nginx")
    print()
    print("# 8. Verificar portas abertas")
    print("sudo netstat -tulpn | grep -E ':(3000|9090|9093|8080|9100|9121|9187)'")
    
    print("\n📊 ETAPA 7: CONFIGURAR DASHBOARDS PERSONALIZADOS")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Criar diretório para dashboards")
    print("sudo mkdir -p /opt/grafana-dashboards")
    print("sudo chown -R ubuntu:ubuntu /opt/grafana-dashboards")
    print()
    print("# 2. Criar dashboard de sistema")
    print("cat > /opt/grafana-dashboards/system-dashboard.json << 'EOF'")
    print("{")
    print("  \"dashboard\": {")
    print("    \"id\": null,")
    print("    \"title\": \"MaraBet AI - System Dashboard\",")
    print("    \"tags\": [\"marabet\", \"system\"],")
    print("    \"style\": \"dark\",")
    print("    \"timezone\": \"browser\",")
    print("    \"panels\": [")
    print("      {")
    print("        \"id\": 1,")
    print("        \"title\": \"CPU Usage\",")
    print("        \"type\": \"graph\",")
    print("        \"targets\": [")
    print("          {")
    print("            \"expr\": \"100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\\\"idle\\\"}[5m])) * 100)\",")
    print("            \"legendFormat\": \"CPU Usage %\"")
    print("          }")
    print("        ],")
    print("        \"yAxes\": [")
    print("          {")
    print("            \"label\": \"Percentage\",")
    print("            \"min\": 0,")
    print("            \"max\": 100")
    print("          }")
    print("        ]")
    print("      }")
    print("    ]")
    print("  }")
    print("}")
    print("EOF")
    print()
    print("# 3. Criar dashboard de aplicação")
    print("cat > /opt/grafana-dashboards/application-dashboard.json << 'EOF'")
    print("{")
    print("  \"dashboard\": {")
    print("    \"id\": null,")
    print("    \"title\": \"MaraBet AI - Application Dashboard\",")
    print("    \"tags\": [\"marabet\", \"application\"],")
    print("    \"style\": \"dark\",")
    print("    \"timezone\": \"browser\",")
    print("    \"panels\": [")
    print("      {")
    print("        \"id\": 1,")
    print("        \"title\": \"Request Rate\",")
    print("        \"type\": \"graph\",")
    print("        \"targets\": [")
    print("          {")
    print("            \"expr\": \"rate(http_requests_total[5m])\",")
    print("            \"legendFormat\": \"Requests/sec\"")
    print("          }")
    print("        ]")
    print("      }")
    print("    ]")
    print("  }")
    print("}")
    print("EOF")
    print()
    print("# 4. Criar dashboard de banco de dados")
    print("cat > /opt/grafana-dashboards/database-dashboard.json << 'EOF'")
    print("{")
    print("  \"dashboard\": {")
    print("    \"id\": null,")
    print("    \"title\": \"MaraBet AI - Database Dashboard\",")
    print("    \"tags\": [\"marabet\", \"database\"],")
    print("    \"style\": \"dark\",")
    print("    \"timezone\": \"browser\",")
    print("    \"panels\": [")
    print("      {")
    print("        \"id\": 1,")
    print("        \"title\": \"PostgreSQL Connections\",")
    print("        \"type\": \"graph\",")
    print("        \"targets\": [")
    print("          {")
    print("            \"expr\": \"pg_stat_database_numbackends\",")
    print("            \"legendFormat\": \"Active Connections\"")
    print("          }")
    print("        ]")
    print("      }")
    print("    ]")
    print("  }")
    print("}")
    print("EOF")
    print()
    print("# 5. Criar dashboard de Redis")
    print("cat > /opt/grafana-dashboards/redis-dashboard.json << 'EOF'")
    print("{")
    print("  \"dashboard\": {")
    print("    \"id\": null,")
    print("    \"title\": \"MaraBet AI - Redis Dashboard\",")
    print("    \"tags\": [\"marabet\", \"redis\"],")
    print("    \"style\": \"dark\",")
    print("    \"timezone\": \"browser\",")
    print("    \"panels\": [")
    print("      {")
    print("        \"id\": 1,")
    print("        \"title\": \"Redis Memory Usage\",")
    print("        \"type\": \"graph\",")
    print("        \"targets\": [")
    print("          {")
    print("            \"expr\": \"redis_memory_used_bytes\",")
    print("            \"legendFormat\": \"Memory Used\"")
    print("          }")
    print("        ]")
    print("      }")
    print("    ]")
    print("  }")
    print("}")
    print("EOF")
    print()
    print("# 6. Criar dashboard de Docker")
    print("cat > /opt/grafana-dashboards/docker-dashboard.json << 'EOF'")
    print("{")
    print("  \"dashboard\": {")
    print("    \"id\": null,")
    print("    \"title\": \"MaraBet AI - Docker Dashboard\",")
    print("    \"tags\": [\"marabet\", \"docker\"],")
    print("    \"style\": \"dark\",")
    print("    \"timezone\": \"browser\",")
    print("    \"panels\": [")
    print("      {")
    print("        \"id\": 1,")
    print("        \"title\": \"Container CPU Usage\",")
    print("        \"type\": \"graph\",")
    print("        \"targets\": [")
    print("          {")
    print("            \"expr\": \"rate(container_cpu_usage_seconds_total[5m])\",")
    print("            \"legendFormat\": \"CPU Usage\"")
    print("          }")
    print("        ]")
    print("      }")
    print("    ]")
    print("  }")
    print("}")
    print("EOF")
    print()
    print("# 7. Criar dashboard de alertas")
    print("cat > /opt/grafana-dashboards/alerts-dashboard.json << 'EOF'")
    print("{")
    print("  \"dashboard\": {")
    print("    \"id\": null,")
    print("    \"title\": \"MaraBet AI - Alerts Dashboard\",")
    print("    \"tags\": [\"marabet\", \"alerts\"],")
    print("    \"style\": \"dark\",")
    print("    \"timezone\": \"browser\",")
    print("    \"panels\": [")
    print("      {")
    print("        \"id\": 1,")
    print("        \"title\": \"Active Alerts\",")
    print("        \"type\": \"table\",")
    print("        \"targets\": [")
    print("          {")
    print("            \"expr\": \"ALERTS{alertstate=\\\"firing\\\"}\",")
    print("            \"legendFormat\": \"Active Alerts\"")
    print("          }")
    print("        ]")
    print("      }")
    print("    ]")
    print("  }")
    print("}")
    print("EOF")
    print()
    print("# 8. Importar dashboards no Grafana")
    print("curl -X POST http://admin:admin123@localhost:3000/api/dashboards/db \\")
    print("  -H 'Content-Type: application/json' \\")
    print("  -d @/opt/grafana-dashboards/system-dashboard.json")
    
    print("\n🎯 COMANDOS DE VERIFICAÇÃO DE MONITORAMENTO:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Verificar status dos serviços")
    print("sudo systemctl status prometheus grafana-server alertmanager node_exporter redis_exporter")
    print()
    print("# Verificar portas abertas")
    print("sudo netstat -tulpn | grep -E ':(3000|9090|9093|8080|9100|9121|9187)'")
    print()
    print("# Verificar logs dos serviços")
    print("sudo journalctl -u prometheus -f")
    print("sudo journalctl -u grafana-server -f")
    print("sudo journalctl -u alertmanager -f")
    print()
    print("# Verificar métricas do Prometheus")
    print("curl http://localhost:9090/api/v1/targets")
    print("curl http://localhost:9090/api/v1/query?query=up")
    print()
    print("# Verificar dashboards do Grafana")
    print("curl http://admin:admin123@localhost:3000/api/dashboards")
    print()
    print("# Verificar alertas do Alertmanager")
    print("curl http://localhost:9093/api/v1/alerts")
    print()
    print("# Verificar configuração do Nginx")
    print("sudo nginx -t")
    print("sudo systemctl status nginx")
    print()
    print("# Verificar SSL")
    print("curl -I https://prometheus.marabet.com")
    print("curl -I https://grafana.marabet.com")
    print("curl -I https://alerts.marabet.com")
    
    print("\n🚀 COMANDOS DE IMPLEMENTAÇÃO RÁPIDA:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Implementar Prometheus")
    print("sudo mkdir -p /opt/prometheus && cd /opt/prometheus && wget https://github.com/prometheus/prometheus/releases/download/v2.45.0/prometheus-2.45.0.linux-amd64.tar.gz && tar -xzf prometheus-2.45.0.linux-amd64.tar.gz && sudo mv prometheus-2.45.0.linux-amd64 prometheus")
    print()
    print("# Implementar Grafana")
    print("wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add - && echo \"deb https://packages.grafana.com/oss/deb stable main\" | sudo tee -a /etc/apt/sources.list.d/grafana.list && sudo apt update && sudo apt install -y grafana")
    print()
    print("# Implementar Exporters")
    print("cd /opt && wget https://github.com/prometheus/node_exporter/releases/download/v1.6.1/node_exporter-1.6.1.linux-amd64.tar.gz && tar -xzf node_exporter-1.6.1.linux-amd64.tar.gz && sudo mv node_exporter-1.6.1.linux-amd64/node_exporter /usr/local/bin/")
    print()
    print("# Implementar Alertmanager")
    print("cd /opt && wget https://github.com/prometheus/alertmanager/releases/download/v0.25.0/alertmanager-0.25.0.linux-amd64.tar.gz && tar -xzf alertmanager-0.25.0.linux-amd64.tar.gz && sudo mv alertmanager-0.25.0.linux-amd64/alertmanager /usr/local/bin/")
    print()
    print("# Implementar Nginx e SSL")
    print("sudo certbot --nginx -d prometheus.marabet.com -d grafana.marabet.com -d alerts.marabet.com")
    print()
    print("# Implementar Dashboards")
    print("sudo mkdir -p /opt/grafana-dashboards && curl -X POST http://admin:admin123@localhost:3000/api/dashboards/db -H 'Content-Type: application/json' -d @/opt/grafana-dashboards/system-dashboard.json")
    print()
    print("# Implementar Monitoramento Completo")
    print("sudo systemctl enable prometheus grafana-server alertmanager node_exporter redis_exporter && sudo systemctl start prometheus grafana-server alertmanager node_exporter redis_exporter")
    print()
    print("# Implementar Verificação Final")
    print("sudo systemctl status prometheus grafana-server alertmanager node_exporter redis_exporter && sudo netstat -tulpn | grep -E ':(3000|9090|9093|8080|9100|9121|9187)'")
    
    print("\n🎉 INTEGRAÇÃO DE MONITORAMENTO GRAFANA E PROMETHEUS CONSOLIDADA COM SUCESSO!")
    print("=" * 80)
    
    return True

def main():
    print("🚀 Iniciando integração de monitoramento Grafana e Prometheus...")
    
    # Criar integração de monitoramento
    success = create_monitoring_integration()
    
    if success:
        print("\n🎯 INTEGRAÇÃO DE MONITORAMENTO GRAFANA E PROMETHEUS CONSOLIDADA COM SUCESSO!")
        print("Sistema completo e funcionando!")
    else:
        print("\n❌ Falha na integração de monitoramento")
        print("Verifique os logs acima para mais detalhes")

if __name__ == "__main__":
    main()
