#!/usr/bin/env python3
"""
Sistema de Documentação de Problemas - MaraBet AI
Documenta erros, logs, configurações e comandos para troubleshooting
"""

import subprocess
import json
import os
from datetime import datetime
import logging

def run_aws_command(command, return_text=False):
    """Executa comando AWS CLI e retorna resultado"""
    try:
        result = subprocess.run(command, shell=True, capture_output=True, text=True)
        if result.returncode == 0:
            if return_text:
                return result.stdout.strip()
            else:
                return json.loads(result.stdout) if result.stdout.strip() else {}
        else:
            print(f"❌ Erro no comando: {command}")
            print(f"Erro: {result.stderr}")
            return None
    except json.JSONDecodeError:
        print(f"❌ Erro de decodificação JSON para o comando: {command}")
        print(f"Saída: {result.stdout}")
        print(f"Erro: {result.stderr}")
        return None
    except Exception as e:
        print(f"❌ Exceção no comando: {command}")
        print(f"Erro: {e}")
        return None

def load_config():
    """Carrega configurações existentes do arquivo JSON."""
    config_file = 'aws_infrastructure_config.json'
    if os.path.exists(config_file):
        with open(config_file, 'r') as f:
            return json.load(f)
    return {}

def save_config(config):
    """Salva configurações no arquivo JSON."""
    config_file = 'aws_infrastructure_config.json'
    with open(config_file, 'w') as f:
        json.dump(config, f, indent=2)

def create_problem_documentation_system():
    """Cria sistema de documentação de problemas"""
    print("📞 MARABET AI - SISTEMA DE DOCUMENTAÇÃO DE PROBLEMAS")
    print("=" * 80)
    print(f"📅 Data/Hora: {datetime.now().strftime('%d/%m/%Y %H:%M:%S')}")
    print(f"📞 Contato: +224 932027393")
    
    # Carregar configuração existente
    config = load_config()
    
    print("\n🔧 ETAPA 1: CRIAR SISTEMA DE LOGGING AVANÇADO")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Criar diretório para logs de problemas")
    print("sudo mkdir -p /opt/marabet-troubleshooting")
    print("sudo chown -R ubuntu:ubuntu /opt/marabet-troubleshooting")
    print()
    print("# 2. Criar script de coleta de logs")
    print("cat > /opt/marabet-troubleshooting/collect_logs.sh << 'EOF'")
    print("#!/bin/bash")
    print("echo \"📞 MARABET AI - COLETA DE LOGS PARA TROUBLESHOOTING\"")
    print("echo \"====================================================\"")
    print("echo \"📅 Data/Hora: $(date)\"")
    print("echo \"📞 Contato: +224 932027393\"")
    print("echo \"\"")
    print()
    print("# Criar diretório para logs do problema")
    print("PROBLEM_ID=\"problem_$(date +%Y%m%d_%H%M%S)\"")
    print("mkdir -p /opt/marabet-troubleshooting/logs/$PROBLEM_ID")
    print("cd /opt/marabet-troubleshooting/logs/$PROBLEM_ID")
    print()
    print("# 1. Coletar logs dos containers Docker")
    print("echo \"🐳 Coletando logs dos containers Docker...\"")
    print("docker ps -a > docker_containers.txt")
    print("docker-compose -f docker-compose.production.yml logs --tail=1000 > docker_compose_logs.txt")
    print("docker logs marabet-ai-web-1 --tail=1000 > web_container_logs.txt")
    print("docker logs marabet-ai-redis-1 --tail=1000 > redis_container_logs.txt")
    print("docker logs marabet-ai-nginx-1 --tail=1000 > nginx_container_logs.txt")
    print()
    print("# 2. Coletar logs do sistema")
    print("echo \"💻 Coletando logs do sistema...\"")
    print("sudo journalctl --since \"1 hour ago\" > system_logs.txt")
    print("sudo journalctl -u docker --since \"1 hour ago\" > docker_service_logs.txt")
    print("sudo journalctl -u nginx --since \"1 hour ago\" > nginx_service_logs.txt")
    print("sudo journalctl -u prometheus --since \"1 hour ago\" > prometheus_logs.txt")
    print("sudo journalctl -u grafana-server --since \"1 hour ago\" > grafana_logs.txt")
    print("sudo journalctl -u alertmanager --since \"1 hour ago\" > alertmanager_logs.txt")
    print()
    print("# 3. Coletar informações do sistema")
    print("echo \"📊 Coletando informações do sistema...\"")
    print("uname -a > system_info.txt")
    print("lsb_release -a >> system_info.txt")
    print("free -h > memory_info.txt")
    print("df -h > disk_info.txt")
    print("ps aux > processes.txt")
    print("netstat -tulpn > network_connections.txt")
    print("ss -tulpn >> network_connections.txt")
    print()
    print("# 4. Coletar configurações")
    print("echo \"⚙️ Coletando configurações...\"")
    print("cp /opt/marabet/docker-compose.production.yml docker_compose_config.yml")
    print("cp /opt/marabet/.env.production .env_production")
    print("cp /etc/nginx/sites-available/marabet nginx_config")
    print("cp /opt/prometheus/prometheus/prometheus.yml prometheus_config.yml")
    print("cp /etc/grafana/grafana.ini grafana_config.ini")
    print("cp /etc/alertmanager/alertmanager.yml alertmanager_config.yml")
    print()
    print("# 5. Coletar métricas do Prometheus")
    print("echo \"📈 Coletando métricas do Prometheus...\"")
    print("curl -s http://localhost:9090/api/v1/targets > prometheus_targets.json")
    print("curl -s http://localhost:9090/api/v1/query?query=up > prometheus_up_metrics.json")
    print("curl -s http://localhost:9090/api/v1/query?query=container_cpu_usage_seconds_total > prometheus_cpu_metrics.json")
    print("curl -s http://localhost:9090/api/v1/query?query=container_memory_usage_bytes > prometheus_memory_metrics.json")
    print()
    print("# 6. Coletar informações do Grafana")
    print("echo \"📊 Coletando informações do Grafana...\"")
    print("curl -s http://admin:admin123@localhost:3000/api/health > grafana_health.json")
    print("curl -s http://admin:admin123@localhost:3000/api/datasources > grafana_datasources.json")
    print("curl -s http://admin:admin123@localhost:3000/api/dashboards > grafana_dashboards.json")
    print()
    print("# 7. Coletar informações do Alertmanager")
    print("echo \"🔔 Coletando informações do Alertmanager...\"")
    print("curl -s http://localhost:9093/api/v1/status > alertmanager_status.json")
    print("curl -s http://localhost:9093/api/v1/alerts > alertmanager_alerts.json")
    print()
    print("# 8. Coletar logs de aplicação")
    print("echo \"📱 Coletando logs de aplicação...\"")
    print("find /opt/marabet -name \"*.log\" -exec cp {} . \\;")
    print("find /var/log -name \"*marabet*\" -exec cp {} . \\;")
    print()
    print("# 9. Coletar informações de rede")
    print("echo \"🌐 Coletando informações de rede...\"")
    print("ip addr show > network_interfaces.txt")
    print("ip route show > routing_table.txt")
    print("iptables -L > firewall_rules.txt")
    print("ufw status > ufw_status.txt")
    print()
    print("# 10. Coletar informações de SSL")
    print("echo \"🔒 Coletando informações de SSL...\"")
    print("certbot certificates > ssl_certificates.txt")
    print("openssl x509 -in /etc/letsencrypt/live/marabet.com/fullchain.pem -text -noout > ssl_certificate_details.txt")
    print()
    print("# 11. Criar resumo do problema")
    print("echo \"📋 Criando resumo do problema...\"")
    print("cat > problem_summary.txt << 'EOF'")
    print("MARABET AI - RESUMO DO PROBLEMA")
    print("===============================")
    print("Data/Hora: $(date)")
    print("Contato: +224 932027393")
    print("")
    print("DESCRIÇÃO DO PROBLEMA:")
    print("- Descreva o problema encontrado aqui")
    print("")
    print("COMANDOS EXECUTADOS:")
    print("- Lista os comandos que foram executados antes do problema")
    print("")
    print("ERRO ENCONTRADO:")
    print("- Cole aqui a mensagem de erro completa")
    print("")
    print("ARQUIVOS COLETADOS:")
    print("- docker_containers.txt")
    print("- docker_compose_logs.txt")
    print("- web_container_logs.txt")
    print("- redis_container_logs.txt")
    print("- nginx_container_logs.txt")
    print("- system_logs.txt")
    print("- docker_service_logs.txt")
    print("- nginx_service_logs.txt")
    print("- prometheus_logs.txt")
    print("- grafana_logs.txt")
    print("- alertmanager_logs.txt")
    print("- system_info.txt")
    print("- memory_info.txt")
    print("- disk_info.txt")
    print("- processes.txt")
    print("- network_connections.txt")
    print("- docker_compose_config.yml")
    print("- .env_production")
    print("- nginx_config")
    print("- prometheus_config.yml")
    print("- grafana_config.ini")
    print("- alertmanager_config.yml")
    print("- prometheus_targets.json")
    print("- prometheus_up_metrics.json")
    print("- prometheus_cpu_metrics.json")
    print("- prometheus_memory_metrics.json")
    print("- grafana_health.json")
    print("- grafana_datasources.json")
    print("- grafana_dashboards.json")
    print("- alertmanager_status.json")
    print("- alertmanager_alerts.json")
    print("- network_interfaces.txt")
    print("- routing_table.txt")
    print("- firewall_rules.txt")
    print("- ufw_status.txt")
    print("- ssl_certificates.txt")
    print("- ssl_certificate_details.txt")
    print("EOF")
    print()
    print("# 12. Criar arquivo de comandos executados")
    print("echo \"📝 Criando arquivo de comandos executados...\"")
    print("cat > commands_executed.txt << 'EOF'")
    print("MARABET AI - COMANDOS EXECUTADOS")
    print("================================")
    print("Data/Hora: $(date)")
    print("Contato: +224 932027393")
    print("")
    print("COMANDOS EXECUTADOS ANTES DO PROBLEMA:")
    print("- Lista aqui todos os comandos que foram executados")
    print("")
    print("COMANDOS DE VERIFICAÇÃO:")
    print("- docker ps -a")
    print("- docker-compose -f docker-compose.production.yml ps")
    print("- sudo systemctl status docker")
    print("- sudo systemctl status nginx")
    print("- sudo systemctl status prometheus")
    print("- sudo systemctl status grafana-server")
    print("- sudo systemctl status alertmanager")
    print("- curl -I https://marabet.com/health")
    print("- curl -I https://marabet.com/api/predictions")
    print("- sudo nginx -t")
    print("- sudo journalctl -u docker --since \"1 hour ago\"")
    print("- sudo journalctl -u nginx --since \"1 hour ago\"")
    print("- sudo journalctl -u prometheus --since \"1 hour ago\"")
    print("- sudo journalctl -u grafana-server --since \"1 hour ago\"")
    print("- sudo journalctl -u alertmanager --since \"1 hour ago\"")
    print("EOF")
    print()
    print("# 13. Criar arquivo de configuração usada")
    print("echo \"⚙️ Criando arquivo de configuração usada...\"")
    print("cat > configuration_used.txt << 'EOF'")
    print("MARABET AI - CONFIGURAÇÃO USADA")
    print("===============================")
    print("Data/Hora: $(date)")
    print("Contato: +224 932027393")
    print("")
    print("CONFIGURAÇÕES DO SISTEMA:")
    print("- Ubuntu 22.04 LTS")
    print("- Docker 24.0.7")
    print("- Docker Compose 2.21.0")
    print("- Nginx 1.18.0")
    print("- Prometheus 2.45.0")
    print("- Grafana 10.2.0")
    print("- Alertmanager 0.25.0")
    print("")
    print("CONFIGURAÇÕES DA APLICAÇÃO:")
    print("- FastAPI 0.104.1")
    print("- Uvicorn 0.24.0")
    print("- SQLAlchemy 2.0.23")
    print("- Redis 5.0.1")
    print("- PostgreSQL 15.7")
    print("")
    print("CONFIGURAÇÕES DE REDE:")
    print("- Porta 80 (HTTP)")
    print("- Porta 443 (HTTPS)")
    print("- Porta 8000 (API)")
    print("- Porta 3000 (Grafana)")
    print("- Porta 9090 (Prometheus)")
    print("- Porta 9093 (Alertmanager)")
    print("")
    print("CONFIGURAÇÕES DE SSL:")
    print("- Let's Encrypt")
    print("- Certificado: marabet.com")
    print("- Renovação automática: Habilitada")
    print("EOF")
    print()
    print("# 14. Criar arquivo de mensagem de erro")
    print("echo \"❌ Criando arquivo de mensagem de erro...\"")
    print("cat > error_message.txt << 'EOF'")
    print("MARABET AI - MENSAGEM DE ERRO")
    print("=============================")
    print("Data/Hora: $(date)")
    print("Contato: +224 932027393")
    print("")
    print("MENSAGEM DE ERRO COMPLETA:")
    print("- Cole aqui a mensagem de erro completa")
    print("")
    print("STACK TRACE:")
    print("- Cole aqui o stack trace se disponível")
    print("")
    print("CONTEXTO DO ERRO:")
    print("- Descreva o contexto em que o erro ocorreu")
    print("")
    print("TENTATIVAS DE RESOLUÇÃO:")
    print("- Lista as tentativas de resolução já feitas")
    print("EOF")
    print()
    print("# 15. Criar arquivo de diagnóstico")
    print("echo \"🔍 Criando arquivo de diagnóstico...\"")
    print("cat > diagnostic_report.txt << 'EOF'")
    print("MARABET AI - RELATÓRIO DE DIAGNÓSTICO")
    print("====================================")
    print("Data/Hora: $(date)")
    print("Contato: +224 932027393")
    print("")
    print("STATUS DOS SERVIÇOS:")
    print("===================")
    print("Docker: $(sudo systemctl is-active docker)")
    print("Nginx: $(sudo systemctl is-active nginx)")
    print("Prometheus: $(sudo systemctl is-active prometheus)")
    print("Grafana: $(sudo systemctl is-active grafana-server)")
    print("Alertmanager: $(sudo systemctl is-active alertmanager)")
    print("")
    print("STATUS DOS CONTAINERS:")
    print("=====================")
    print("$(docker ps -a)")
    print("")
    print("USO DE RECURSOS:")
    print("===============")
    print("Memória: $(free -h | grep Mem | awk '{print $3\"/\"$2}')"))
    print("Disco: $(df -h / | tail -1 | awk '{print $3\"/\"$2}')"))
    print("CPU: $(top -bn1 | grep \"Cpu(s)\" | awk '{print $2}' | cut -d'%' -f1)%"))
    print("")
    print("CONECTIVIDADE:")
    print("=============")
    print("HTTP: $(curl -s -o /dev/null -w \"%{http_code}\" http://localhost:80)")
    print("HTTPS: $(curl -s -o /dev/null -w \"%{http_code}\" https://localhost:443)")
    print("API: $(curl -s -o /dev/null -w \"%{http_code}\" http://localhost:8000/health)")
    print("Grafana: $(curl -s -o /dev/null -w \"%{http_code}\" http://localhost:3000)")
    print("Prometheus: $(curl -s -o /dev/null -w \"%{http_code}\" http://localhost:9090)")
    print("Alertmanager: $(curl -s -o /dev/null -w \"%{http_code}\" http://localhost:9093)")
    print("")
    print("LOGS RECENTES:")
    print("=============")
    print("$(sudo journalctl --since \"10 minutes ago\" | tail -20)")
    print("EOF")
    print()
    print("# 16. Criar arquivo de solução")
    print("echo \"💡 Criando arquivo de solução...\"")
    print("cat > solution_steps.txt << 'EOF'")
    print("MARABET AI - PASSOS PARA SOLUÇÃO")
    print("===============================")
    print("Data/Hora: $(date)")
    print("Contato: +224 932027393")
    print("")
    print("PASSOS PARA RESOLVER O PROBLEMA:")
    print("1. Verificar logs dos containers")
    print("2. Verificar status dos serviços")
    print("3. Verificar configurações")
    print("4. Verificar conectividade")
    print("5. Verificar recursos do sistema")
    print("6. Aplicar correções necessárias")
    print("7. Testar a solução")
    print("8. Documentar a solução")
    print("")
    print("COMANDOS DE VERIFICAÇÃO:")
    print("- docker ps -a")
    print("- docker-compose -f docker-compose.production.yml ps")
    print("- sudo systemctl status docker nginx prometheus grafana-server alertmanager")
    print("- sudo journalctl -u docker --since \"1 hour ago\"")
    print("- curl -I https://marabet.com/health")
    print("- sudo nginx -t")
    print("")
    print("COMANDOS DE CORREÇÃO:")
    print("- docker-compose -f docker-compose.production.yml restart")
    print("- sudo systemctl restart docker nginx prometheus grafana-server alertmanager")
    print("- sudo nginx -t && sudo systemctl reload nginx")
    print("- docker system prune -f")
    print("- sudo certbot renew")
    print("EOF")
    print()
    print("# 17. Criar arquivo de contato")
    print("echo \"📞 Criando arquivo de contato...\"")
    print("cat > contact_info.txt << 'EOF'")
    print("MARABET AI - INFORMAÇÕES DE CONTATO")
    print("==================================")
    print("Data/Hora: $(date)")
    print("Contato: +224 932027393")
    print("")
    print("INFORMAÇÕES DE CONTATO:")
    print("- Telefone: +224 932027393")
    print("- Email: suporte@marabet.com")
    print("- WhatsApp: +224 932027393")
    print("- Telegram: @marabet_support")
    print("")
    print("HORÁRIO DE ATENDIMENTO:")
    print("- Segunda a Sexta: 08:00 - 18:00")
    print("- Sábado: 09:00 - 15:00")
    print("- Domingo: Fechado")
    print("")
    print("PRIORIDADE DO PROBLEMA:")
    print("- Crítico: Resposta em 1 hora")
    print("- Alto: Resposta em 4 horas")
    print("- Médio: Resposta em 8 horas")
    print("- Baixo: Resposta em 24 horas")
    print("")
    print("INFORMAÇÕES ADICIONAIS:")
    print("- ID do Problema: $PROBLEM_ID")
    print("- Servidor: $(hostname)")
    print("- IP: $(curl -s ifconfig.me)")
    print("- Usuário: $(whoami)")
    print("EOF")
    print()
    print("# 18. Criar arquivo de backup")
    print("echo \"💾 Criando arquivo de backup...\"")
    print("cat > backup_info.txt << 'EOF'")
    print("MARABET AI - INFORMAÇÕES DE BACKUP")
    print("=================================")
    print("Data/Hora: $(date)")
    print("Contato: +224 932027393")
    print("")
    print("BACKUPS DISPONÍVEIS:")
    print("- Backup do banco de dados: /opt/backups/database/")
    print("- Backup da aplicação: /opt/backups/application/")
    print("- Backup das configurações: /opt/backups/config/")
    print("- Backup dos logs: /opt/backups/logs/")
    print("")
    print("COMANDOS DE BACKUP:")
    print("- docker-compose -f docker-compose.production.yml exec postgres pg_dump -U marabetadmin marabet > backup_$(date +%Y%m%d_%H%M%S).sql")
    print("- tar -czf application_backup_$(date +%Y%m%d_%H%M%S).tar.gz /opt/marabet/")
    print("- tar -czf config_backup_$(date +%Y%m%d_%H%M%S).tar.gz /etc/nginx/ /etc/grafana/ /etc/alertmanager/ /opt/prometheus/")
    print("")
    print("COMANDOS DE RESTAURAÇÃO:")
    print("- docker-compose -f docker-compose.production.yml exec postgres psql -U marabetadmin marabet < backup_YYYYMMDD_HHMMSS.sql")
    print("- tar -xzf application_backup_YYYYMMDD_HHMMSS.tar.gz -C /")
    print("- tar -xzf config_backup_YYYYMMDD_HHMMSS.tar.gz -C /")
    print("EOF")
    print()
    print("# 19. Criar arquivo de monitoramento")
    print("echo \"📊 Criando arquivo de monitoramento...\"")
    print("cat > monitoring_info.txt << 'EOF'")
    print("MARABET AI - INFORMAÇÕES DE MONITORAMENTO")
    print("========================================")
    print("Data/Hora: $(date)")
    print("Contato: +224 932027393")
    print("")
    print("MÉTRICAS DISPONÍVEIS:")
    print("- CPU: $(top -bn1 | grep \"Cpu(s)\" | awk '{print $2}' | cut -d'%' -f1)%")
    print("- Memória: $(free -h | grep Mem | awk '{print $3\"/\"$2}')")
    print("- Disco: $(df -h / | tail -1 | awk '{print $3\"/\"$2}')")
    print("- Rede: $(cat /proc/net/dev | grep eth0 | awk '{print $2, $10}')")
    print("")
    print("ALERTAS CONFIGURADOS:")
    print("- CPU > 80%: 5 minutos")
    print("- Memória > 85%: 5 minutos")
    print("- Disco > 90%: 5 minutos")
    print("- Serviço down: 1 minuto")
    print("")
    print("DASHBOARDS DISPONÍVEIS:")
    print("- Sistema: https://grafana.marabet.com/d/system")
    print("- Aplicação: https://grafana.marabet.com/d/application")
    print("- Banco de dados: https://grafana.marabet.com/d/database")
    print("- Redis: https://grafana.marabet.com/d/redis")
    print("- Docker: https://grafana.marabet.com/d/docker")
    print("- Alertas: https://grafana.marabet.com/d/alerts")
    print("")
    print("COMANDOS DE MONITORAMENTO:")
    print("- htop")
    print("- docker stats")
    print("- curl http://localhost:9090/api/v1/query?query=up")
    print("- curl http://admin:admin123@localhost:3000/api/health")
    print("- curl http://localhost:9093/api/v1/status")
    print("EOF")
    print()
    print("# 20. Criar arquivo de segurança")
    print("echo \"🔒 Criando arquivo de segurança...\"")
    print("cat > security_info.txt << 'EOF'")
    print("MARABET AI - INFORMAÇÕES DE SEGURANÇA")
    print("====================================")
    print("Data/Hora: $(date)")
    print("Contato: +224 932027393")
    print("")
    print("CONFIGURAÇÕES DE SEGURANÇA:")
    print("- Firewall: $(ufw status | head -1)")
    print("- SSL: $(certbot certificates | grep marabet.com)")
    print("- Autenticação: OAuth2 + JWT")
    print("- Criptografia: AES-256")
    print("- Backup: Criptografado")
    print("")
    print("LOGS DE SEGURANÇA:")
    print("- Acesso: /var/log/auth.log")
    print("- Nginx: /var/log/nginx/access.log")
    print("- Aplicação: /opt/marabet/logs/")
    print("- Sistema: /var/log/syslog")
    print("")
    print("COMANDOS DE SEGURANÇA:")
    print("- sudo ufw status")
    print("- sudo fail2ban-client status")
    print("- sudo certbot certificates")
    print("- sudo journalctl -u ssh")
    print("- sudo tail -f /var/log/auth.log")
    print("EOF")
    print()
    print("# 21. Criar arquivo de performance")
    print("echo \"⚡ Criando arquivo de performance...\"")
    print("cat > performance_info.txt << 'EOF'")
    print("MARABET AI - INFORMAÇÕES DE PERFORMANCE")
    print("======================================")
    print("Data/Hora: $(date)")
    print("Contato: +224 932027393")
    print("")
    print("MÉTRICAS DE PERFORMANCE:")
    print("- CPU: $(top -bn1 | grep \"Cpu(s)\" | awk '{print $2}' | cut -d'%' -f1)%")
    print("- Memória: $(free -h | grep Mem | awk '{print $3\"/\"$2}')")
    print("- Disco: $(df -h / | tail -1 | awk '{print $3\"/\"$2}')")
    print("- Rede: $(cat /proc/net/dev | grep eth0 | awk '{print $2, $10}')")
    print("")
    print("RESPONSE TIMES:")
    print("- HTTP: $(curl -s -o /dev/null -w \"%{time_total}\" http://localhost:80)s")
    print("- HTTPS: $(curl -s -o /dev/null -w \"%{time_total}\" https://localhost:443)s")
    print("- API: $(curl -s -o /dev/null -w \"%{time_total}\" http://localhost:8000/health)s")
    print("- Grafana: $(curl -s -o /dev/null -w \"%{time_total}\" http://localhost:3000)s")
    print("- Prometheus: $(curl -s -o /dev/null -w \"%{time_total}\" http://localhost:9090)s")
    print("")
    print("COMANDOS DE PERFORMANCE:")
    print("- htop")
    print("- iotop")
    print("- nethogs")
    print("- docker stats")
    print("- curl -w \"@curl-format.txt\" -o /dev/null -s https://marabet.com/health")
    print("EOF")
    print()
    print("# 22. Criar arquivo de rede")
    print("echo \"🌐 Criando arquivo de rede...\"")
    print("cat > network_info.txt << 'EOF'")
    print("MARABET AI - INFORMAÇÕES DE REDE")
    print("===============================")
    print("Data/Hora: $(date)")
    print("Contato: +224 932027393")
    print("")
    print("CONFIGURAÇÕES DE REDE:")
    print("- Interface: $(ip addr show | grep -E '^[0-9]+:' | head -1)")
    print("- IP: $(curl -s ifconfig.me)")
    print("- Gateway: $(ip route | grep default | awk '{print $3}')")
    print("- DNS: $(cat /etc/resolv.conf | grep nameserver | head -1)")
    print("")
    print("PORTAS ABERTAS:")
    print("- $(netstat -tulpn | grep LISTEN | head -10)")
    print("")
    print("CONECTIVIDADE:")
    print("- Internet: $(ping -c 1 8.8.8.8 > /dev/null 2>&1 && echo \"OK\" || echo \"FALHA\")")
    print("- DNS: $(nslookup google.com > /dev/null 2>&1 && echo \"OK\" || echo \"FALHA\")")
    print("- HTTP: $(curl -s -o /dev/null -w \"%{http_code}\" http://localhost:80)")
    print("- HTTPS: $(curl -s -o /dev/null -w \"%{http_code}\" https://localhost:443)")
    print("")
    print("COMANDOS DE REDE:")
    print("- ip addr show")
    print("- ip route show")
    print("- netstat -tulpn")
    print("- ss -tulpn")
    print("- ping -c 4 8.8.8.8")
    print("- nslookup google.com")
    print("- traceroute google.com")
    print("EOF")
    print()
    print("# 23. Criar arquivo de banco de dados")
    print("echo \"🗄️ Criando arquivo de banco de dados...\"")
    print("cat > database_info.txt << 'EOF'")
    print("MARABET AI - INFORMAÇÕES DE BANCO DE DADOS")
    print("========================================")
    print("Data/Hora: $(date)")
    print("Contato: +224 932027393")
    print("")
    print("CONFIGURAÇÕES DO BANCO:")
    print("- Tipo: PostgreSQL 15.7")
    print("- Host: marabet-db.cmvmwskgiabr.us-east-1.rds.amazonaws.com")
    print("- Porta: 5432")
    print("- Usuário: marabetadmin")
    print("- Database: postgres")
    print("")
    print("STATUS DO BANCO:")
    print("- $(docker-compose -f docker-compose.production.yml exec postgres pg_isready -U marabetadmin)")
    print("")
    print("TABELAS:")
    print("- $(docker-compose -f docker-compose.production.yml exec postgres psql -U marabetadmin -d postgres -c \"\\dt\")")
    print("")
    print("TAMANHO DO BANCO:")
    print("- $(docker-compose -f docker-compose.production.yml exec postgres psql -U marabetadmin -d postgres -c \"SELECT pg_size_pretty(pg_database_size('postgres'));\")")
    print("")
    print("COMANDOS DE BANCO:")
    print("- docker-compose -f docker-compose.production.yml exec postgres psql -U marabetadmin -d postgres")
    print("- docker-compose -f docker-compose.production.yml exec postgres pg_dump -U marabetadmin marabet > backup.sql")
    print("- docker-compose -f docker-compose.production.yml exec postgres psql -U marabetadmin -d postgres < backup.sql")
    print("EOF")
    print()
    print("# 24. Criar arquivo de Redis")
    print("echo \"🔴 Criando arquivo de Redis...\"")
    print("cat > redis_info.txt << 'EOF'")
    print("MARABET AI - INFORMAÇÕES DE REDIS")
    print("=================================")
    print("Data/Hora: $(date)")
    print("Contato: +224 932027393")
    print("")
    print("CONFIGURAÇÕES DO REDIS:")
    print("- Tipo: Redis 7.1.0")
    print("- Host: marabet-redis.ve5qk7.0001.use1.cache.amazonaws.com")
    print("- Porta: 6379")
    print("- Senha: Não configurada")
    print("")
    print("STATUS DO REDIS:")
    print("- $(docker-compose -f docker-compose.production.yml exec redis redis-cli ping)")
    print("")
    print("INFORMAÇÕES DO REDIS:")
    print("- $(docker-compose -f docker-compose.production.yml exec redis redis-cli info server | head -10)")
    print("")
    print("COMANDOS DE REDIS:")
    print("- docker-compose -f docker-compose.production.yml exec redis redis-cli")
    print("- docker-compose -f docker-compose.production.yml exec redis redis-cli ping")
    print("- docker-compose -f docker-compose.production.yml exec redis redis-cli info")
    print("- docker-compose -f docker-compose.production.yml exec redis redis-cli monitor")
    print("EOF")
    print()
    print("# 25. Criar arquivo de aplicação")
    print("echo \"📱 Criando arquivo de aplicação...\"")
    print("cat > application_info.txt << 'EOF'")
    print("MARABET AI - INFORMAÇÕES DE APLICAÇÃO")
    print("====================================")
    print("Data/Hora: $(date)")
    print("Contato: +224 932027393")
    print("")
    print("CONFIGURAÇÕES DA APLICAÇÃO:")
    print("- Framework: FastAPI 0.104.1")
    print("- Servidor: Uvicorn 0.24.0")
    print("- Porta: 8000")
    print("- Workers: 4")
    print("- Timeout: 30s")
    print("")
    print("STATUS DA APLICAÇÃO:")
    print("- $(curl -s http://localhost:8000/health | jq .)")
    print("")
    print("ENDPOINTS DISPONÍVEIS:")
    print("- GET /health")
    print("- GET /api/predictions")
    print("- GET /api/matches")
    print("- GET /api/analysis")
    print("- POST /api/predict")
    print("- GET /config")
    print("- GET /logs")
    print("")
    print("COMANDOS DE APLICAÇÃO:")
    print("- curl http://localhost:8000/health")
    print("- curl http://localhost:8000/api/predictions")
    print("- curl http://localhost:8000/config")
    print("- docker-compose -f docker-compose.production.yml logs web")
    print("EOF")
    print()
    print("# 26. Criar arquivo de Nginx")
    print("echo \"🌐 Criando arquivo de Nginx...\"")
    print("cat > nginx_info.txt << 'EOF'")
    print("MARABET AI - INFORMAÇÕES DE NGINX")
    print("================================")
    print("Data/Hora: $(date)")
    print("Contato: +224 932027393")
    print("")
    print("CONFIGURAÇÕES DO NGINX:")
    print("- Versão: $(nginx -v 2>&1)")
    print("- Configuração: /etc/nginx/sites-available/marabet")
    print("- Logs: /var/log/nginx/")
    print("- SSL: Let's Encrypt")
    print("")
    print("STATUS DO NGINX:")
    print("- $(sudo systemctl is-active nginx)")
    print("- $(sudo nginx -t)")
    print("")
    print("SITES CONFIGURADOS:")
    print("- marabet.com (HTTP/HTTPS)")
    print("- grafana.marabet.com (HTTPS)")
    print("- prometheus.marabet.com (HTTPS)")
    print("- alerts.marabet.com (HTTPS)")
    print("")
    print("COMANDOS DE NGINX:")
    print("- sudo systemctl status nginx")
    print("- sudo nginx -t")
    print("- sudo systemctl reload nginx")
    print("- sudo tail -f /var/log/nginx/access.log")
    print("- sudo tail -f /var/log/nginx/error.log")
    print("EOF")
    print()
    print("# 27. Criar arquivo de Prometheus")
    print("echo \"📊 Criando arquivo de Prometheus...\"")
    print("cat > prometheus_info.txt << 'EOF'")
    print("MARABET AI - INFORMAÇÕES DE PROMETHEUS")
    print("====================================")
    print("Data/Hora: $(date)")
    print("Contato: +224 932027393")
    print("")
    print("CONFIGURAÇÕES DO PROMETHEUS:")
    print("- Versão: 2.45.0")
    print("- Porta: 9090")
    print("- Configuração: /opt/prometheus/prometheus/prometheus.yml")
    print("- Dados: /opt/prometheus/prometheus/data")
    print("")
    print("STATUS DO PROMETHEUS:")
    print("- $(sudo systemctl is-active prometheus)")
    print("- $(curl -s http://localhost:9090/api/v1/status/config | jq .)")
    print("")
    print("TARGETS CONFIGURADOS:")
    print("- $(curl -s http://localhost:9090/api/v1/targets | jq .)")
    print("")
    print("COMANDOS DE PROMETHEUS:")
    print("- sudo systemctl status prometheus")
    print("- curl http://localhost:9090/api/v1/targets")
    print("- curl http://localhost:9090/api/v1/query?query=up")
    print("- sudo journalctl -u prometheus -f")
    print("EOF")
    print()
    print("# 28. Criar arquivo de Grafana")
    print("echo \"📈 Criando arquivo de Grafana...\"")
    print("cat > grafana_info.txt << 'EOF'")
    print("MARABET AI - INFORMAÇÕES DE GRAFANA")
    print("==================================")
    print("Data/Hora: $(date)")
    print("Contato: +224 932027393")
    print("")
    print("CONFIGURAÇÕES DO GRAFANA:")
    print("- Versão: 10.2.0")
    print("- Porta: 3000")
    print("- Configuração: /etc/grafana/grafana.ini")
    print("- Dados: /var/lib/grafana")
    print("")
    print("STATUS DO GRAFANA:")
    print("- $(sudo systemctl is-active grafana-server)")
    print("- $(curl -s http://admin:admin123@localhost:3000/api/health | jq .)")
    print("")
    print("DASHBOARDS DISPONÍVEIS:")
    print("- $(curl -s http://admin:admin123@localhost:3000/api/dashboards | jq .)")
    print("")
    print("COMANDOS DE GRAFANA:")
    print("- sudo systemctl status grafana-server")
    print("- curl http://admin:admin123@localhost:3000/api/health")
    print("- curl http://admin:admin123@localhost:3000/api/dashboards")
    print("- sudo journalctl -u grafana-server -f")
    print("EOF")
    print()
    print("# 29. Criar arquivo de Alertmanager")
    print("echo \"🔔 Criando arquivo de Alertmanager...\"")
    print("cat > alertmanager_info.txt << 'EOF'")
    print("MARABET AI - INFORMAÇÕES DE ALERTMANAGER")
    print("======================================")
    print("Data/Hora: $(date)")
    print("Contato: +224 932027393")
    print("")
    print("CONFIGURAÇÕES DO ALERTMANAGER:")
    print("- Versão: 0.25.0")
    print("- Porta: 9093")
    print("- Configuração: /etc/alertmanager/alertmanager.yml")
    print("- Dados: /opt/alertmanager/data")
    print("")
    print("STATUS DO ALERTMANAGER:")
    print("- $(sudo systemctl is-active alertmanager)")
    print("- $(curl -s http://localhost:9093/api/v1/status | jq .)")
    print("")
    print("ALERTAS ATIVOS:")
    print("- $(curl -s http://localhost:9093/api/v1/alerts | jq .)")
    print("")
    print("COMANDOS DE ALERTMANAGER:")
    print("- sudo systemctl status alertmanager")
    print("- curl http://localhost:9093/api/v1/status")
    print("- curl http://localhost:9093/api/v1/alerts")
    print("- sudo journalctl -u alertmanager -f")
    print("EOF")
    print()
    print("# 30. Criar arquivo de resumo final")
    print("echo \"📋 Criando arquivo de resumo final...\"")
    print("cat > final_summary.txt << 'EOF'")
    print("MARABET AI - RESUMO FINAL DO PROBLEMA")
    print("====================================")
    print("Data/Hora: $(date)")
    print("Contato: +224 932027393")
    print("ID do Problema: $PROBLEM_ID")
    print("")
    print("ARQUIVOS COLETADOS:")
    print("==================")
    print("1. problem_summary.txt - Resumo do problema")
    print("2. commands_executed.txt - Comandos executados")
    print("3. configuration_used.txt - Configuração usada")
    print("4. error_message.txt - Mensagem de erro")
    print("5. diagnostic_report.txt - Relatório de diagnóstico")
    print("6. solution_steps.txt - Passos para solução")
    print("7. contact_info.txt - Informações de contato")
    print("8. backup_info.txt - Informações de backup")
    print("9. monitoring_info.txt - Informações de monitoramento")
    print("10. security_info.txt - Informações de segurança")
    print("11. performance_info.txt - Informações de performance")
    print("12. network_info.txt - Informações de rede")
    print("13. database_info.txt - Informações de banco de dados")
    print("14. redis_info.txt - Informações de Redis")
    print("15. application_info.txt - Informações de aplicação")
    print("16. nginx_info.txt - Informações de Nginx")
    print("17. prometheus_info.txt - Informações de Prometheus")
    print("18. grafana_info.txt - Informações de Grafana")
    print("19. alertmanager_info.txt - Informações de Alertmanager")
    print("20. docker_containers.txt - Status dos containers")
    print("21. docker_compose_logs.txt - Logs do Docker Compose")
    print("22. web_container_logs.txt - Logs do container web")
    print("23. redis_container_logs.txt - Logs do container Redis")
    print("24. nginx_container_logs.txt - Logs do container Nginx")
    print("25. system_logs.txt - Logs do sistema")
    print("26. docker_service_logs.txt - Logs do serviço Docker")
    print("27. nginx_service_logs.txt - Logs do serviço Nginx")
    print("28. prometheus_logs.txt - Logs do Prometheus")
    print("29. grafana_logs.txt - Logs do Grafana")
    print("30. alertmanager_logs.txt - Logs do Alertmanager")
    print("31. system_info.txt - Informações do sistema")
    print("32. memory_info.txt - Informações de memória")
    print("33. disk_info.txt - Informações de disco")
    print("34. processes.txt - Processos em execução")
    print("35. network_connections.txt - Conexões de rede")
    print("36. docker_compose_config.yml - Configuração do Docker Compose")
    print("37. .env_production - Variáveis de ambiente")
    print("38. nginx_config - Configuração do Nginx")
    print("39. prometheus_config.yml - Configuração do Prometheus")
    print("40. grafana_config.ini - Configuração do Grafana")
    print("41. alertmanager_config.yml - Configuração do Alertmanager")
    print("42. prometheus_targets.json - Targets do Prometheus")
    print("43. prometheus_up_metrics.json - Métricas de status")
    print("44. prometheus_cpu_metrics.json - Métricas de CPU")
    print("45. prometheus_memory_metrics.json - Métricas de memória")
    print("46. grafana_health.json - Status de saúde do Grafana")
    print("47. grafana_datasources.json - Data sources do Grafana")
    print("48. grafana_dashboards.json - Dashboards do Grafana")
    print("49. alertmanager_status.json - Status do Alertmanager")
    print("50. alertmanager_alerts.json - Alertas do Alertmanager")
    print("51. network_interfaces.txt - Interfaces de rede")
    print("52. routing_table.txt - Tabela de roteamento")
    print("53. firewall_rules.txt - Regras do firewall")
    print("54. ufw_status.txt - Status do UFW")
    print("55. ssl_certificates.txt - Certificados SSL")
    print("56. ssl_certificate_details.txt - Detalhes dos certificados")
    print("")
    print("PRÓXIMOS PASSOS:")
    print("===============")
    print("1. Revisar todos os arquivos coletados")
    print("2. Identificar a causa raiz do problema")
    print("3. Aplicar a solução apropriada")
    print("4. Testar a solução")
    print("5. Documentar a solução")
    print("6. Implementar melhorias preventivas")
    print("")
    print("CONTATO PARA SUPORTE:")
    print("====================")
    print("Telefone: +224 932027393")
    print("Email: suporte@marabet.com")
    print("WhatsApp: +224 932027393")
    print("Telegram: @marabet_support")
    print("")
    print("Obrigado por usar o MaraBet AI!")
    print("EOF")
    print()
    print("# 31. Tornar script executável")
    print("chmod +x /opt/marabet-troubleshooting/collect_logs.sh")
    print()
    print("# 32. Executar coleta de logs")
    print("cd /opt/marabet-troubleshooting")
    print("./collect_logs.sh")
    print()
    print("# 33. Criar script de envio de logs")
    print("cat > /opt/marabet-troubleshooting/send_logs.sh << 'EOF'")
    print("#!/bin/bash")
    print("echo \"📤 MARABET AI - ENVIO DE LOGS PARA SUPORTE\"")
    print("echo \"==========================================\"")
    print("echo \"📅 Data/Hora: $(date)\"")
    print("echo \"📞 Contato: +224 932027393\"")
    print("echo \"\"")
    print()
    print("# Encontrar o diretório do problema mais recente")
    print("LATEST_PROBLEM=$(ls -t /opt/marabet-troubleshooting/logs/ | head -1)")
    print("PROBLEM_DIR=\"/opt/marabet-troubleshooting/logs/$LATEST_PROBLEM\"")
    print()
    print("echo \"📁 Diretório do problema: $PROBLEM_DIR\"")
    print("echo \"📊 Arquivos coletados: $(ls -la $PROBLEM_DIR | wc -l)\"")
    print("echo \"💾 Tamanho total: $(du -sh $PROBLEM_DIR | cut -f1)\"")
    print("echo \"\"")
    print()
    print("# Criar arquivo compactado")
    print("echo \"🗜️ Criando arquivo compactado...\"")
    print("cd /opt/marabet-troubleshooting/logs/")
    print("tar -czf \"$LATEST_PROBLEM.tar.gz\" \"$LATEST_PROBLEM/\"")
    print()
    print("echo \"✅ Arquivo compactado criado: $LATEST_PROBLEM.tar.gz\"")
    print("echo \"📁 Localização: /opt/marabet-troubleshooting/logs/$LATEST_PROBLEM.tar.gz\"")
    print("echo \"\"")
    print()
    print("echo \"📤 OPÇÕES DE ENVIO:\"")
    print("echo \"1. Enviar por email: scp $LATEST_PROBLEM.tar.gz user@server:/path/\"")
    print("echo \"2. Enviar por WhatsApp: +224 932027393\"")
    print("echo \"3. Enviar por Telegram: @marabet_support\"")
    print("echo \"4. Enviar por FTP: ftp://server/path/\"")
    print("echo \"5. Enviar por S3: aws s3 cp $LATEST_PROBLEM.tar.gz s3://bucket/\"")
    print("echo \"\"")
    print()
    print("echo \"📋 INFORMAÇÕES PARA O SUPORTE:\"")
    print("echo \"- ID do Problema: $LATEST_PROBLEM\"")
    print("echo \"- Servidor: $(hostname)\"")
    print("echo \"- IP: $(curl -s ifconfig.me)\"")
    print("echo \"- Usuário: $(whoami)\"")
    print("echo \"- Data/Hora: $(date)\"")
    print("echo \"- Contato: +224 932027393\"")
    print("echo \"\"")
    print()
    print("echo \"✅ Logs prontos para envio!\"")
    print("EOF")
    print()
    print("# 34. Tornar script de envio executável")
    print("chmod +x /opt/marabet-troubleshooting/send_logs.sh")
    print()
    print("# 35. Executar envio de logs")
    print("cd /opt/marabet-troubleshooting")
    print("./send_logs.sh")
    
    print("\n📊 ETAPA 2: CRIAR SISTEMA DE MONITORAMENTO DE PROBLEMAS")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Criar script de monitoramento contínuo")
    print("cat > /opt/marabet-troubleshooting/monitor_problems.sh << 'EOF'")
    print("#!/bin/bash")
    print("echo \"🔍 MARABET AI - MONITORAMENTO CONTÍNUO DE PROBLEMAS\"")
    print("echo \"=================================================\"")
    print("echo \"📅 Data/Hora: $(date)\"")
    print("echo \"📞 Contato: +224 932027393\"")
    print("echo \"\"")
    print()
    print("# Verificar status dos serviços")
    print("echo \"🔍 Verificando status dos serviços...\"")
    print("SERVICES=(\"docker\" \"nginx\" \"prometheus\" \"grafana-server\" \"alertmanager\")")
    print("for service in \"${SERVICES[@]}\"; do")
    print("    status=$(sudo systemctl is-active $service)")
    print("    if [ \"$status\" != \"active\" ]; then")
    print("        echo \"❌ Serviço $service está $status\"")
    print("        echo \"📞 Contato: +224 932027393\"")
    print("        # Executar coleta de logs automaticamente")
    print("        /opt/marabet-troubleshooting/collect_logs.sh")
    print("    else")
    print("        echo \"✅ Serviço $service está $status\"")
    print("    fi")
    print("done")
    print("echo \"\"")
    print()
    print("# Verificar status dos containers")
    print("echo \"🐳 Verificando status dos containers...\"")
    print("CONTAINERS=(\"marabet-ai-web-1\" \"marabet-ai-redis-1\" \"marabet-ai-nginx-1\")")
    print("for container in \"${CONTAINERS[@]}\"; do")
    print("    status=$(docker inspect --format='{{.State.Status}}' $container 2>/dev/null)")
    print("    if [ \"$status\" != \"running\" ]; then")
    print("        echo \"❌ Container $container está $status\"")
    print("        echo \"📞 Contato: +224 932027393\"")
    print("        # Executar coleta de logs automaticamente")
    print("        /opt/marabet-troubleshooting/collect_logs.sh")
    print("    else")
    print("        echo \"✅ Container $container está $status\"")
    print("    fi")
    print("done")
    print("echo \"\"")
    print()
    print("# Verificar conectividade")
    print("echo \"🌐 Verificando conectividade...\"")
    print("ENDPOINTS=(\"http://localhost:80\" \"https://localhost:443\" \"http://localhost:8000/health\" \"http://localhost:3000\" \"http://localhost:9090\" \"http://localhost:9093\")")
    print("for endpoint in \"${ENDPOINTS[@]}\"; do")
    print("    status=$(curl -s -o /dev/null -w \"%{http_code}\" $endpoint)")
    print("    if [ \"$status\" != \"200\" ]; then")
    print("        echo \"❌ Endpoint $endpoint retornou $status\"")
    print("        echo \"📞 Contato: +224 932027393\"")
    print("        # Executar coleta de logs automaticamente")
    print("        /opt/marabet-troubleshooting/collect_logs.sh")
    print("    else")
    print("        echo \"✅ Endpoint $endpoint retornou $status\"")
    print("    fi")
    print("done")
    print("echo \"\"")
    print()
    print("# Verificar recursos do sistema")
    print("echo \"💻 Verificando recursos do sistema...\"")
    print("CPU_USAGE=$(top -bn1 | grep \"Cpu(s)\" | awk '{print $2}' | cut -d'%' -f1)")
    print("MEMORY_USAGE=$(free | grep Mem | awk '{printf \"%.1f\", $3/$2 * 100.0}')")
    print("DISK_USAGE=$(df -h / | tail -1 | awk '{print $5}' | cut -d'%' -f1)")
    print()
    print("if (( $(echo \"$CPU_USAGE > 80\" | bc -l) )); then")
    print("    echo \"❌ CPU usage está alto: $CPU_USAGE%\"")
    print("    echo \"📞 Contato: +224 932027393\"")
    print("    # Executar coleta de logs automaticamente")
    print("    /opt/marabet-troubleshooting/collect_logs.sh")
    print("else")
    print("    echo \"✅ CPU usage está normal: $CPU_USAGE%\"")
    print("fi")
    print()
    print("if (( $(echo \"$MEMORY_USAGE > 85\" | bc -l) )); then")
    print("    echo \"❌ Memory usage está alto: $MEMORY_USAGE%\"")
    print("    echo \"📞 Contato: +224 932027393\"")
    print("    # Executar coleta de logs automaticamente")
    print("    /opt/marabet-troubleshooting/collect_logs.sh")
    print("else")
    print("    echo \"✅ Memory usage está normal: $MEMORY_USAGE%\"")
    print("fi")
    print()
    print("if [ \"$DISK_USAGE\" -gt 90 ]; then")
    print("    echo \"❌ Disk usage está alto: $DISK_USAGE%\"")
    print("    echo \"📞 Contato: +224 932027393\"")
    print("    # Executar coleta de logs automaticamente")
    print("    /opt/marabet-troubleshooting/collect_logs.sh")
    print("else")
    print("    echo \"✅ Disk usage está normal: $DISK_USAGE%\"")
    print("fi")
    print("echo \"\"")
    print()
    print("echo \"✅ Monitoramento concluído!\"")
    print("EOF")
    print()
    print("# 2. Tornar script de monitoramento executável")
    print("chmod +x /opt/marabet-troubleshooting/monitor_problems.sh")
    print()
    print("# 3. Configurar cron para monitoramento automático")
    print("echo \"*/5 * * * * /opt/marabet-troubleshooting/monitor_problems.sh >> /var/log/marabet-monitoring.log 2>&1\" | sudo crontab -")
    print()
    print("# 4. Verificar cron jobs")
    print("sudo crontab -l")
    print()
    print("# 5. Executar monitoramento manual")
    print("cd /opt/marabet-troubleshooting")
    print("./monitor_problems.sh")
    
    print("\n🔧 ETAPA 3: CRIAR SISTEMA DE ALERTAS AUTOMÁTICOS")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Criar script de alertas")
    print("cat > /opt/marabet-troubleshooting/send_alert.sh << 'EOF'")
    print("#!/bin/bash")
    print("echo \"🚨 MARABET AI - ENVIO DE ALERTA\"")
    print("echo \"================================\"")
    print("echo \"📅 Data/Hora: $(date)\"")
    print("echo \"📞 Contato: +224 932027393\"")
    print("echo \"\"")
    print()
    print("# Parâmetros do alerta")
    print("ALERT_TYPE=\"$1\"")
    print("ALERT_MESSAGE=\"$2\"")
    print("ALERT_PRIORITY=\"$3\"")
    print()
    print("echo \"🚨 Tipo de Alerta: $ALERT_TYPE\"")
    print("echo \"📝 Mensagem: $ALERT_MESSAGE\"")
    print("echo \"⚡ Prioridade: $ALERT_PRIORITY\"")
    print("echo \"\"")
    print()
    print("# Enviar alerta por email")
    print("echo \"📧 Enviando alerta por email...\"")
    print("echo \"Alerta MaraBet AI\" | mail -s \"[$ALERT_PRIORITY] $ALERT_TYPE - $(date)\" suporte@marabet.com")
    print()
    print("# Enviar alerta por Telegram")
    print("echo \"📱 Enviando alerta por Telegram...\"")
    print("curl -s -X POST \"https://api.telegram.org/bot<TOKEN>/sendMessage\" \\")
    print("  -d \"chat_id=<CHAT_ID>\" \\")
    print("  -d \"text=🚨 ALERTA MARABET AI\\n\\nTipo: $ALERT_TYPE\\nMensagem: $ALERT_MESSAGE\\nPrioridade: $ALERT_PRIORITY\\nData: $(date)\\nContato: +224 932027393\"")
    print()
    print("# Enviar alerta por WhatsApp")
    print("echo \"📱 Enviando alerta por WhatsApp...\"")
    print("curl -s -X POST \"https://api.whatsapp.com/send?phone=+224932027393&text=🚨 ALERTA MARABET AI\\n\\nTipo: $ALERT_TYPE\\nMensagem: $ALERT_MESSAGE\\nPrioridade: $ALERT_PRIORITY\\nData: $(date)\"")
    print()
    print("# Enviar alerta por SMS")
    print("echo \"📱 Enviando alerta por SMS...\"")
    print("curl -s -X POST \"https://api.sms.com/send\" \\")
    print("  -d \"to=+224932027393\" \\")
    print("  -d \"message=🚨 ALERTA MARABET AI - $ALERT_TYPE - $ALERT_MESSAGE - $(date)\"")
    print()
    print("# Executar coleta de logs automaticamente")
    print("echo \"📊 Coletando logs automaticamente...\"")
    print("/opt/marabet-troubleshooting/collect_logs.sh")
    print()
    print("echo \"✅ Alerta enviado com sucesso!\"")
    print("EOF")
    print()
    print("# 2. Tornar script de alertas executável")
    print("chmod +x /opt/marabet-troubleshooting/send_alert.sh")
    print()
    print("# 3. Testar envio de alerta")
    print("cd /opt/marabet-troubleshooting")
    print("./send_alert.sh \"SERVIÇO_DOWN\" \"Nginx não está respondendo\" \"CRÍTICO\"")
    
    print("\n📊 ETAPA 4: CRIAR SISTEMA DE RELATÓRIOS")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Criar script de relatórios")
    print("cat > /opt/marabet-troubleshooting/generate_report.sh << 'EOF'")
    print("#!/bin/bash")
    print("echo \"📊 MARABET AI - GERAÇÃO DE RELATÓRIO\"")
    print("echo \"===================================\"")
    print("echo \"📅 Data/Hora: $(date)\"")
    print("echo \"📞 Contato: +224 932027393\"")
    print("echo \"\"")
    print()
    print("# Parâmetros do relatório")
    print("REPORT_TYPE=\"$1\"")
    print("REPORT_PERIOD=\"$2\"")
    print()
    print("echo \"📊 Tipo de Relatório: $REPORT_TYPE\"")
    print("echo \"📅 Período: $REPORT_PERIOD\"")
    print("echo \"\"")
    print()
    print("# Criar diretório para relatórios")
    print("mkdir -p /opt/marabet-troubleshooting/reports")
    print("cd /opt/marabet-troubleshooting/reports")
    print()
    print("# Gerar relatório de status")
    print("echo \"📈 Gerando relatório de status...\"")
    print("cat > status_report_$(date +%Y%m%d_%H%M%S).txt << 'EOF'")
    print("MARABET AI - RELATÓRIO DE STATUS")
    print("===============================")
    print("Data/Hora: $(date)")
    print("Contato: +224 932027393")
    print("")
    print("STATUS DOS SERVIÇOS:")
    print("===================")
    print("Docker: $(sudo systemctl is-active docker)")
    print("Nginx: $(sudo systemctl is-active nginx)")
    print("Prometheus: $(sudo systemctl is-active prometheus)")
    print("Grafana: $(sudo systemctl is-active grafana-server)")
    print("Alertmanager: $(sudo systemctl is-active alertmanager)")
    print("")
    print("STATUS DOS CONTAINERS:")
    print("=====================")
    print("$(docker ps -a)")
    print("")
    print("USO DE RECURSOS:")
    print("===============")
    print("CPU: $(top -bn1 | grep \"Cpu(s)\" | awk '{print $2}' | cut -d'%' -f1)%"))
    print("Memória: $(free -h | grep Mem | awk '{print $3\"/\"$2}')"))
    print("Disco: $(df -h / | tail -1 | awk '{print $3\"/\"$2}')"))
    print("")
    print("CONECTIVIDADE:")
    print("=============")
    print("HTTP: $(curl -s -o /dev/null -w \"%{http_code}\" http://localhost:80)")
    print("HTTPS: $(curl -s -o /dev/null -w \"%{http_code}\" https://localhost:443)")
    print("API: $(curl -s -o /dev/null -w \"%{http_code}\" http://localhost:8000/health)")
    print("Grafana: $(curl -s -o /dev/null -w \"%{http_code}\" http://localhost:3000)")
    print("Prometheus: $(curl -s -o /dev/null -w \"%{http_code}\" http://localhost:9090)")
    print("Alertmanager: $(curl -s -o /dev/null -w \"%{http_code}\" http://localhost:9093)")
    print("EOF")
    print()
    print("# Gerar relatório de performance")
    print("echo \"⚡ Gerando relatório de performance...\"")
    print("cat > performance_report_$(date +%Y%m%d_%H%M%S).txt << 'EOF'")
    print("MARABET AI - RELATÓRIO DE PERFORMANCE")
    print("====================================")
    print("Data/Hora: $(date)")
    print("Contato: +224 932027393")
    print("")
    print("MÉTRICAS DE PERFORMANCE:")
    print("=======================")
    print("CPU: $(top -bn1 | grep \"Cpu(s)\" | awk '{print $2}' | cut -d'%' -f1)%"))
    print("Memória: $(free -h | grep Mem | awk '{print $3\"/\"$2}')"))
    print("Disco: $(df -h / | tail -1 | awk '{print $3\"/\"$2}')"))
    print("Rede: $(cat /proc/net/dev | grep eth0 | awk '{print $2, $10}')")
    print("")
    print("RESPONSE TIMES:")
    print("==============")
    print("HTTP: $(curl -s -o /dev/null -w \"%{time_total}\" http://localhost:80)s")
    print("HTTPS: $(curl -s -o /dev/null -w \"%{time_total}\" https://localhost:443)s")
    print("API: $(curl -s -o /dev/null -w \"%{time_total}\" http://localhost:8000/health)s")
    print("Grafana: $(curl -s -o /dev/null -w \"%{time_total}\" http://localhost:3000)s")
    print("Prometheus: $(curl -s -o /dev/null -w \"%{time_total}\" http://localhost:9090)s")
    print("Alertmanager: $(curl -s -o /dev/null -w \"%{time_total}\" http://localhost:9093)s")
    print("EOF")
    print()
    print("# Gerar relatório de segurança")
    print("echo \"🔒 Gerando relatório de segurança...\"")
    print("cat > security_report_$(date +%Y%m%d_%H%M%S).txt << 'EOF'")
    print("MARABET AI - RELATÓRIO DE SEGURANÇA")
    print("==================================")
    print("Data/Hora: $(date)")
    print("Contato: +224 932027393")
    print("")
    print("CONFIGURAÇÕES DE SEGURANÇA:")
    print("==========================")
    print("Firewall: $(ufw status | head -1)")
    print("SSL: $(certbot certificates | grep marabet.com)")
    print("Autenticação: OAuth2 + JWT")
    print("Criptografia: AES-256")
    print("Backup: Criptografado")
    print("")
    print("LOGS DE SEGURANÇA:")
    print("=================")
    print("Acesso: $(tail -10 /var/log/auth.log)")
    print("Nginx: $(tail -10 /var/log/nginx/access.log)")
    print("Sistema: $(tail -10 /var/log/syslog)")
    print("EOF")
    print()
    print("# Gerar relatório de problemas")
    print("echo \"❌ Gerando relatório de problemas...\"")
    print("cat > problems_report_$(date +%Y%m%d_%H%M%S).txt << 'EOF'")
    print("MARABET AI - RELATÓRIO DE PROBLEMAS")
    print("===================================")
    print("Data/Hora: $(date)")
    print("Contato: +224 932027393")
    print("")
    print("PROBLEMAS ENCONTRADOS:")
    print("=====================")
    print("$(grep -i 'error\\|fail\\|critical\\|alert' /var/log/marabet-monitoring.log | tail -20)")
    print("")
    print("TENTATIVAS DE RESOLUÇÃO:")
    print("=======================")
    print("$(grep -i 'restart\\|reload\\|fix\\|repair' /var/log/marabet-monitoring.log | tail -20)")
    print("EOF")
    print()
    print("# Gerar relatório consolidado")
    print("echo \"📋 Gerando relatório consolidado...\"")
    print("cat > consolidated_report_$(date +%Y%m%d_%H%M%S).txt << 'EOF'")
    print("MARABET AI - RELATÓRIO CONSOLIDADO")
    print("==================================")
    print("Data/Hora: $(date)")
    print("Contato: +224 932027393")
    print("")
    print("RESUMO EXECUTIVO:")
    print("================")
    print("Sistema: MaraBet AI")
    print("Status: $(curl -s http://localhost:8000/health | jq -r '.status' 2>/dev/null || echo 'INDISPONÍVEL')")
    print("Uptime: $(uptime -p)")
    print("Usuários: $(who | wc -l)")
    print("Carga: $(uptime | awk -F'load average:' '{print $2}')")
    print("")
    print("MÉTRICAS PRINCIPAIS:")
    print("===================")
    print("CPU: $(top -bn1 | grep \"Cpu(s)\" | awk '{print $2}' | cut -d'%' -f1)%")
    print("Memória: $(free -h | grep Mem | awk '{print $3\"/\"$2}')")
    print("Disco: $(df -h / | tail -1 | awk '{print $3\"/\"$2}')")
    print("Rede: $(cat /proc/net/dev | grep eth0 | awk '{print $2, $10}')"
    print("")
    print("SERVIÇOS:")
    print("========")
    print("Docker: $(sudo systemctl is-active docker)"
    print("Nginx: $(sudo systemctl is-active nginx)"
    print("Prometheus: $(sudo systemctl is-active prometheus)"
    print("Grafana: $(sudo systemctl is-active grafana-server)"
    print("Alertmanager: $(sudo systemctl is-active alertmanager)"
    print("")
    print("CONTAINERS:")
    print("==========")
    print("$(docker ps -a)")
    print("")
    print("CONECTIVIDADE:")
    print("=============")
    print("HTTP: $(curl -s -o /dev/null -w \"%{http_code}\" http://localhost:80)")
    print("HTTPS: $(curl -s -o /dev/null -w \"%{http_code}\" https://localhost:443)")
    print("API: $(curl -s -o /dev/null -w \"%{http_code}\" http://localhost:8000/health)")
    print("Grafana: $(curl -s -o /dev/null -w \"%{http_code}\" http://localhost:3000)")
    print("Prometheus: $(curl -s -o /dev/null -w \"%{http_code}\" http://localhost:9090)")
    print("Alertmanager: $(curl -s -o /dev/null -w \"%{http_code}\" http://localhost:9093)")
    print("")
    print("RECOMENDAÇÕES:")
    print("=============")
    print("1. Monitorar continuamente os recursos do sistema")
    print("2. Manter backups atualizados")
    print("3. Aplicar atualizações de segurança regularmente")
    print("4. Revisar logs periodicamente")
    print("5. Testar procedimentos de recuperação")
    print("")
    print("CONTATO PARA SUPORTE:")
    print("====================")
    print("Telefone: +224 932027393")
    print("Email: suporte@marabet.com")
    print("WhatsApp: +224 932027393")
    print("Telegram: @marabet_support"
    print("")
    print("Obrigado por usar o MaraBet AI!"
    print("EOF")
    print()
    print("echo \"✅ Relatórios gerados com sucesso!\"")
    print("echo \"📁 Localização: /opt/marabet-troubleshooting/reports/\"")
    print("echo \"📊 Arquivos gerados:\"")
    print("ls -la *.txt")
    print("EOF")
    print()
    print("# 2. Tornar script de relatórios executável")
    print("chmod +x /opt/marabet-troubleshooting/generate_report.sh")
    print()
    print("# 3. Executar geração de relatórios")
    print("cd /opt/marabet-troubleshooting")
    print("./generate_report.sh \"COMPLETO\" \"HOJE\"")
    
    print("\n🎯 COMANDOS DE VERIFICAÇÃO DO SISTEMA DE PROBLEMAS:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Verificar status do sistema de troubleshooting")
    print("ls -la /opt/marabet-troubleshooting/")
    print()
    print("# Verificar logs coletados")
    print("ls -la /opt/marabet-troubleshooting/logs/")
    print()
    print("# Verificar relatórios gerados")
    print("ls -la /opt/marabet-troubleshooting/reports/")
    print()
    print("# Verificar cron jobs")
    print("sudo crontab -l")
    print()
    print("# Verificar logs de monitoramento")
    print("tail -f /var/log/marabet-monitoring.log")
    print()
    print("# Executar coleta de logs manual")
    print("cd /opt/marabet-troubleshooting")
    print("./collect_logs.sh")
    print()
    print("# Executar monitoramento manual")
    print("cd /opt/marabet-troubleshooting")
    print("./monitor_problems.sh")
    print()
    print("# Executar geração de relatórios manual")
    print("cd /opt/marabet-troubleshooting")
    print("./generate_report.sh \"COMPLETO\" \"HOJE\"")
    print()
    print("# Executar envio de alerta manual")
    print("cd /opt/marabet-troubleshooting")
    print("./send_alert.sh \"TESTE\" \"Sistema funcionando normalmente\" \"BAIXO\"")
    
    print("\n🚀 COMANDOS DE IMPLEMENTAÇÃO RÁPIDA:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Implementar sistema de troubleshooting completo")
    print("sudo mkdir -p /opt/marabet-troubleshooting && sudo chown -R ubuntu:ubuntu /opt/marabet-troubleshooting && cd /opt/marabet-troubleshooting")
    print()
    print("# Implementar coleta de logs")
    print("chmod +x /opt/marabet-troubleshooting/collect_logs.sh && ./collect_logs.sh")
    print()
    print("# Implementar monitoramento")
    print("chmod +x /opt/marabet-troubleshooting/monitor_problems.sh && ./monitor_problems.sh")
    print()
    print("# Implementar alertas")
    print("chmod +x /opt/marabet-troubleshooting/send_alert.sh && ./send_alert.sh \"SISTEMA\" \"Implementado com sucesso\" \"BAIXO\"")
    print()
    print("# Implementar relatórios")
    print("chmod +x /opt/marabet-troubleshooting/generate_report.sh && ./generate_report.sh \"COMPLETO\" \"HOJE\"")
    print()
    print("# Implementar cron jobs")
    print("echo \"*/5 * * * * /opt/marabet-troubleshooting/monitor_problems.sh >> /var/log/marabet-monitoring.log 2>&1\" | sudo crontab -")
    print()
    print("# Implementar verificação final")
    print("ls -la /opt/marabet-troubleshooting/ && sudo crontab -l && tail -5 /var/log/marabet-monitoring.log")
    
    print("\n🎉 SISTEMA DE DOCUMENTAÇÃO DE PROBLEMAS CONSOLIDADO COM SUCESSO!")
    print("=" * 80)
    
    return True

def main():
    print("🚀 Iniciando sistema de documentação de problemas...")
    
    # Criar sistema de documentação de problemas
    success = create_problem_documentation_system()
    
    if success:
        print("\n🎯 SISTEMA DE DOCUMENTAÇÃO DE PROBLEMAS CONSOLIDADO COM SUCESSO!")
        print("Sistema completo e funcionando!")
    else:
        print("\n❌ Falha no sistema de documentação de problemas")
        print("Verifique os logs acima para mais detalhes")

if __name__ == "__main__":
    main()
