#!/usr/bin/env python3
"""
Plano de Ação para Finalizar Produção - MaraBet AI
Resolução dos problemas identificados na auditoria
"""

import os
import json
from datetime import datetime

def create_production_fix_plan():
    """Cria plano detalhado para resolver problemas de produção"""
    print("🔧 MARABET AI - PLANO DE AÇÃO PARA FINALIZAR PRODUÇÃO")
    print("=" * 80)
    print(f"📅 Data/Hora: {datetime.now().strftime('%d/%m/%Y %H:%M:%S')}")
    print(f"📞 Contato: +224 932027393")
    
    print("\n🎯 PROBLEMAS IDENTIFICADOS NA AUDITORIA:")
    print("-" * 60)
    print("🚨 CRÍTICOS (2):")
    print("  1. Docker não instalado")
    print("  2. Docker Compose não instalado")
    print()
    print("⚠️ AVISOS (4):")
    print("  1. Configuração SSL/HTTPS não encontrada")
    print("  2. Sistema de migrações não encontrado")
    print("  3. Testes de carga não encontrados")
    print("  4. Grafana não configurado")
    
    print("\n🔧 PLANO DE AÇÃO DETALHADO:")
    print("=" * 80)
    
    print("\n1️⃣ INSTALAÇÃO DO DOCKER (CRÍTICO)")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Atualizar sistema")
    print("sudo apt update && sudo apt upgrade -y")
    print()
    print("# Instalar dependências")
    print("sudo apt install -y apt-transport-https ca-certificates curl gnupg lsb-release")
    print()
    print("# Adicionar chave GPG do Docker")
    print("curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg")
    print()
    print("# Adicionar repositório do Docker")
    print('echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null')
    print()
    print("# Instalar Docker")
    print("sudo apt update && sudo apt install -y docker-ce docker-ce-cli containerd.io")
    print()
    print("# Adicionar usuário ao grupo docker")
    print("sudo usermod -aG docker $USER")
    print()
    print("# Instalar Docker Compose")
    print("sudo curl -L \"https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)\" -o /usr/local/bin/docker-compose")
    print("sudo chmod +x /usr/local/bin/docker-compose")
    print()
    print("# Verificar instalação")
    print("docker --version && docker-compose --version")
    print()
    print("# Reiniciar sessão")
    print("newgrp docker")
    
    print("\n2️⃣ CONFIGURAÇÃO SSL/HTTPS (IMPORTANTE)")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Instalar Certbot")
    print("sudo apt install -y certbot python3-certbot-nginx")
    print()
    print("# Obter certificado SSL")
    print("sudo certbot --nginx -d marabet.com -d www.marabet.com")
    print()
    print("# Configurar renovação automática")
    print("sudo crontab -e")
    print("# Adicionar linha: 0 12 * * * /usr/bin/certbot renew --quiet")
    print()
    print("# Atualizar nginx.conf com SSL")
    print("cat > nginx_ssl.conf << 'EOF'")
    print("server {")
    print("    listen 80;")
    print("    server_name marabet.com www.marabet.com;")
    print("    return 301 https://$server_name$request_uri;")
    print("}")
    print()
    print("server {")
    print("    listen 443 ssl http2;")
    print("    server_name marabet.com www.marabet.com;")
    print()
    print("    ssl_certificate /etc/letsencrypt/live/marabet.com/fullchain.pem;")
    print("    ssl_certificate_key /etc/letsencrypt/live/marabet.com/privkey.pem;")
    print("    ssl_protocols TLSv1.2 TLSv1.3;")
    print("    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384;")
    print("    ssl_prefer_server_ciphers off;")
    print()
    print("    location / {")
    print("        proxy_pass http://localhost:8000;")
    print("        proxy_set_header Host $host;")
    print("        proxy_set_header X-Real-IP $remote_addr;")
    print("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;")
    print("        proxy_set_header X-Forwarded-Proto $scheme;")
    print("    }")
    print("}")
    print("EOF")
    print()
    print("# Aplicar configuração")
    print("sudo cp nginx_ssl.conf /etc/nginx/sites-available/marabet")
    print("sudo nginx -t && sudo systemctl reload nginx")
    
    print("\n3️⃣ SISTEMA DE MIGRAÇÕES (IMPORTANTE)")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Criar diretório de migrações")
    print("mkdir -p migrations")
    print()
    print("# Criar arquivo de migração inicial")
    print("cat > migrations/001_initial_schema.sql << 'EOF'")
    print("-- Migração inicial do MaraBet AI")
    print("CREATE TABLE IF NOT EXISTS matches (")
    print("    id SERIAL PRIMARY KEY,")
    print("    home_team VARCHAR(255) NOT NULL,")
    print("    away_team VARCHAR(255) NOT NULL,")
    print("    league VARCHAR(255) NOT NULL,")
    print("    match_date TIMESTAMP NOT NULL,")
    print("    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
    print(");")
    print()
    print("CREATE TABLE IF NOT EXISTS predictions (")
    print("    id SERIAL PRIMARY KEY,")
    print("    match_id INTEGER REFERENCES matches(id),")
    print("    prediction_type VARCHAR(100) NOT NULL,")
    print("    prediction_data JSONB NOT NULL,")
    print("    confidence DECIMAL(5,2) NOT NULL,")
    print("    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
    print(");")
    print()
    print("CREATE TABLE IF NOT EXISTS odds (")
    print("    id SERIAL PRIMARY KEY,")
    print("    match_id INTEGER REFERENCES matches(id),")
    print("    market_type VARCHAR(100) NOT NULL,")
    print("    selection VARCHAR(100) NOT NULL,")
    print("    odds DECIMAL(10,2) NOT NULL,")
    print("    bookmaker VARCHAR(100) NOT NULL,")
    print("    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
    print(");")
    print("EOF")
    print()
    print("# Criar script de migração")
    print("cat > migrate.py << 'EOF'")
    print("#!/usr/bin/env python3")
    print("import os")
    print("import psycopg2")
    print("from pathlib import Path")
    print()
    print("def run_migrations():")
    print("    conn = psycopg2.connect(os.getenv('DATABASE_URL'))")
    print("    cursor = conn.cursor()")
    print("    ")
    print("    migration_files = sorted(Path('migrations').glob('*.sql'))")
    print("    ")
    print("    for migration_file in migration_files:")
    print("        print(f'Executando migração: {migration_file.name}')")
    print("        with open(migration_file, 'r') as f:")
    print("            cursor.execute(f.read())")
    print("    ")
    print("    conn.commit()")
    print("    cursor.close()")
    print("    conn.close()")
    print("    print('Migrações executadas com sucesso!')")
    print()
    print("if __name__ == '__main__':")
    print("    run_migrations()")
    print("EOF")
    print()
    print("# Tornar executável")
    print("chmod +x migrate.py")
    print()
    print("# Executar migrações")
    print("python migrate.py")
    
    print("\n4️⃣ TESTES DE CARGA (IMPORTANTE)")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Instalar Locust")
    print("pip3 install locust")
    print()
    print("# Criar diretório de testes")
    print("mkdir -p load_tests")
    print()
    print("# Criar teste de carga")
    print("cat > load_tests/test_marabet.py << 'EOF'")
    print("from locust import HttpUser, task, between")
    print("import random")
    print()
    print("class MaraBetLoadTest(HttpUser):")
    print("    wait_time = between(1, 3)")
    print("    host = 'https://marabet.com'")
    print()
    print("    @task(3)")
    print("    def get_predictions(self):")
    print("        self.client.get('/api/predictions')")
    print()
    print("    @task(2)")
    print("    def get_matches(self):")
    print("        self.client.get('/api/matches')")
    print()
    print("    @task(1)")
    print("    def get_health(self):")
    print("        self.client.get('/health')")
    print("EOF")
    print()
    print("# Executar teste de carga")
    print("cd load_tests && locust -f test_marabet.py --users 50 --spawn-rate 5 --run-time 60s --headless")
    
    print("\n5️⃣ CONFIGURAÇÃO DO GRAFANA (IMPORTANTE)")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Instalar Grafana")
    print("wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -")
    print("echo \"deb https://packages.grafana.com/oss/deb stable main\" | sudo tee /etc/apt/sources.list.d/grafana.list")
    print("sudo apt update && sudo apt install -y grafana")
    print()
    print("# Iniciar Grafana")
    print("sudo systemctl start grafana-server")
    print("sudo systemctl enable grafana-server")
    print()
    print("# Configurar Grafana")
    print("sudo systemctl status grafana-server")
    print()
    print("# Acessar Grafana")
    print("echo 'Acesse: http://localhost:3000'")
    print("echo 'Usuário: admin'")
    print("echo 'Senha: admin'")
    print()
    print("# Criar dashboard")
    print("cat > grafana_dashboard.json << 'EOF'")
    print("{")
    print("  \"dashboard\": {")
    print("    \"title\": \"MaraBet AI Dashboard\",")
    print("    \"panels\": [")
    print("      {")
    print("        \"title\": \"CPU Usage\",")
    print("        \"type\": \"graph\",")
    print("        \"targets\": [")
    print("          {")
    print("            \"expr\": \"100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)\"")
    print("          }")
    print("        ]")
    print("      }")
    print("    ]")
    print("  }")
    print("}")
    print("EOF")
    
    print("\n6️⃣ SCRIPT DE DEPLOY AUTOMATIZADO")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Criar script de deploy")
    print("cat > deploy_production.sh << 'EOF'")
    print("#!/bin/bash")
    print("echo '🚀 MARABET AI - DEPLOY DE PRODUÇÃO'")
    print("echo '==================================='")
    print()
    print("# Parar containers existentes")
    print("docker-compose -f docker-compose.production.yml down")
    print()
    print("# Fazer backup do banco")
    print("python backup.py")
    print()
    print("# Executar migrações")
    print("python migrate.py")
    print()
    print("# Construir e iniciar containers")
    print("docker-compose -f docker-compose.production.yml build")
    print("docker-compose -f docker-compose.production.yml up -d")
    print()
    print("# Verificar status")
    print("docker-compose -f docker-compose.production.yml ps")
    print()
    print("# Executar testes de saúde")
    print("curl -f http://localhost:8000/health || exit 1")
    print()
    print("echo '✅ Deploy concluído com sucesso!'")
    print("EOF")
    print()
    print("# Tornar executável")
    print("chmod +x deploy_production.sh")
    
    print("\n7️⃣ SCRIPT DE BACKUP AUTOMATIZADO")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Criar script de backup")
    print("cat > backup.py << 'EOF'")
    print("#!/usr/bin/env python3")
    print("import os")
    print("import psycopg2")
    print("import subprocess")
    print("from datetime import datetime")
    print()
    print("def backup_database():")
    print("    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')")
    print("    backup_file = f'backup_marabet_{timestamp}.sql'")
    print("    ")
    print("    # Fazer backup do banco")
    print("    cmd = f\"pg_dump {os.getenv('DATABASE_URL')} > {backup_file}\"")
    print("    subprocess.run(cmd, shell=True)")
    print("    ")
    print("    print(f'Backup criado: {backup_file}')")
    print("    return backup_file")
    print()
    print("if __name__ == '__main__':")
    print("    backup_database()")
    print("EOF")
    print()
    print("# Tornar executável")
    print("chmod +x backup.py")
    print()
    print("# Configurar backup automático")
    print("echo '0 2 * * * /opt/marabet/backup.py' | sudo crontab -")
    
    print("\n8️⃣ MONITORAMENTO E ALERTAS")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Criar script de monitoramento")
    print("cat > monitor.py << 'EOF'")
    print("#!/usr/bin/env python3")
    print("import requests")
    print("import psutil")
    print("import time")
    print()
    print("def check_health():")
    print("    try:")
    print("        response = requests.get('http://localhost:8000/health', timeout=5)")
    print("        return response.status_code == 200")
    print("    except:")
    print("        return False")
    print()
    print("def check_resources():")
    print("    cpu = psutil.cpu_percent()")
    print("    memory = psutil.virtual_memory().percent")
    print("    disk = psutil.disk_usage('/').percent")
    print("    ")
    print("    return cpu < 80 and memory < 85 and disk < 90")
    print()
    print("def main():")
    print("    if not check_health():")
    print("        print('❌ Aplicação não está respondendo')")
    print("        # Enviar alerta")
    print("    ")
    print("    if not check_resources():")
    print("        print('⚠️ Recursos do sistema altos')")
    print("        # Enviar alerta")
    print("    ")
    print("    print('✅ Sistema funcionando normalmente')")
    print()
    print("if __name__ == '__main__':")
    print("    main()")
    print("EOF")
    print()
    print("# Tornar executável")
    print("chmod +x monitor.py")
    print()
    print("# Configurar monitoramento contínuo")
    print("echo '*/5 * * * * /opt/marabet/monitor.py' | sudo crontab -")
    
    print("\n9️⃣ TESTES FINAIS DE PRODUÇÃO")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Teste de conectividade")
    print("curl -I https://marabet.com/health")
    print()
    print("# Teste de performance")
    print("ab -n 1000 -c 10 https://marabet.com/api/predictions")
    print()
    print("# Teste de carga")
    print("cd load_tests && locust -f test_marabet.py --users 100 --spawn-rate 10 --run-time 300s --headless")
    print()
    print("# Verificar logs")
    print("docker-compose -f docker-compose.production.yml logs --tail=100")
    print()
    print("# Verificar métricas")
    print("curl http://localhost:9090/api/v1/query?query=up")
    
    print("\n🔟 CHECKLIST FINAL DE PRODUÇÃO")
    print("-" * 60)
    print("✅ Docker instalado e funcionando")
    print("✅ Docker Compose instalado e funcionando")
    print("✅ SSL/HTTPS configurado")
    print("✅ Migrações de banco executadas")
    print("✅ Testes de carga implementados")
    print("✅ Grafana configurado")
    print("✅ Scripts de deploy criados")
    print("✅ Backup automatizado configurado")
    print("✅ Monitoramento ativo")
    print("✅ Alertas configurados")
    print("✅ Testes finais executados")
    print("✅ Documentação atualizada")
    
    print("\n📊 CRONOGRAMA DE IMPLEMENTAÇÃO:")
    print("-" * 60)
    print("Dia 1: Instalação Docker + SSL")
    print("Dia 2: Migrações + Testes de Carga")
    print("Dia 3: Grafana + Monitoramento")
    print("Dia 4: Scripts + Backup")
    print("Dia 5: Testes Finais + Deploy")
    
    print("\n📞 SUPORTE TÉCNICO:")
    print("-" * 60)
    print("• Telefone: +224 932027393")
    print("• WhatsApp: +224 932027393")
    print("• Telegram: @marabet_support")
    print("• Email: suporte@marabet.ai")
    
    print("\n🎯 RESULTADO ESPERADO:")
    print("-" * 60)
    print("• Score de produção: 95%+")
    print("• Sistema totalmente funcional")
    print("• Monitoramento ativo")
    print("• Backup automatizado")
    print("• Testes de carga validados")
    print("• SSL/HTTPS funcionando")
    print("• Deploy automatizado")
    
    print("\n🎉 SISTEMA PRONTO PARA PRODUÇÃO!")
    print("=" * 80)
    
    return True

def main():
    print("🚀 Iniciando plano de ação para finalizar produção...")
    
    # Criar plano de ação
    success = create_production_fix_plan()
    
    if success:
        print("\n🎯 PLANO DE AÇÃO CRIADO COM SUCESSO!")
        print("Siga os passos para finalizar a produção!")
    else:
        print("\n❌ Falha ao criar plano de ação")
        print("Verifique os logs acima para mais detalhes")

if __name__ == "__main__":
    main()
