#!/usr/bin/env python3
"""
Script de Monitoramento de Recursos - MaraBet AI
Consolida todos os comandos para monitorar recursos do sistema
"""

import subprocess
import json
import os
from datetime import datetime

def run_aws_command(command, return_text=False):
    """Executa comando AWS CLI e retorna resultado"""
    try:
        result = subprocess.run(command, shell=True, capture_output=True, text=True)
        if result.returncode == 0:
            if return_text:
                return result.stdout.strip()
            else:
                return json.loads(result.stdout) if result.stdout.strip() else {}
        else:
            print(f"❌ Erro no comando: {command}")
            print(f"Erro: {result.stderr}")
            return None
    except json.JSONDecodeError:
        print(f"❌ Erro de decodificação JSON para o comando: {command}")
        print(f"Saída: {result.stdout}")
        print(f"Erro: {result.stderr}")
        return None
    except Exception as e:
        print(f"❌ Exceção no comando: {command}")
        print(f"Erro: {e}")
        return None

def load_config():
    """Carrega configurações existentes do arquivo JSON."""
    config_file = 'aws_infrastructure_config.json'
    if os.path.exists(config_file):
        with open(config_file, 'r') as f:
            return json.load(f)
    return {}

def save_config(config):
    """Salva configurações no arquivo JSON."""
    config_file = 'aws_infrastructure_config.json'
    with open(config_file, 'w') as f:
        json.dump(config, f, indent=2)

def create_resource_monitoring():
    """Cria resumo de comandos de monitoramento de recursos"""
    print("📊 MARABET AI - MONITORAMENTO DE RECURSOS DO SISTEMA")
    print("=" * 80)
    print(f"📅 Data/Hora: {datetime.now().strftime('%d/%m/%Y %H:%M:%S')}")
    
    # Carregar configuração existente
    config = load_config()
    
    print("\n💻 CPU E MEMÓRIA - MONITORAMENTO BÁSICO:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Ver uso de CPU/RAM em tempo real")
    print("htop")
    print()
    print("# Ver uso de CPU/RAM resumido")
    print("top")
    print()
    print("# Ver uso de memória detalhado")
    print("free -h")
    print()
    print("# Ver uso de CPU detalhado")
    print("iostat -x 1")
    print()
    print("# Ver processos por uso de CPU")
    print("ps aux --sort=-%cpu | head -10")
    print()
    print("# Ver processos por uso de memória")
    print("ps aux --sort=-%mem | head -10")
    print()
    print("# Ver uso de CPU por core")
    print("mpstat -P ALL 1")
    print()
    print("# Ver uso de memória por processo")
    print("ps aux --sort=-%mem | head -20")
    print()
    print("# Ver uso de CPU por processo")
    print("ps aux --sort=-%cpu | head -20")
    
    print("\n💾 DISCO - MONITORAMENTO DE ARMAZENAMENTO:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Ver uso de disco")
    print("df -h")
    print()
    print("# Ver uso de disco detalhado")
    print("df -hT")
    print()
    print("# Ver uso de disco por diretório")
    print("du -sh /* 2>/dev/null | sort -hr")
    print()
    print("# Ver uso de disco por diretório específico")
    print("du -sh /home/ubuntu/* 2>/dev/null | sort -hr")
    print()
    print("# Ver uso de disco em tempo real")
    print("iotop")
    print()
    print("# Ver uso de disco por processo")
    print("sudo lsof | grep -E 'REG.*[0-9]+.*[0-9]+.*[0-9]+' | awk '{print $9}' | sort | uniq -c | sort -nr | head -10")
    print()
    print("# Ver arquivos maiores")
    print("find /home/ubuntu -type f -size +100M -exec ls -lh {} \\; 2>/dev/null | sort -k5 -hr")
    print()
    print("# Ver diretórios maiores")
    print("du -h /home/ubuntu | grep -E '^[0-9]+\\.[0-9]+G' | sort -hr")
    print()
    print("# Ver espaço livre em tempo real")
    print("watch -n 1 'df -h'")
    
    print("\n📝 LOGS - MONITORAMENTO DE LOGS:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Ver logs do sistema em tempo real")
    print("sudo journalctl -f")
    print()
    print("# Ver logs do sistema por serviço")
    print("sudo journalctl -u nginx -f")
    print("sudo journalctl -u docker -f")
    print()
    print("# Ver logs de aplicação")
    print("docker-compose -f docker-compose.production.yml logs -f")
    print()
    print("# Ver logs de Nginx")
    print("sudo tail -f /var/log/nginx/access.log")
    print("sudo tail -f /var/log/nginx/error.log")
    print()
    print("# Ver logs de backup")
    print("tail -f /var/log/marabet_backup.log")
    print()
    print("# Ver logs de atualização")
    print("tail -f /var/log/marabet_system_updates.log")
    print("tail -f /var/log/marabet_app_updates.log")
    print("tail -f /var/log/marabet_security.log")
    print("tail -f /var/log/marabet_monitoring.log")
    print()
    print("# Ver logs de sistema por período")
    print("sudo journalctl --since '1 hour ago'")
    print("sudo journalctl --since '1 day ago'")
    print("sudo journalctl --since '1 week ago'")
    print()
    print("# Ver logs de erro")
    print("sudo journalctl -p err -f")
    print()
    print("# Ver logs de warning")
    print("sudo journalctl -p warning -f")
    
    print("\n🐳 DOCKER - MONITORAMENTO DE CONTAINERS:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Ver processos Docker")
    print("docker stats")
    print()
    print("# Ver processos Docker sem streaming")
    print("docker stats --no-stream")
    print()
    print("# Ver containers em execução")
    print("docker ps")
    print()
    print("# Ver todos os containers")
    print("docker ps -a")
    print()
    print("# Ver imagens")
    print("docker images")
    print()
    print("# Ver volumes")
    print("docker volume ls")
    print()
    print("# Ver redes")
    print("docker network ls")
    print()
    print("# Ver uso de espaço Docker")
    print("docker system df")
    print()
    print("# Ver logs de container específico")
    print("docker logs -f <container_id>")
    print()
    print("# Ver logs de container por nome")
    print("docker logs -f marabet-ai_web_1")
    print()
    print("# Ver processos dentro do container")
    print("docker exec -it <container_id> ps aux")
    print()
    print("# Ver uso de recursos do container")
    print("docker exec -it <container_id> top")
    
    print("\n🌐 REDE - MONITORAMENTO DE CONECTIVIDADE:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Ver conexões de rede")
    print("netstat -tuln")
    print()
    print("# Ver conexões de rede por protocolo")
    print("netstat -tuln | grep :80")
    print("netstat -tuln | grep :443")
    print("netstat -tuln | grep :8000")
    print()
    print("# Ver processos por porta")
    print("sudo lsof -i :80")
    print("sudo lsof -i :443")
    print("sudo lsof -i :8000")
    print()
    print("# Ver conexões ativas")
    print("ss -tuln")
    print()
    print("# Ver conexões TCP")
    print("ss -tuln | grep tcp")
    print()
    print("# Ver conexões UDP")
    print("ss -tuln | grep udp")
    print()
    print("# Ver tráfego de rede")
    print("iftop")
    print()
    print("# Ver estatísticas de rede")
    print("cat /proc/net/dev")
    print()
    print("# Ver roteamento")
    print("ip route")
    print()
    print("# Ver interfaces de rede")
    print("ip addr show")
    
    print("\n🔍 PROCESSOS - MONITORAMENTO DE PROCESSOS:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Ver todos os processos")
    print("ps aux")
    print()
    print("# Ver processos por usuário")
    print("ps aux | grep ubuntu")
    print()
    print("# Ver processos por comando")
    print("ps aux | grep python")
    print("ps aux | grep nginx")
    print("ps aux | grep docker")
    print()
    print("# Ver processos em árvore")
    print("pstree")
    print()
    print("# Ver processos por PID")
    print("ps -p <pid>")
    print()
    print("# Ver processos por PPID")
    print("ps --ppid <ppid>")
    print()
    print("# Ver processos por nome")
    print("pgrep -f nginx")
    print("pgrep -f docker")
    print()
    print("# Ver processos por porta")
    print("fuser -n tcp 80")
    print("fuser -n tcp 443")
    print("fuser -n tcp 8000")
    print()
    print("# Ver processos em tempo real")
    print("watch -n 1 'ps aux | head -20'")
    
    print("\n📊 SISTEMA - MONITORAMENTO GERAL:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Ver informações do sistema")
    print("uname -a")
    print()
    print("# Ver versão do sistema")
    print("lsb_release -a")
    print()
    print("# Ver uptime")
    print("uptime")
    print()
    print("# Ver carga do sistema")
    print("cat /proc/loadavg")
    print()
    print("# Ver informações de CPU")
    print("cat /proc/cpuinfo | grep 'model name' | head -1")
    print()
    print("# Ver informações de memória")
    print("cat /proc/meminfo | head -10")
    print()
    print("# Ver informações de disco")
    print("lsblk")
    print()
    print("# Ver informações de rede")
    print("ip link show")
    print()
    print("# Ver informações de hardware")
    print("lshw -short")
    print()
    print("# Ver informações de PCI")
    print("lspci")
    print()
    print("# Ver informações de USB")
    print("lsusb")
    
    print("\n🔧 FERRAMENTAS - MONITORAMENTO AVANÇADO:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Instalar ferramentas de monitoramento")
    print("sudo apt install -y htop iotop nethogs nload iftop")
    print()
    print("# Ver uso de CPU com htop")
    print("htop")
    print()
    print("# Ver uso de disco com iotop")
    print("sudo iotop")
    print()
    print("# Ver uso de rede com nethogs")
    print("sudo nethogs")
    print()
    print("# Ver uso de rede com nload")
    print("nload")
    print()
    print("# Ver uso de rede com iftop")
    print("sudo iftop")
    print()
    print("# Ver uso de memória com free")
    print("free -h")
    print()
    print("# Ver uso de disco com df")
    print("df -h")
    print()
    print("# Ver uso de disco com du")
    print("du -sh /* 2>/dev/null | sort -hr")
    print()
    print("# Ver uso de CPU com top")
    print("top")
    print()
    print("# Ver uso de CPU com vmstat")
    print("vmstat 1")
    
    print("\n📈 MÉTRICAS - MONITORAMENTO CONTÍNUO:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Monitorar CPU continuamente")
    print("watch -n 1 'cat /proc/loadavg'")
    print()
    print("# Monitorar memória continuamente")
    print("watch -n 1 'free -h'")
    print()
    print("# Monitorar disco continuamente")
    print("watch -n 1 'df -h'")
    print()
    print("# Monitorar processos continuamente")
    print("watch -n 1 'ps aux --sort=-%cpu | head -10'")
    print()
    print("# Monitorar rede continuamente")
    print("watch -n 1 'netstat -tuln | grep LISTEN'")
    print()
    print("# Monitorar Docker continuamente")
    print("watch -n 1 'docker stats --no-stream'")
    print()
    print("# Monitorar logs continuamente")
    print("tail -f /var/log/syslog")
    print()
    print("# Monitorar Nginx continuamente")
    print("tail -f /var/log/nginx/access.log")
    print()
    print("# Monitorar aplicação continuamente")
    print("docker-compose -f docker-compose.production.yml logs -f")
    
    print("\n🎯 COMANDOS RÁPIDOS - MONITORAMENTO:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Status completo do sistema")
    print("htop && df -h && free -h && uptime")
    print()
    print("# Status completo dos serviços")
    print("docker-compose -f docker-compose.production.yml ps && sudo systemctl status nginx && sudo systemctl status docker")
    print()
    print("# Status completo da rede")
    print("netstat -tuln | grep LISTEN && ss -tuln | grep LISTEN")
    print()
    print("# Status completo dos logs")
    print("sudo journalctl --since '1 hour ago' | tail -20 && docker-compose -f docker-compose.production.yml logs --tail=20")
    print()
    print("# Status completo do Docker")
    print("docker stats --no-stream && docker ps && docker images")
    print()
    print("# Status completo do disco")
    print("df -h && du -sh /home/ubuntu/* 2>/dev/null | sort -hr | head -10")
    print()
    print("# Status completo da memória")
    print("free -h && ps aux --sort=-%mem | head -10")
    print()
    print("# Status completo da CPU")
    print("top -bn1 | head -20 && ps aux --sort=-%cpu | head -10")
    
    print("\n🎉 COMANDOS DE MONITORAMENTO CONSOLIDADOS COM SUCESSO!")
    print("=" * 80)
    
    return True

def main():
    print("🚀 Iniciando consolidação de comandos de monitoramento...")
    
    # Criar comandos de monitoramento
    success = create_resource_monitoring()
    
    if success:
        print("\n🎯 COMANDOS DE MONITORAMENTO CONSOLIDADOS COM SUCESSO!")
        print("Sistema completo e funcionando!")
    else:
        print("\n❌ Falha na consolidação de comandos de monitoramento")
        print("Verifique os logs acima para mais detalhes")

if __name__ == "__main__":
    main()
