#!/usr/bin/env python3
"""
Script de Implementação de Segurança - MaraBet AI
Implementa WAF (Web Application Firewall) e AWS Shield para proteção avançada
"""

import subprocess
import json
import os
from datetime import datetime

def run_aws_command(command, return_text=False):
    """Executa comando AWS CLI e retorna resultado"""
    try:
        result = subprocess.run(command, shell=True, capture_output=True, text=True)
        if result.returncode == 0:
            if return_text:
                return result.stdout.strip()
            else:
                return json.loads(result.stdout) if result.stdout.strip() else {}
        else:
            print(f"❌ Erro no comando: {command}")
            print(f"Erro: {result.stderr}")
            return None
    except json.JSONDecodeError:
        print(f"❌ Erro de decodificação JSON para o comando: {command}")
        print(f"Saída: {result.stdout}")
        print(f"Erro: {result.stderr}")
        return None
    except Exception as e:
        print(f"❌ Exceção no comando: {command}")
        print(f"Erro: {e}")
        return None

def load_config():
    """Carrega configurações existentes do arquivo JSON."""
    config_file = 'aws_infrastructure_config.json'
    if os.path.exists(config_file):
        with open(config_file, 'r') as f:
            return json.load(f)
    return {}

def save_config(config):
    """Salva configurações no arquivo JSON."""
    config_file = 'aws_infrastructure_config.json'
    with open(config_file, 'w') as f:
        json.dump(config, f, indent=2)

def create_security_implementation():
    """Cria implementação de segurança WAF e Shield"""
    print("🛡️ MARABET AI - IMPLEMENTAÇÃO DE SEGURANÇA WAF E SHIELD")
    print("=" * 80)
    print(f"📅 Data/Hora: {datetime.now().strftime('%d/%m/%Y %H:%M:%S')}")
    
    # Carregar configuração existente
    config = load_config()
    
    print("\n🔒 ETAPA 1: IMPLEMENTAÇÃO DO AWS WAF")
    print("-" * 60)
    print("Execute no terminal local:")
    print()
    print("# 1. Criar Web ACL para MaraBet AI")
    print("aws wafv2 create-web-acl --name marabet-waf-acl --scope REGIONAL --default-action Allow={} --rules file://waf-rules.json --region us-east-1")
    print()
    print("# 2. Criar regras de proteção contra SQL Injection")
    print("aws wafv2 create-rule-group --name marabet-sql-injection-rules --scope REGIONAL --rules file://sql-injection-rules.json --region us-east-1")
    print()
    print("# 3. Criar regras de proteção contra XSS")
    print("aws wafv2 create-rule-group --name marabet-xss-rules --scope REGIONAL --rules file://xss-rules.json --region us-east-1")
    print()
    print("# 4. Criar regras de rate limiting")
    print("aws wafv2 create-rule-group --name marabet-rate-limit-rules --scope REGIONAL --rules file://rate-limit-rules.json --region us-east-1")
    print()
    print("# 5. Criar regras de proteção contra DDoS")
    print("aws wafv2 create-rule-group --name marabet-ddos-rules --scope REGIONAL --rules file://ddos-rules.json --region us-east-1")
    print()
    print("# 6. Criar regras de geolocalização")
    print("aws wafv2 create-rule-group --name marabet-geo-rules --scope REGIONAL --rules file://geo-rules.json --region us-east-1")
    print()
    print("# 7. Criar regras de proteção contra bots")
    print("aws wafv2 create-rule-group --name marabet-bot-rules --scope REGIONAL --rules file://bot-rules.json --region us-east-1")
    print()
    print("# 8. Criar regras de proteção contra ataques conhecidos")
    print("aws wafv2 create-rule-group --name marabet-known-attacks-rules --scope REGIONAL --rules file://known-attacks-rules.json --region us-east-1")
    
    print("\n🛡️ ETAPA 2: IMPLEMENTAÇÃO DO AWS SHIELD")
    print("-" * 60)
    print("Execute no terminal local:")
    print()
    print("# 1. Ativar AWS Shield Advanced")
    print("aws shield create-subscription --region us-east-1")
    print()
    print("# 2. Criar proteção para o Load Balancer")
    print("aws shield create-protection --name marabet-shield-protection --resource-arn arn:aws:elasticloadbalancing:us-east-1:206749730888:loadbalancer/app/marabet-lb/1234567890abcdef --region us-east-1")
    print()
    print("# 3. Criar proteção para o RDS")
    print("aws shield create-protection --name marabet-rds-shield-protection --resource-arn arn:aws:rds:us-east-1:206749730888:db:marabet-db --region us-east-1")
    print()
    print("# 4. Criar proteção para o Redis")
    print("aws shield create-protection --name marabet-redis-shield-protection --resource-arn arn:aws:elasticache:us-east-1:206749730888:cluster:marabet-redis --region us-east-1")
    print()
    print("# 5. Configurar notificações de Shield")
    print("aws shield create-subscription --region us-east-1")
    print()
    print("# 6. Configurar alarmes de Shield")
    print("aws cloudwatch put-metric-alarm --alarm-name marabet-shield-ddos-alarm --alarm-description \"DDoS Attack Detected\" --metric-name DDoSDetected --namespace AWS/DDoSProtection --statistic Sum --period 300 --threshold 1 --comparison-operator GreaterThanOrEqualToThreshold --region us-east-1")
    print()
    print("# 7. Configurar resposta automática")
    print("aws shield create-response-plan --name marabet-shield-response-plan --incident-template file://shield-response-plan.json --region us-east-1")
    print()
    print("# 8. Configurar integração com SNS")
    print("aws sns create-topic --name marabet-shield-alerts --region us-east-1")
    
    print("\n🌐 ETAPA 3: CONFIGURAÇÃO DO LOAD BALANCER COM WAF")
    print("-" * 60)
    print("Execute no terminal local:")
    print()
    print("# 1. Criar Load Balancer Application")
    print("aws elbv2 create-load-balancer --name marabet-alb --subnets subnet-09d65bdd7b15819c4 subnet-0b3cec41b65c8a0a0 --security-groups sg-04b9744aba79e7514 --region us-east-1")
    print()
    print("# 2. Criar Target Group")
    print("aws elbv2 create-target-group --name marabet-targets --protocol HTTP --port 8000 --vpc-id vpc-0c08de281a0a35d05 --health-check-path /health --region us-east-1")
    print()
    print("# 3. Registrar instâncias no Target Group")
    print("aws elbv2 register-targets --target-group-arn arn:aws:elasticloadbalancing:us-east-1:206749730888:targetgroup/marabet-targets/1234567890abcdef --targets Id=i-0225f2fa806b1bf27 --region us-east-1")
    print()
    print("# 4. Criar Listener HTTPS")
    print("aws elbv2 create-listener --load-balancer-arn arn:aws:elasticloadbalancing:us-east-1:206749730888:loadbalancer/app/marabet-alb/1234567890abcdef --protocol HTTPS --port 443 --certificates CertificateArn=arn:aws:acm:us-east-1:206749730888:certificate/12345678-1234-1234-1234-123456789012 --default-actions Type=forward,TargetGroupArn=arn:aws:elasticloadbalancing:us-east-1:206749730888:targetgroup/marabet-targets/1234567890abcdef --region us-east-1")
    print()
    print("# 5. Associar WAF ao Load Balancer")
    print("aws wafv2 associate-web-acl --web-acl-arn arn:aws:wafv2:us-east-1:206749730888:regional/webacl/marabet-waf-acl/12345678-1234-1234-1234-123456789012 --resource-arn arn:aws:elasticloadbalancing:us-east-1:206749730888:loadbalancer/app/marabet-alb/1234567890abcdef --region us-east-1")
    print()
    print("# 6. Configurar SSL/TLS")
    print("aws acm request-certificate --domain-name marabet.com --validation-method DNS --region us-east-1")
    print()
    print("# 7. Configurar redirecionamento HTTP para HTTPS")
    print("aws elbv2 create-listener --load-balancer-arn arn:aws:elasticloadbalancing:us-east-1:206749730888:loadbalancer/app/marabet-alb/1234567890abcdef --protocol HTTP --port 80 --default-actions Type=redirect,RedirectConfig='{Protocol=HTTPS,Port=443,StatusCode=HTTP_301}' --region us-east-1")
    print()
    print("# 8. Configurar health checks avançados")
    print("aws elbv2 modify-target-group --target-group-arn arn:aws:elasticloadbalancing:us-east-1:206749730888:targetgroup/marabet-targets/1234567890abcdef --health-check-path /health --health-check-interval-seconds 30 --healthy-threshold-count 2 --unhealthy-threshold-count 3 --region us-east-1")
    
    print("\n🔐 ETAPA 4: CONFIGURAÇÃO DE SEGURANÇA AVANÇADA")
    print("-" * 60)
    print("Execute no terminal local:")
    print()
    print("# 1. Configurar AWS Config para compliance")
    print("aws configservice put-configuration-recorder --configuration-recorder name=marabet-config-recorder,roleARN=arn:aws:iam::206749730888:role/ConfigRole --region us-east-1")
    print()
    print("# 2. Configurar AWS GuardDuty")
    print("aws guardduty create-detector --enable --region us-east-1")
    print()
    print("# 3. Configurar AWS Security Hub")
    print("aws securityhub enable-security-hub --region us-east-1")
    print()
    print("# 4. Configurar AWS Inspector")
    print("aws inspector create-assessment-target --assessment-target-name marabet-inspector-target --resource-group-arn arn:aws:inspector:us-east-1:206749730888:resourcegroup/0-1234567890abcdef --region us-east-1")
    print()
    print("# 5. Configurar AWS CloudTrail")
    print("aws cloudtrail create-trail --name marabet-cloudtrail --s3-bucket-name marabet-cloudtrail-logs --region us-east-1")
    print()
    print("# 6. Configurar AWS VPC Flow Logs")
    print("aws ec2 create-flow-logs --resource-type VPC --resource-ids vpc-0c08de281a0a35d05 --traffic-type ALL --log-destination-type s3 --log-destination arn:aws:s3:::marabet-vpc-flow-logs --region us-east-1")
    print()
    print("# 7. Configurar AWS KMS para criptografia")
    print("aws kms create-key --description \"MaraBet AI Encryption Key\" --region us-east-1")
    print()
    print("# 8. Configurar AWS Secrets Manager")
    print("aws secretsmanager create-secret --name marabet-db-credentials --description \"MaraBet AI Database Credentials\" --secret-string '{\"username\":\"marabetadmin\",\"password\":\"MaraBet2024!SuperSecret\"}' --region us-east-1")
    
    print("\n📊 ETAPA 5: MONITORAMENTO E ALERTAS DE SEGURANÇA")
    print("-" * 60)
    print("Execute no terminal local:")
    print()
    print("# 1. Criar dashboard de segurança")
    print("aws cloudwatch put-dashboard --dashboard-name MaraBet-Security-Dashboard --dashboard-body file://security-dashboard.json --region us-east-1")
    print()
    print("# 2. Configurar alarmes de WAF")
    print("aws cloudwatch put-metric-alarm --alarm-name marabet-waf-blocked-requests --alarm-description \"WAF Blocked Requests\" --metric-name BlockedRequests --namespace AWS/WAFV2 --statistic Sum --period 300 --threshold 100 --comparison-operator GreaterThanThreshold --region us-east-1")
    print()
    print("# 3. Configurar alarmes de Shield")
    print("aws cloudwatch put-metric-alarm --alarm-name marabet-shield-attacks --alarm-description \"Shield Attack Detected\" --metric-name AttackCount --namespace AWS/DDoSProtection --statistic Sum --period 300 --threshold 1 --comparison-operator GreaterThanOrEqualToThreshold --region us-east-1")
    print()
    print("# 4. Configurar alarmes de GuardDuty")
    print("aws cloudwatch put-metric-alarm --alarm-name marabet-guardduty-findings --alarm-description \"GuardDuty Security Findings\" --metric-name Findings --namespace AWS/GuardDuty --statistic Sum --period 300 --threshold 1 --comparison-operator GreaterThanOrEqualToThreshold --region us-east-1")
    print()
    print("# 5. Configurar alarmes de Security Hub")
    print("aws cloudwatch put-metric-alarm --alarm-name marabet-security-hub-findings --alarm-description \"Security Hub Findings\" --metric-name Findings --namespace AWS/SecurityHub --statistic Sum --period 300 --threshold 1 --comparison-operator GreaterThanOrEqualToThreshold --region us-east-1")
    print()
    print("# 6. Configurar alarmes de Inspector")
    print("aws cloudwatch put-metric-alarm --alarm-name marabet-inspector-findings --alarm-description \"Inspector Security Findings\" --metric-name Findings --namespace AWS/Inspector --statistic Sum --period 300 --threshold 1 --comparison-operator GreaterThanOrEqualToThreshold --region us-east-1")
    print()
    print("# 7. Configurar alarmes de CloudTrail")
    print("aws cloudwatch put-metric-alarm --alarm-name marabet-cloudtrail-errors --alarm-description \"CloudTrail Errors\" --metric-name ErrorCount --namespace AWS/CloudTrail --statistic Sum --period 300 --threshold 1 --comparison-operator GreaterThanOrEqualToThreshold --region us-east-1")
    print()
    print("# 8. Configurar alarmes de VPC Flow Logs")
    print("aws cloudwatch put-metric-alarm --alarm-name marabet-vpc-flow-logs-errors --alarm-description \"VPC Flow Logs Errors\" --metric-name ErrorCount --namespace AWS/VPC --statistic Sum --period 300 --threshold 1 --comparison-operator GreaterThanOrEqualToThreshold --region us-east-1")
    
    print("\n🔧 ETAPA 6: CONFIGURAÇÃO DE RESPOSTA A INCIDENTES")
    print("-" * 60)
    print("Execute no terminal local:")
    print()
    print("# 1. Criar playbook de resposta a incidentes")
    print("aws ssm create-document --name marabet-incident-response-playbook --document-type Command --content file://incident-response-playbook.json --region us-east-1")
    print()
    print("# 2. Configurar AWS Systems Manager Incident Manager")
    print("aws ssm create-response-plan --name marabet-incident-response-plan --incident-template file://incident-template.json --region us-east-1")
    print()
    print("# 3. Configurar AWS Systems Manager Automation")
    print("aws ssm create-automation --name marabet-security-automation --document-name marabet-security-automation --region us-east-1")
    print()
    print("# 4. Configurar AWS Systems Manager Run Command")
    print("aws ssm send-command --instance-ids i-0225f2fa806b1bf27 --document-name AWS-RunShellScript --parameters 'commands=[\"sudo systemctl restart nginx\",\"sudo systemctl restart docker\"]' --region us-east-1")
    print()
    print("# 5. Configurar AWS Systems Manager Patch Manager")
    print("aws ssm create-patch-baseline --name marabet-patch-baseline --description \"MaraBet AI Patch Baseline\" --region us-east-1")
    print()
    print("# 6. Configurar AWS Systems Manager Compliance")
    print("aws ssm create-association --name marabet-compliance-association --targets Key=InstanceIds,Values=i-0225f2fa806b1bf27 --schedule-expression \"rate(1 day)\" --region us-east-1")
    print()
    print("# 7. Configurar AWS Systems Manager Inventory")
    print("aws ssm create-association --name marabet-inventory-association --targets Key=InstanceIds,Values=i-0225f2fa806b1bf27 --schedule-expression \"rate(1 day)\" --region us-east-1")
    print()
    print("# 8. Configurar AWS Systems Manager Maintenance Windows")
    print("aws ssm create-maintenance-window --name marabet-maintenance-window --schedule \"cron(0 2 ? * SUN *)\" --duration 4 --cutoff 1 --region us-east-1")
    
    print("\n📋 ETAPA 7: CONFIGURAÇÃO DE COMPLIANCE E AUDITORIA")
    print("-" * 60)
    print("Execute no terminal local:")
    print()
    print("# 1. Configurar AWS Config Rules")
    print("aws configservice put-config-rule --config-rule name=marabet-config-rule,Source={\"Owner\":\"AWS\",\"SourceIdentifier\":\"S3_BUCKET_PUBLIC_READ_PROHIBITED\"} --region us-east-1")
    print()
    print("# 2. Configurar AWS Config Conformance Packs")
    print("aws configservice put-conformance-pack --conformance-pack-name marabet-conformance-pack --template-body file://conformance-pack-template.yaml --region us-east-1")
    print()
    print("# 3. Configurar AWS Config Aggregator")
    print("aws configservice put-configuration-aggregator --configuration-aggregator-name marabet-config-aggregator --account-aggregation-sources AccountIds=206749730888,AllAwsRegions=true --region us-east-1")
    print()
    print("# 4. Configurar AWS Config Delivery Channel")
    print("aws configservice put-delivery-channel --delivery-channel name=marabet-delivery-channel,s3BucketName=marabet-config-logs --region us-east-1")
    print()
    print("# 5. Configurar AWS Config Recorder")
    print("aws configservice put-configuration-recorder --configuration-recorder name=marabet-config-recorder,roleARN=arn:aws:iam::206749730888:role/ConfigRole --region us-east-1")
    print()
    print("# 6. Configurar AWS Config Source")
    print("aws configservice put-config-rule --config-rule name=marabet-config-rule,Source={\"Owner\":\"AWS\",\"SourceIdentifier\":\"S3_BUCKET_PUBLIC_READ_PROHIBITED\"} --region us-east-1")
    print()
    print("# 7. Configurar AWS Config Evaluation")
    print("aws configservice start-config-rules-evaluation --config-rule-names marabet-config-rule --region us-east-1")
    print()
    print("# 8. Configurar AWS Config Compliance")
    print("aws configservice get-compliance-summary-by-config-rule --region us-east-1")
    
    print("\n🎯 COMANDOS DE VERIFICAÇÃO DE SEGURANÇA:")
    print("-" * 60)
    print("Execute no terminal local:")
    print()
    print("# Verificar status do WAF")
    print("aws wafv2 list-web-acls --scope REGIONAL --region us-east-1")
    print()
    print("# Verificar status do Shield")
    print("aws shield describe-subscription --region us-east-1")
    print()
    print("# Verificar status do GuardDuty")
    print("aws guardduty list-detectors --region us-east-1")
    print()
    print("# Verificar status do Security Hub")
    print("aws securityhub describe-hub --region us-east-1")
    print()
    print("# Verificar status do Inspector")
    print("aws inspector list-assessment-targets --region us-east-1")
    print()
    print("# Verificar status do CloudTrail")
    print("aws cloudtrail describe-trails --region us-east-1")
    print()
    print("# Verificar status do Config")
    print("aws configservice describe-configuration-recorders --region us-east-1")
    print()
    print("# Verificar status do KMS")
    print("aws kms list-keys --region us-east-1")
    
    print("\n🚀 COMANDOS DE IMPLEMENTAÇÃO RÁPIDA:")
    print("-" * 60)
    print("Execute no terminal local:")
    print()
    print("# Implementar WAF completo")
    print("aws wafv2 create-web-acl --name marabet-waf-acl --scope REGIONAL --default-action Allow={} --rules file://waf-rules.json --region us-east-1 && aws wafv2 associate-web-acl --web-acl-arn arn:aws:wafv2:us-east-1:206749730888:regional/webacl/marabet-waf-acl/12345678-1234-1234-1234-123456789012 --resource-arn arn:aws:elasticloadbalancing:us-east-1:206749730888:loadbalancer/app/marabet-alb/1234567890abcdef --region us-east-1")
    print()
    print("# Implementar Shield completo")
    print("aws shield create-subscription --region us-east-1 && aws shield create-protection --name marabet-shield-protection --resource-arn arn:aws:elasticloadbalancing:us-east-1:206749730888:loadbalancer/app/marabet-alb/1234567890abcdef --region us-east-1")
    print()
    print("# Implementar Load Balancer com WAF")
    print("aws elbv2 create-load-balancer --name marabet-alb --subnets subnet-09d65bdd7b15819c4 subnet-0b3cec41b65c8a0a0 --security-groups sg-04b9744aba79e7514 --region us-east-1 && aws elbv2 create-target-group --name marabet-targets --protocol HTTP --port 8000 --vpc-id vpc-0c08de281a0a35d05 --health-check-path /health --region us-east-1")
    print()
    print("# Implementar monitoramento de segurança")
    print("aws cloudwatch put-dashboard --dashboard-name MaraBet-Security-Dashboard --dashboard-body file://security-dashboard.json --region us-east-1 && aws cloudwatch put-metric-alarm --alarm-name marabet-waf-blocked-requests --alarm-description \"WAF Blocked Requests\" --metric-name BlockedRequests --namespace AWS/WAFV2 --statistic Sum --period 300 --threshold 100 --comparison-operator GreaterThanThreshold --region us-east-1")
    print()
    print("# Implementar compliance e auditoria")
    print("aws configservice put-configuration-recorder --configuration-recorder name=marabet-config-recorder,roleARN=arn:aws:iam::206749730888:role/ConfigRole --region us-east-1 && aws configservice put-delivery-channel --delivery-channel name=marabet-delivery-channel,s3BucketName=marabet-config-logs --region us-east-1")
    print()
    print("# Implementar resposta a incidentes")
    print("aws ssm create-document --name marabet-incident-response-playbook --document-type Command --content file://incident-response-playbook.json --region us-east-1 && aws ssm create-response-plan --name marabet-incident-response-plan --incident-template file://incident-template.json --region us-east-1")
    print()
    print("# Implementar criptografia e secrets")
    print("aws kms create-key --description \"MaraBet AI Encryption Key\" --region us-east-1 && aws secretsmanager create-secret --name marabet-db-credentials --description \"MaraBet AI Database Credentials\" --secret-string '{\"username\":\"marabetadmin\",\"password\":\"MaraBet2024!SuperSecret\"}' --region us-east-1")
    print()
    print("# Implementar patch management")
    print("aws ssm create-patch-baseline --name marabet-patch-baseline --description \"MaraBet AI Patch Baseline\" --region us-east-1 && aws ssm create-maintenance-window --name marabet-maintenance-window --schedule \"cron(0 2 ? * SUN *)\" --duration 4 --cutoff 1 --region us-east-1")
    
    print("\n🎉 IMPLEMENTAÇÃO DE SEGURANÇA WAF E SHIELD CONSOLIDADA COM SUCESSO!")
    print("=" * 80)
    
    return True

def main():
    print("🚀 Iniciando implementação de segurança WAF e Shield...")
    
    # Criar implementação de segurança
    success = create_security_implementation()
    
    if success:
        print("\n🎯 IMPLEMENTAÇÃO DE SEGURANÇA WAF E SHIELD CONSOLIDADA COM SUCESSO!")
        print("Sistema completo e funcionando!")
    else:
        print("\n❌ Falha na implementação de segurança")
        print("Verifique os logs acima para mais detalhes")

if __name__ == "__main__":
    main()
