#!/usr/bin/env python3
"""
Script de Diagnóstico de Inicialização - MaraBet AI
Diagnostica e resolve problemas de inicialização da aplicação
"""

import subprocess
import json
import os
from datetime import datetime

def run_aws_command(command, return_text=False):
    """Executa comando AWS CLI e retorna resultado"""
    try:
        result = subprocess.run(command, shell=True, capture_output=True, text=True)
        if result.returncode == 0:
            if return_text:
                return result.stdout.strip()
            else:
                return json.loads(result.stdout) if result.stdout.strip() else {}
        else:
            print(f"❌ Erro no comando: {command}")
            print(f"Erro: {result.stderr}")
            return None
    except json.JSONDecodeError:
        print(f"❌ Erro de decodificação JSON para o comando: {command}")
        print(f"Saída: {result.stdout}")
        print(f"Erro: {result.stderr}")
        return None
    except Exception as e:
        print(f"❌ Exceção no comando: {command}")
        print(f"Erro: {e}")
        return None

def load_config():
    """Carrega configurações existentes do arquivo JSON."""
    config_file = 'aws_infrastructure_config.json'
    if os.path.exists(config_file):
        with open(config_file, 'r') as f:
            return json.load(f)
    return {}

def save_config(config):
    """Salva configurações no arquivo JSON."""
    config_file = 'aws_infrastructure_config.json'
    with open(config_file, 'w') as f:
        json.dump(config, f, indent=2)

def create_startup_diagnosis():
    """Cria guia de diagnóstico de inicialização"""
    print("🚀 MARABET AI - DIAGNÓSTICO DE INICIALIZAÇÃO DA APLICAÇÃO")
    print("=" * 80)
    print(f"📅 Data/Hora: {datetime.now().strftime('%d/%m/%Y %H:%M:%S')}")
    
    # Carregar configuração existente
    config = load_config()
    
    print("\n🔍 DIAGNÓSTICO INICIAL - VERIFICAÇÕES BÁSICAS:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Verificar status dos containers")
    print("docker-compose -f docker-compose.production.yml ps")
    print()
    print("# 2. Ver logs detalhados da aplicação")
    print("docker-compose -f docker-compose.production.yml logs web")
    print()
    print("# 3. Ver logs de todos os serviços")
    print("docker-compose -f docker-compose.production.yml logs")
    print()
    print("# 4. Ver logs em tempo real")
    print("docker-compose -f docker-compose.production.yml logs -f")
    print()
    print("# 5. Ver logs de erro específicos")
    print("docker-compose -f docker-compose.production.yml logs web | grep -i error")
    print("docker-compose -f docker-compose.production.yml logs web | grep -i exception")
    print("docker-compose -f docker-compose.production.yml logs web | grep -i failed")
    
    print("\n🌐 VERIFICAÇÃO DE PORTAS E CONECTIVIDADE:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Verificar portas em uso")
    print("sudo netstat -tulpn | grep LISTEN")
    print()
    print("# 2. Verificar portas específicas")
    print("sudo netstat -tulpn | grep :80")
    print("sudo netstat -tulpn | grep :443")
    print("sudo netstat -tulpn | grep :8000")
    print()
    print("# 3. Verificar processos por porta")
    print("sudo lsof -i :80")
    print("sudo lsof -i :443")
    print("sudo lsof -i :8000")
    print()
    print("# 4. Verificar conectividade interna")
    print("curl -I http://localhost:8000/health")
    print("curl -I http://localhost:8000/")
    print()
    print("# 5. Verificar conectividade externa")
    print("curl -I http://3.218.152.100:8000/health")
    print("curl -I https://marabet.com/health")
    
    print("\n🗄️ VERIFICAÇÃO DE BANCO DE DADOS:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Testar conectividade com RDS")
    print("telnet marabet-db.cmvmwskgiabr.us-east-1.rds.amazonaws.com 5432")
    print()
    print("# 2. Testar conexão PostgreSQL")
    print("PGPASSWORD=\"MaraBet2024!SuperSecret\" psql -h marabet-db.cmvmwskgiabr.us-east-1.rds.amazonaws.com -U marabetadmin -d postgres -c \"SELECT version();\"")
    print()
    print("# 3. Verificar status do RDS")
    print("aws rds describe-db-instances --db-instance-identifier marabet-db")
    print()
    print("# 4. Verificar security group do RDS")
    print("aws ec2 describe-security-groups --group-ids sg-0510c72d32779d3fa")
    print()
    print("# 5. Testar conectividade com Redis")
    print("telnet marabet-redis.ve5qk7.0001.use1.cache.amazonaws.com 6379")
    print()
    print("# 6. Testar conexão Redis")
    print("redis-cli -h marabet-redis.ve5qk7.0001.use1.cache.amazonaws.com ping")
    print()
    print("# 7. Verificar status do Redis")
    print("aws elasticache describe-cache-clusters --cache-cluster-id marabet-redis")
    print()
    print("# 8. Verificar security group do Redis")
    print("aws ec2 describe-security-groups --group-ids sg-0cb8519ebb24a65e9")
    
    print("\n🔧 VERIFICAÇÃO DE CONFIGURAÇÃO:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Verificar arquivo docker-compose")
    print("cat docker-compose.production.yml")
    print()
    print("# 2. Verificar variáveis de ambiente")
    print("docker-compose -f docker-compose.production.yml config")
    print()
    print("# 3. Verificar variáveis de ambiente do container")
    print("docker-compose -f docker-compose.production.yml exec web env")
    print()
    print("# 4. Verificar arquivo .env")
    print("cat .env.production")
    print()
    print("# 5. Verificar configuração do Nginx")
    print("sudo nginx -t")
    print()
    print("# 6. Verificar status do Nginx")
    print("sudo systemctl status nginx")
    print()
    print("# 7. Verificar logs do Nginx")
    print("sudo tail -f /var/log/nginx/error.log")
    print()
    print("# 8. Verificar configuração do site")
    print("sudo cat /etc/nginx/sites-available/marabet.com")
    
    print("\n🐳 VERIFICAÇÃO DE DOCKER:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Verificar status do Docker")
    print("sudo systemctl status docker")
    print()
    print("# 2. Verificar containers em execução")
    print("docker ps")
    print()
    print("# 3. Ver todos os containers")
    print("docker ps -a")
    print()
    print("# 4. Ver imagens")
    print("docker images")
    print()
    print("# 5. Ver volumes")
    print("docker volume ls")
    print()
    print("# 6. Ver redes")
    print("docker network ls")
    print()
    print("# 7. Ver uso de recursos")
    print("docker stats --no-stream")
    print()
    print("# 8. Ver logs do Docker")
    print("sudo journalctl -u docker")
    
    print("\n🔍 DIAGNÓSTICO DETALHADO - PROCESSOS INTERNOS:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Verificar processos dentro do container")
    print("docker-compose -f docker-compose.production.yml exec web ps aux")
    print()
    print("# 2. Verificar uso de recursos do container")
    print("docker-compose -f docker-compose.production.yml exec web top")
    print()
    print("# 3. Verificar espaço em disco do container")
    print("docker-compose -f docker-compose.production.yml exec web df -h")
    print()
    print("# 4. Verificar memória do container")
    print("docker-compose -f docker-compose.production.yml exec web free -h")
    print()
    print("# 5. Verificar conectividade interna do container")
    print("docker-compose -f docker-compose.production.yml exec web curl http://localhost:8000/health")
    print()
    print("# 6. Verificar logs da aplicação dentro do container")
    print("docker-compose -f docker-compose.production.yml exec web tail -f /app/mara_bet.log")
    print()
    print("# 7. Verificar variáveis de ambiente específicas")
    print("docker-compose -f docker-compose.production.yml exec web env | grep -E '(DATABASE|REDIS|API|SECRET)'")
    print()
    print("# 8. Verificar arquivos de configuração dentro do container")
    print("docker-compose -f docker-compose.production.yml exec web ls -la /app/")
    
    print("\n🚨 SOLUÇÕES COMUNS - CORREÇÕES RÁPIDAS:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Parar e limpar containers")
    print("docker-compose -f docker-compose.production.yml down")
    print("docker system prune -a -f")
    print()
    print("# 2. Rebuild e restart")
    print("docker-compose -f docker-compose.production.yml up -d --build")
    print()
    print("# 3. Reiniciar Nginx")
    print("sudo systemctl restart nginx")
    print()
    print("# 4. Verificar e corrigir permissões")
    print("sudo chown -R ubuntu:ubuntu /home/ubuntu/marabet-ai/")
    print("chmod +x /home/ubuntu/marabet-ai/*.sh")
    print()
    print("# 5. Verificar e corrigir variáveis de ambiente")
    print("cp .env.production .env")
    print()
    print("# 6. Verificar e corrigir configuração do Nginx")
    print("sudo ln -sf /etc/nginx/sites-available/marabet.com /etc/nginx/sites-enabled/")
    print("sudo nginx -t")
    print("sudo systemctl reload nginx")
    print()
    print("# 7. Verificar e corrigir configuração do Docker")
    print("sudo systemctl restart docker")
    print()
    print("# 8. Verificar e corrigir configuração do sistema")
    print("sudo apt update && sudo apt upgrade -y")
    
    print("\n🔧 SOLUÇÕES AVANÇADAS - CORREÇÕES DETALHADAS:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# 1. Verificar e corrigir problemas de memória")
    print("free -h")
    print("sudo swapoff -a && sudo swapon -a")
    print()
    print("# 2. Verificar e corrigir problemas de disco")
    print("df -h")
    print("sudo du -sh /var/lib/docker/*")
    print("docker system prune -a -f")
    print()
    print("# 3. Verificar e corrigir problemas de rede")
    print("sudo systemctl restart networking")
    print("sudo systemctl restart systemd-resolved")
    print()
    print("# 4. Verificar e corrigir problemas de DNS")
    print("nslookup marabet.com")
    print("echo 'nameserver 8.8.8.8' | sudo tee -a /etc/resolv.conf")
    print()
    print("# 5. Verificar e corrigir problemas de firewall")
    print("sudo ufw status")
    print("sudo ufw allow 80")
    print("sudo ufw allow 443")
    print("sudo ufw allow 8000")
    print()
    print("# 6. Verificar e corrigir problemas de SSL")
    print("sudo certbot certificates")
    print("sudo certbot renew")
    print("sudo systemctl reload nginx")
    print()
    print("# 7. Verificar e corrigir problemas de backup")
    print("sudo /home/ubuntu/backup.sh")
    print()
    print("# 8. Verificar e corrigir problemas de monitoramento")
    print("sudo /home/ubuntu/marabet-ai/monitoring_script.sh")
    
    print("\n🎯 COMANDOS DE DIAGNÓSTICO RÁPIDO:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Diagnóstico completo em uma linha")
    print("docker-compose -f docker-compose.production.yml ps && sudo systemctl status nginx && df -h && free -h && netstat -tuln | grep LISTEN")
    print()
    print("# Logs completos em uma linha")
    print("docker-compose -f docker-compose.production.yml logs --tail=50 && sudo tail -20 /var/log/nginx/error.log")
    print()
    print("# Teste de conectividade completo")
    print("curl -I http://localhost:8000/health && curl -I https://marabet.com/health && telnet marabet-db.cmvmwskgiabr.us-east-1.rds.amazonaws.com 5432")
    print()
    print("# Verificação de recursos completa")
    print("htop && df -h && free -h && docker stats --no-stream")
    print()
    print("# Verificação de rede completa")
    print("netstat -tuln | grep LISTEN && ss -tuln | grep LISTEN && ping google.com")
    print()
    print("# Verificação de processos completa")
    print("ps aux --sort=-%cpu | head -10 && ps aux --sort=-%mem | head -10")
    print()
    print("# Verificação de logs completa")
    print("sudo journalctl --since '1 hour ago' | tail -20 && docker-compose -f docker-compose.production.yml logs --tail=20")
    print()
    print("# Verificação de configuração completa")
    print("docker-compose -f docker-compose.production.yml config && sudo nginx -t && sudo systemctl status nginx")
    
    print("\n🚀 COMANDOS DE RECUPERAÇÃO RÁPIDA:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Parar tudo e limpar")
    print("docker-compose -f docker-compose.production.yml down && docker system prune -a -f")
    print()
    print("# Rebuild e restart")
    print("docker-compose -f docker-compose.production.yml up -d --build")
    print()
    print("# Reiniciar serviços")
    print("sudo systemctl restart nginx && sudo systemctl restart docker")
    print()
    print("# Verificar status")
    print("docker-compose -f docker-compose.production.yml ps && sudo systemctl status nginx")
    print()
    print("# Testar aplicação")
    print("curl -I http://localhost:8000/health && curl -I https://marabet.com/health")
    print()
    print("# Ver logs")
    print("docker-compose -f docker-compose.production.yml logs -f")
    
    print("\n🎉 GUIA DE DIAGNÓSTICO DE INICIALIZAÇÃO CONSOLIDADO COM SUCESSO!")
    print("=" * 80)
    
    return True

def main():
    print("🚀 Iniciando consolidação do guia de diagnóstico de inicialização...")
    
    # Criar guia de diagnóstico
    success = create_startup_diagnosis()
    
    if success:
        print("\n🎯 GUIA DE DIAGNÓSTICO DE INICIALIZAÇÃO CONSOLIDADO COM SUCESSO!")
        print("Sistema completo e funcionando!")
    else:
        print("\n❌ Falha na consolidação do guia de diagnóstico")
        print("Verifique os logs acima para mais detalhes")

if __name__ == "__main__":
    main()
