#!/usr/bin/env python3
"""
Script de Troubleshooting - MaraBet AI
Consolida todos os comandos para resolver problemas comuns
"""

import subprocess
import json
import os
from datetime import datetime

def run_aws_command(command, return_text=False):
    """Executa comando AWS CLI e retorna resultado"""
    try:
        result = subprocess.run(command, shell=True, capture_output=True, text=True)
        if result.returncode == 0:
            if return_text:
                return result.stdout.strip()
            else:
                return json.loads(result.stdout) if result.stdout.strip() else {}
        else:
            print(f"❌ Erro no comando: {command}")
            print(f"Erro: {result.stderr}")
            return None
    except json.JSONDecodeError:
        print(f"❌ Erro de decodificação JSON para o comando: {command}")
        print(f"Saída: {result.stdout}")
        print(f"Erro: {result.stderr}")
        return None
    except Exception as e:
        print(f"❌ Exceção no comando: {command}")
        print(f"Erro: {e}")
        return None

def load_config():
    """Carrega configurações existentes do arquivo JSON."""
    config_file = 'aws_infrastructure_config.json'
    if os.path.exists(config_file):
        with open(config_file, 'r') as f:
            return json.load(f)
    return {}

def save_config(config):
    """Salva configurações no arquivo JSON."""
    config_file = 'aws_infrastructure_config.json'
    with open(config_file, 'w') as f:
        json.dump(config, f, indent=2)

def create_troubleshooting_guide():
    """Cria guia de troubleshooting"""
    print("🔧 MARABET AI - GUIA DE TROUBLESHOOTING")
    print("=" * 80)
    print(f"📅 Data/Hora: {datetime.now().strftime('%d/%m/%Y %H:%M:%S')}")
    
    # Carregar configuração existente
    config = load_config()
    
    print("\n🔌 SSH - PROBLEMAS DE CONECTIVIDADE:")
    print("-" * 60)
    print("Execute no terminal local:")
    print()
    print("# Verificar security group")
    print("aws ec2 describe-security-groups --group-ids sg-07f7e19db4e1e8f78")
    print()
    print("# Adicionar regra SSH se necessário")
    print("aws ec2 authorize-security-group-ingress --group-id sg-07f7e19db4e1e8f78 --protocol tcp --port 22 --cidr 0.0.0.0/0")
    print()
    print("# Verificar status da instância")
    print("aws ec2 describe-instances --instance-ids i-0225f2fa806b1bf27")
    print()
    print("# Verificar chave SSH")
    print("ls -la ~/.ssh/marabet-key.pem")
    print()
    print("# Verificar permissões da chave")
    print("chmod 400 ~/.ssh/marabet-key.pem")
    print()
    print("# Testar conectividade")
    print("ping 3.218.152.100")
    print()
    print("# Testar porta SSH")
    print("telnet 3.218.152.100 22")
    print()
    print("# Conectar via SSH")
    print("ssh -i ~/.ssh/marabet-key.pem ubuntu@3.218.152.100")
    print()
    print("# Verificar logs de SSH no servidor")
    print("sudo tail -f /var/log/auth.log")
    print()
    print("# Verificar configuração SSH")
    print("sudo cat /etc/ssh/sshd_config")
    
    print("\n🌐 NGINX - PROBLEMAS DE PROXY:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Verificar status do Nginx")
    print("sudo systemctl status nginx")
    print()
    print("# Verificar configuração")
    print("sudo nginx -t")
    print()
    print("# Ver logs de erro")
    print("sudo tail -f /var/log/nginx/error.log")
    print()
    print("# Ver logs de acesso")
    print("sudo tail -f /var/log/nginx/access.log")
    print()
    print("# Verificar se está rodando")
    print("sudo netstat -tuln | grep :80")
    print("sudo netstat -tuln | grep :443")
    print()
    print("# Reiniciar Nginx")
    print("sudo systemctl restart nginx")
    print()
    print("# Verificar configuração do site")
    print("sudo cat /etc/nginx/sites-available/marabet.com")
    print()
    print("# Verificar se site está habilitado")
    print("ls -la /etc/nginx/sites-enabled/")
    print()
    print("# Habilitar site")
    print("sudo ln -sf /etc/nginx/sites-available/marabet.com /etc/nginx/sites-enabled/")
    print()
    print("# Recarregar configuração")
    print("sudo systemctl reload nginx")
    
    print("\n🐳 DOCKER - PROBLEMAS DE CONTAINERS:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Ver status dos containers")
    print("docker-compose -f docker-compose.production.yml ps")
    print()
    print("# Ver logs dos containers")
    print("docker-compose -f docker-compose.production.yml logs")
    print()
    print("# Ver logs de um container específico")
    print("docker-compose -f docker-compose.production.yml logs web")
    print()
    print("# Reiniciar containers")
    print("docker-compose -f docker-compose.production.yml restart")
    print()
    print("# Parar e iniciar containers")
    print("docker-compose -f docker-compose.production.yml down")
    print("docker-compose -f docker-compose.production.yml up -d")
    print()
    print("# Rebuild containers")
    print("docker-compose -f docker-compose.production.yml up -d --build")
    print()
    print("# Ver uso de recursos")
    print("docker stats")
    print()
    print("# Ver containers parados")
    print("docker ps -a")
    print()
    print("# Limpar containers antigos")
    print("docker system prune -a")
    print()
    print("# Ver logs do Docker")
    print("sudo journalctl -u docker")
    
    print("\n🗄️ BANCO DE DADOS - PROBLEMAS DE CONECTIVIDADE:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Testar conectividade com RDS")
    print("PGPASSWORD=\"MaraBet2024!SuperSecret\" psql -h marabet-db.cmvmwskgiabr.us-east-1.rds.amazonaws.com -U marabetadmin -d postgres -c \"SELECT version();\"")
    print()
    print("# Verificar status do RDS")
    print("aws rds describe-db-instances --db-instance-identifier marabet-db")
    print()
    print("# Verificar security group do RDS")
    print("aws ec2 describe-security-groups --group-ids sg-0510c72d32779d3fa")
    print()
    print("# Testar conectividade com Redis")
    print("redis-cli -h marabet-redis.ve5qk7.0001.use1.cache.amazonaws.com ping")
    print()
    print("# Verificar status do Redis")
    print("aws elasticache describe-cache-clusters --cache-cluster-id marabet-redis")
    print()
    print("# Verificar security group do Redis")
    print("aws ec2 describe-security-groups --group-ids sg-0cb8519ebb24a65e9")
    print()
    print("# Verificar logs do banco")
    print("docker-compose -f docker-compose.production.yml logs web | grep -i database")
    print()
    print("# Verificar variáveis de ambiente")
    print("docker-compose -f docker-compose.production.yml exec web env | grep -i database")
    
    print("\n🔒 SSL - PROBLEMAS DE CERTIFICADO:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Verificar certificados")
    print("sudo certbot certificates")
    print()
    print("# Verificar expiração")
    print("openssl x509 -in /etc/letsencrypt/live/marabet.com/fullchain.pem -dates -noout")
    print()
    print("# Renovar certificados")
    print("sudo certbot renew")
    print()
    print("# Testar renovação")
    print("sudo certbot renew --dry-run")
    print()
    print("# Ver logs do Certbot")
    print("sudo tail -f /var/log/letsencrypt/letsencrypt.log")
    print()
    print("# Verificar configuração SSL no Nginx")
    print("sudo nginx -t")
    print()
    print("# Recarregar Nginx após renovação")
    print("sudo systemctl reload nginx")
    print()
    print("# Testar HTTPS")
    print("curl -I https://marabet.com")
    print()
    print("# Verificar certificado via OpenSSL")
    print("openssl s_client -connect marabet.com:443 -servername marabet.com")
    
    print("\n💾 BACKUP - PROBLEMAS DE BACKUP:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Verificar cron job")
    print("crontab -l | grep backup")
    print()
    print("# Executar backup manual")
    print("sudo /home/ubuntu/backup.sh")
    print()
    print("# Ver logs de backup")
    print("tail -f /var/log/marabet_backup.log")
    print()
    print("# Verificar diretório de backup")
    print("ls -la /home/ubuntu/backups/")
    print()
    print("# Verificar espaço em disco")
    print("df -h")
    print()
    print("# Verificar integridade do backup")
    print("tar -tzf /home/ubuntu/backups/backup_YYYYMMDD_HHMMSS.tar.gz")
    print()
    print("# Verificar upload para S3")
    print("aws s3 ls s3://marabet-backups/backups/")
    print()
    print("# Testar conectividade com S3")
    print("aws s3 ls s3://marabet-backups/")
    print()
    print("# Verificar permissões do script")
    print("ls -la /home/ubuntu/backup.sh")
    print()
    print("# Dar permissão de execução")
    print("chmod +x /home/ubuntu/backup.sh")
    
    print("\n📱 TELEGRAM - PROBLEMAS DE NOTIFICAÇÃO:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Verificar configuração")
    print("cat /home/ubuntu/marabet-ai/telegram_config.json")
    print()
    print("# Testar envio de mensagem")
    print("python3 /home/ubuntu/marabet-ai/send_telegram_direct.py")
    print()
    print("# Ver logs do Telegram")
    print("tail -f /var/log/marabet_telegram.log")
    print()
    print("# Verificar bot")
    print("curl https://api.telegram.org/bot<TOKEN>/getMe")
    print()
    print("# Verificar webhook")
    print("curl https://api.telegram.org/bot<TOKEN>/getWebhookInfo")
    print()
    print("# Testar conectividade")
    print("curl -I https://api.telegram.org")
    print()
    print("# Verificar logs de aplicação")
    print("docker-compose -f docker-compose.production.yml logs web | grep -i telegram")
    print()
    print("# Verificar variáveis de ambiente")
    print("docker-compose -f docker-compose.production.yml exec web env | grep -i telegram")
    
    print("\n🌐 APLICAÇÃO - PROBLEMAS DE FUNCIONAMENTO:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Verificar status da aplicação")
    print("curl -I http://localhost:8000/health")
    print()
    print("# Verificar status via HTTPS")
    print("curl -I https://marabet.com/health")
    print()
    print("# Ver logs da aplicação")
    print("docker-compose -f docker-compose.production.yml logs web")
    print()
    print("# Ver logs de erro")
    print("docker-compose -f docker-compose.production.yml logs web | grep -i error")
    print()
    print("# Verificar variáveis de ambiente")
    print("docker-compose -f docker-compose.production.yml exec web env")
    print()
    print("# Verificar conectividade interna")
    print("docker-compose -f docker-compose.production.yml exec web curl http://localhost:8000/health")
    print()
    print("# Verificar processos dentro do container")
    print("docker-compose -f docker-compose.production.yml exec web ps aux")
    print()
    print("# Verificar uso de recursos")
    print("docker stats marabet-ai_web_1")
    print()
    print("# Reiniciar aplicação")
    print("docker-compose -f docker-compose.production.yml restart web")
    
    print("\n📊 MONITORAMENTO - PROBLEMAS DE ALERTAS:")
    print("-" * 60)
    print("Execute no terminal local:")
    print()
    print("# Verificar alarmes CloudWatch")
    print("aws cloudwatch describe-alarms --alarm-names marabet-web-high-cpu")
    print()
    print("# Verificar status dos alarmes")
    print("aws cloudwatch describe-alarms --state-value ALARM")
    print()
    print("# Verificar métricas")
    print("aws cloudwatch get-metric-statistics --namespace AWS/EC2 --metric-name CPUUtilization --dimensions Name=InstanceId,Value=i-0225f2fa806b1bf27 --start-time 2024-01-01T00:00:00Z --end-time 2024-01-02T00:00:00Z --period 3600 --statistics Average")
    print()
    print("# Verificar subscrições SNS")
    print("aws sns list-subscriptions-by-topic --topic-arn arn:aws:sns:us-east-1:206749730888:marabet-alerts")
    print()
    print("# Verificar dashboard")
    print("aws cloudwatch get-dashboard --dashboard-name MaraBet-AI-Dashboard")
    print()
    print("# Verificar logs do CloudWatch")
    print("aws logs describe-log-groups")
    print()
    print("# Verificar métricas customizadas")
    print("aws cloudwatch list-metrics --namespace MaraBet-AI")
    
    print("\n🔧 SISTEMA - PROBLEMAS GERAIS:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Verificar espaço em disco")
    print("df -h")
    print()
    print("# Verificar memória")
    print("free -h")
    print()
    print("# Verificar CPU")
    print("top -bn1 | head -20")
    print()
    print("# Verificar processos")
    print("ps aux --sort=-%cpu | head -10")
    print()
    print("# Verificar logs do sistema")
    print("sudo journalctl --since '1 hour ago'")
    print()
    print("# Verificar conectividade de rede")
    print("ping google.com")
    print()
    print("# Verificar DNS")
    print("nslookup marabet.com")
    print()
    print("# Verificar firewall")
    print("sudo ufw status")
    print()
    print("# Verificar serviços")
    print("sudo systemctl status nginx docker")
    print()
    print("# Verificar cron jobs")
    print("crontab -l")
    
    print("\n🚨 EMERGÊNCIA - COMANDOS DE RECUPERAÇÃO:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Parar tudo")
    print("docker-compose -f docker-compose.production.yml down")
    print("sudo systemctl stop nginx")
    print()
    print("# Limpar tudo")
    print("docker system prune -a -f")
    print("docker volume prune -f")
    print()
    print("# Restaurar do backup")
    print("sudo /home/ubuntu/marabet-ai/restore_script.sh backup_YYYYMMDD_HHMMSS.tar.gz")
    print()
    print("# Reiniciar tudo")
    print("sudo systemctl start nginx")
    print("docker-compose -f docker-compose.production.yml up -d")
    print()
    print("# Verificar status")
    print("docker-compose -f docker-compose.production.yml ps")
    print("sudo systemctl status nginx")
    print()
    print("# Testar aplicação")
    print("curl -I http://localhost:8000/health")
    print("curl -I https://marabet.com/health")
    
    print("\n🎯 COMANDOS RÁPIDOS - TROUBLESHOOTING:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Diagnóstico completo")
    print("docker-compose -f docker-compose.production.yml ps && sudo systemctl status nginx && df -h && free -h")
    print()
    print("# Logs completos")
    print("docker-compose -f docker-compose.production.yml logs --tail=50 && sudo tail -20 /var/log/nginx/error.log")
    print()
    print("# Teste de conectividade")
    print("curl -I http://localhost:8000/health && curl -I https://marabet.com/health")
    print()
    print("# Verificação de recursos")
    print("htop && df -h && free -h")
    print()
    print("# Verificação de rede")
    print("netstat -tuln | grep LISTEN && ss -tuln | grep LISTEN")
    print()
    print("# Verificação de processos")
    print("ps aux --sort=-%cpu | head -10 && ps aux --sort=-%mem | head -10")
    print()
    print("# Verificação de logs")
    print("sudo journalctl --since '1 hour ago' | tail -20")
    print()
    print("# Verificação de backup")
    print("ls -la /home/ubuntu/backups/ && tail -20 /var/log/marabet_backup.log")
    
    print("\n🎉 GUIA DE TROUBLESHOOTING CONSOLIDADO COM SUCESSO!")
    print("=" * 80)
    
    return True

def main():
    print("🚀 Iniciando consolidação do guia de troubleshooting...")
    
    # Criar guia de troubleshooting
    success = create_troubleshooting_guide()
    
    if success:
        print("\n🎯 GUIA DE TROUBLESHOOTING CONSOLIDADO COM SUCESSO!")
        print("Sistema completo e funcionando!")
    else:
        print("\n❌ Falha na consolidação do guia de troubleshooting")
        print("Verifique os logs acima para mais detalhes")

if __name__ == "__main__":
    main()
