#!/usr/bin/env python3
"""
Script de Comandos Úteis - MaraBet AI
Consolida todos os comandos úteis para gerenciar a aplicação
"""

import subprocess
import json
import os
from datetime import datetime

def run_aws_command(command, return_text=False):
    """Executa comando AWS CLI e retorna resultado"""
    try:
        result = subprocess.run(command, shell=True, capture_output=True, text=True)
        if result.returncode == 0:
            if return_text:
                return result.stdout.strip()
            else:
                return json.loads(result.stdout) if result.stdout.strip() else {}
        else:
            print(f"❌ Erro no comando: {command}")
            print(f"Erro: {result.stderr}")
            return None
    except json.JSONDecodeError:
        print(f"❌ Erro de decodificação JSON para o comando: {command}")
        print(f"Saída: {result.stdout}")
        print(f"Erro: {result.stderr}")
        return None
    except Exception as e:
        print(f"❌ Exceção no comando: {command}")
        print(f"Erro: {e}")
        return None

def load_config():
    """Carrega configurações existentes do arquivo JSON."""
    config_file = 'aws_infrastructure_config.json'
    if os.path.exists(config_file):
        with open(config_file, 'r') as f:
            return json.load(f)
    return {}

def save_config(config):
    """Salva configurações no arquivo JSON."""
    config_file = 'aws_infrastructure_config.json'
    with open(config_file, 'w') as f:
        json.dump(config, f, indent=2)

def create_useful_commands():
    """Cria resumo de comandos úteis"""
    print("🔧 MARABET AI - COMANDOS ÚTEIS PARA GERENCIAMENTO")
    print("=" * 80)
    print(f"📅 Data/Hora: {datetime.now().strftime('%d/%m/%Y %H:%M:%S')}")
    
    # Carregar configuração existente
    config = load_config()
    
    print("\n🐳 DOCKER - GERENCIAR APLICAÇÃO:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Ver logs em tempo real")
    print("docker-compose -f docker-compose.production.yml logs -f")
    print()
    print("# Ver logs de um serviço específico")
    print("docker-compose -f docker-compose.production.yml logs -f web")
    print("docker-compose -f docker-compose.production.yml logs -f redis")
    print()
    print("# Reiniciar todos os serviços")
    print("docker-compose -f docker-compose.production.yml restart")
    print()
    print("# Reiniciar um serviço específico")
    print("docker-compose -f docker-compose.production.yml restart web")
    print()
    print("# Parar todos os serviços")
    print("docker-compose -f docker-compose.production.yml down")
    print()
    print("# Parar e remover volumes")
    print("docker-compose -f docker-compose.production.yml down -v")
    print()
    print("# Rebuild e restart")
    print("docker-compose -f docker-compose.production.yml up -d --build")
    print()
    print("# Iniciar serviços")
    print("docker-compose -f docker-compose.production.yml up -d")
    print()
    print("# Ver status dos serviços")
    print("docker-compose -f docker-compose.production.yml ps")
    print()
    print("# Executar comando em container")
    print("docker-compose -f docker-compose.production.yml exec web bash")
    print("docker-compose -f docker-compose.production.yml exec web python manage.py migrate")
    print()
    print("# Limpar containers antigos")
    print("docker system prune -a")
    print()
    print("# Limpar volumes não utilizados")
    print("docker volume prune")
    print()
    print("# Ver uso de recursos")
    print("docker stats")
    print()
    print("# Ver imagens")
    print("docker images")
    print()
    print("# Ver containers")
    print("docker ps -a")
    
    print("\n🌐 NGINX - GERENCIAR PROXY:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Ver status do Nginx")
    print("sudo systemctl status nginx")
    print()
    print("# Iniciar Nginx")
    print("sudo systemctl start nginx")
    print()
    print("# Parar Nginx")
    print("sudo systemctl stop nginx")
    print()
    print("# Reiniciar Nginx")
    print("sudo systemctl restart nginx")
    print()
    print("# Recarregar configuração")
    print("sudo systemctl reload nginx")
    print()
    print("# Testar configuração")
    print("sudo nginx -t")
    print()
    print("# Ver logs de acesso")
    print("sudo tail -f /var/log/nginx/access.log")
    print()
    print("# Ver logs de erro")
    print("sudo tail -f /var/log/nginx/error.log")
    print()
    print("# Ver configuração")
    print("sudo cat /etc/nginx/sites-available/marabet.com")
    print()
    print("# Habilitar site")
    print("sudo ln -sf /etc/nginx/sites-available/marabet.com /etc/nginx/sites-enabled/")
    print()
    print("# Desabilitar site")
    print("sudo rm /etc/nginx/sites-enabled/marabet.com")
    
    print("\n🔒 SSL - GERENCIAR CERTIFICADOS:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Ver certificados")
    print("sudo certbot certificates")
    print()
    print("# Renovar certificados")
    print("sudo certbot renew")
    print()
    print("# Testar renovação")
    print("sudo certbot renew --dry-run")
    print()
    print("# Verificar status")
    print("sudo certbot certificates --cert-name marabet.com")
    print()
    print("# Ver logs do Certbot")
    print("sudo tail -f /var/log/letsencrypt/letsencrypt.log")
    print()
    print("# Verificar certificado")
    print("openssl x509 -in /etc/letsencrypt/live/marabet.com/fullchain.pem -text -noout")
    print()
    print("# Verificar expiração")
    print("openssl x509 -in /etc/letsencrypt/live/marabet.com/fullchain.pem -dates -noout")
    
    print("\n💾 BACKUP - GERENCIAR BACKUPS:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Executar backup manual")
    print("sudo /home/ubuntu/backup.sh")
    print()
    print("# Ver logs de backup")
    print("tail -f /var/log/marabet_backup.log")
    print()
    print("# Ver diretório de backup")
    print("ls -la /home/ubuntu/backups/")
    print()
    print("# Ver tamanho dos backups")
    print("du -sh /home/ubuntu/backups/*")
    print()
    print("# Verificar integridade")
    print("tar -tzf /home/ubuntu/backups/backup_YYYYMMDD_HHMMSS.tar.gz")
    print()
    print("# Restaurar banco de dados")
    print("PGPASSWORD=\"MaraBet2024!SuperSecret\" psql -h marabet-db.cmvmwskgiabr.us-east-1.rds.amazonaws.com -U marabetadmin -d postgres < /home/ubuntu/backups/db_YYYYMMDD_HHMMSS.sql")
    print()
    print("# Verificar cron job")
    print("crontab -l | grep backup")
    print()
    print("# Verificar espaço em disco")
    print("df -h")
    
    print("\n🔄 ATUALIZAÇÕES - GERENCIAR SISTEMA:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Atualizar sistema")
    print("sudo apt update && sudo apt upgrade -y")
    print()
    print("# Atualizar aplicação")
    print("sudo /home/ubuntu/marabet-ai/app_update_script.sh")
    print()
    print("# Verificar segurança")
    print("sudo /home/ubuntu/marabet-ai/security_check_script.sh")
    print()
    print("# Executar monitoramento")
    print("sudo /home/ubuntu/marabet-ai/monitoring_script.sh")
    print()
    print("# Ver logs de atualização")
    print("tail -f /var/log/marabet_system_updates.log")
    print("tail -f /var/log/marabet_app_updates.log")
    print("tail -f /var/log/marabet_security.log")
    print("tail -f /var/log/marabet_monitoring.log")
    print()
    print("# Verificar cron jobs")
    print("crontab -l")
    print()
    print("# Verificar espaço em disco")
    print("df -h")
    print()
    print("# Verificar memória")
    print("free -h")
    print()
    print("# Verificar processos")
    print("ps aux | grep -E '(python|node|java)'")
    
    print("\n📊 MONITORAMENTO - VERIFICAR SISTEMA:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Ver status dos serviços")
    print("sudo systemctl status nginx")
    print("sudo systemctl status docker")
    print()
    print("# Ver logs do sistema")
    print("sudo journalctl -u nginx -f")
    print("sudo journalctl -u docker -f")
    print()
    print("# Ver uso de recursos")
    print("htop")
    print("iotop")
    print()
    print("# Ver conexões de rede")
    print("netstat -tuln")
    print("ss -tuln")
    print()
    print("# Ver processos por porta")
    print("sudo lsof -i :80")
    print("sudo lsof -i :443")
    print("sudo lsof -i :8000")
    print()
    print("# Ver logs de aplicação")
    print("docker-compose -f docker-compose.production.yml logs --tail=100")
    print()
    print("# Ver métricas do Docker")
    print("docker stats --no-stream")
    
    print("\n🔍 DEBUGGING - RESOLVER PROBLEMAS:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Ver logs de erro")
    print("sudo tail -f /var/log/nginx/error.log")
    print("sudo tail -f /var/log/syslog")
    print()
    print("# Verificar conectividade")
    print("curl -I http://localhost:8000/health")
    print("curl -I https://marabet.com/health")
    print()
    print("# Verificar DNS")
    print("nslookup marabet.com")
    print("dig marabet.com")
    print()
    print("# Verificar certificado SSL")
    print("openssl s_client -connect marabet.com:443 -servername marabet.com")
    print()
    print("# Verificar banco de dados")
    print("PGPASSWORD=\"MaraBet2024!SuperSecret\" psql -h marabet-db.cmvmwskgiabr.us-east-1.rds.amazonaws.com -U marabetadmin -d postgres -c \"SELECT version();\"")
    print()
    print("# Verificar Redis")
    print("redis-cli -h marabet-redis.ve5qk7.0001.use1.cache.amazonaws.com ping")
    print()
    print("# Verificar conectividade AWS")
    print("aws sts get-caller-identity")
    print("aws s3 ls s3://marabet-backups/")
    print()
    print("# Verificar alarmes CloudWatch")
    print("aws cloudwatch describe-alarms --alarm-names marabet-web-high-cpu")
    print()
    print("# Verificar subscrições SNS")
    print("aws sns list-subscriptions-by-topic --topic-arn arn:aws:sns:us-east-1:206749730888:marabet-alerts")
    
    print("\n🚀 DEPLOYMENT - IMPLANTAÇÃO:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Fazer backup antes do deploy")
    print("sudo /home/ubuntu/backup.sh")
    print()
    print("# Parar aplicação")
    print("docker-compose -f docker-compose.production.yml down")
    print()
    print("# Atualizar código")
    print("cd /home/ubuntu/marabet-ai")
    print("git pull origin main")
    print()
    print("# Rebuild e restart")
    print("docker-compose -f docker-compose.production.yml up -d --build")
    print()
    print("# Verificar status")
    print("docker-compose -f docker-compose.production.yml ps")
    print()
    print("# Testar aplicação")
    print("curl -I http://localhost:8000/health")
    print("curl -I https://marabet.com/health")
    print()
    print("# Ver logs")
    print("docker-compose -f docker-compose.production.yml logs -f")
    
    print("\n🔧 MANUTENÇÃO - MANTER SISTEMA:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Limpar logs antigos")
    print("sudo find /var/log -name \"*.log\" -mtime +30 -delete")
    print()
    print("# Limpar backups antigos")
    print("find /home/ubuntu/backups -name \"*.tar.gz\" -mtime +7 -delete")
    print()
    print("# Limpar containers antigos")
    print("docker system prune -a -f")
    print()
    print("# Limpar volumes não utilizados")
    print("docker volume prune -f")
    print()
    print("# Limpar imagens não utilizadas")
    print("docker image prune -a -f")
    print()
    print("# Verificar espaço em disco")
    print("df -h")
    print()
    print("# Verificar memória")
    print("free -h")
    print()
    print("# Verificar processos")
    print("ps aux --sort=-%mem | head -10")
    print()
    print("# Verificar conexões")
    print("netstat -tuln | grep LISTEN")
    print()
    print("# Verificar cron jobs")
    print("crontab -l")
    print()
    print("# Verificar logs de sistema")
    print("sudo journalctl --since \"1 hour ago\"")
    
    print("\n📱 TELEGRAM - GERENCIAR NOTIFICAÇÕES:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Ver configuração do Telegram")
    print("cat /home/ubuntu/marabet-ai/telegram_config.json")
    print()
    print("# Testar envio de mensagem")
    print("python3 /home/ubuntu/marabet-ai/send_telegram_direct.py")
    print()
    print("# Ver logs do Telegram")
    print("tail -f /var/log/marabet_telegram.log")
    print()
    print("# Verificar bot")
    print("curl https://api.telegram.org/bot<TOKEN>/getMe")
    print()
    print("# Verificar webhook")
    print("curl https://api.telegram.org/bot<TOKEN>/getWebhookInfo")
    
    print("\n🎯 COMANDOS RÁPIDOS - RESUMO:")
    print("-" * 60)
    print("Execute no servidor Ubuntu:")
    print()
    print("# Status completo")
    print("docker-compose -f docker-compose.production.yml ps && sudo systemctl status nginx && df -h")
    print()
    print("# Logs completos")
    print("docker-compose -f docker-compose.production.yml logs --tail=50 && sudo tail -20 /var/log/nginx/error.log")
    print()
    print("# Restart completo")
    print("docker-compose -f docker-compose.production.yml restart && sudo systemctl restart nginx")
    print()
    print("# Backup e restart")
    print("sudo /home/ubuntu/backup.sh && docker-compose -f docker-compose.production.yml restart")
    print()
    print("# Verificação completa")
    print("curl -I https://marabet.com/health && docker-compose -f docker-compose.production.yml ps && sudo systemctl status nginx")
    
    print("\n🎉 COMANDOS ÚTEIS CONSOLIDADOS COM SUCESSO!")
    print("=" * 80)
    
    return True

def main():
    print("🚀 Iniciando consolidação de comandos úteis...")
    
    # Criar comandos úteis
    success = create_useful_commands()
    
    if success:
        print("\n🎯 COMANDOS ÚTEIS CONSOLIDADOS COM SUCESSO!")
        print("Sistema completo e funcionando!")
    else:
        print("\n❌ Falha na consolidação de comandos úteis")
        print("Verifique os logs acima para mais detalhes")

if __name__ == "__main__":
    main()
